### ISSUE TITLE
Blank exception page in dashboard

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1487] opened 2020-04-08 11:24 UTC
![image](https://user-images.githubusercontent.com/3112191/78778877-481de800-799c-11ea-98f5-724c0dd666e0.png)

**Comment by slowbackspace** [comment] 2020-04-09 06:56
duplicate of duplicate https://github.com/trezor/trezor-suite/issues/1363

**Closed as completed by slowbackspace** 2020-04-09 06:56 UTC
Labels: bug
