### ISSUE TITLE
Missing symbol before some ERC20 tokens name

### ISSUE THREAD

**Issue by cryptomar1o** [trezor/trezor-suite#6952] opened 2022-11-21 09:22 UTC
**Describe the bug**
For some ERC20 tokens, the symbol is missing before the token names.

**Info:**
-   Suite Version: desktop 22.11.1 (https://github.com/trezor/trezor-suite/commit/73ccf723353e0575a64f58b2f5775d20f072311f)
-   Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
-   OS: maOS Monterey
-   Bridge: 2.0.27
-   Firmware Version: Trezor Model One 1.11.2 regular

**How to reproduce**

1. Launch the application Trezor Suite (both desktop and web version, behaviour is the very same)
2. Check on of the following ERC20 token (does not matter if the token has a balance or you add it manually)
[HEX](https://eth1.trezor.io/address/0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39)
[Index](https://eth1.trezor.io/address/0x0954906da0Bf32d5479e25f46056d22f08464cab)
[Badger](https://eth1.trezor.io/address/0x3472A5A71965499acd81997a54BBA8D852C6E53d)
[Nexo](https://eth1.trezor.io/address/0xB62132e35a6c13ee1EE0f84dC5d40bad8d815206)

**Expected behavior**
The symbol is shown for those tokens before their name as for the other ERC20 tokens

**Screenshots**
<img width="376" alt="Screenshot 2022-11-17 at 3 07 33 PM" src="https://user-images.githubusercontent.com/52966597/203009987-f5366ae6-2713-43cc-ae55-1af83c834f34.png">

**Comment by komret** [comment] 2022-11-21 16:50
It's not a bug, it's a feature, implemented in [this commit](https://github.com/trezor/trezor-suite/commit/8fed4ff9336a4f9c7eef5d7ef29943c66208ad12#diff-7fe91df0275ac2c521d22ab6ced2f427b7d7eac291ce8641db79cd8197d7a987).
`const noName = !t.symbol || t.symbol.toLowerCase() === t.name?.toLowerCase()`, i.e. do not show the symbol if it is the same as the name.

Is it confusing? Should I remove the behaviour?

**Comment by komret** [comment] 2022-11-22 11:21
@sime
From Slack: "Is it confusing? -> hard to say, there was just one feedback until now from our users…"
https://satoshilabs.slack.com/archives/C01SXSHGK44/p1668758402923239

Please decide whether this behaviour should be changed, feel free to close the issue if not.

**Comment by sime** [comment] 2022-11-23 10:34
> It's not a bug, it's a feature, implemented in [this commit](https://github.com/trezor/trezor-suite/commit/8fed4ff9336a4f9c7eef5d7ef29943c66208ad12#diff-7fe91df0275ac2c521d22ab6ced2f427b7d7eac291ce8641db79cd8197d7a987). `const noName = !t.symbol || t.symbol.toLowerCase() === t.name?.toLowerCase()`, i.e. do not show the symbol if it is the same as the name.
> 
> Is it confusing? Should I remove the behaviour?

@gabrielKerekes @vladimirvolek 

This code change has introduced into an ADA related PR. Any hesitations about allowing token name and token symbol to appear side by side if they are the same?

**Comment by slowbackspace** [comment] 2022-11-23 11:10
I think that should have been cardano-specific change since we had no reason to change rendering of ethereum tokens => bug :disappointed: 

That condition should be evaluated only in cardano right? @vladimirvolek 

It was implemented because cardano tokens don’t always have a name/symbol. In such a case we are rendering only token fingerprint (unique identifier) and it didn’t make sense to render it twice as it is quite long (see screenshot, first token doesn’t have any name/symbol, second one does).

Should I open a PR? it should be rather quick fix to run that one line of code only in cardano, reverting rendering of ethereum tokens to the state before the cardano PR.

![image](https://user-images.githubusercontent.com/6961901/203532363-13f5b037-9758-491e-9289-44d972382338.png)

**Comment by komret** [comment] 2022-11-23 14:25
Thanks @slowbackspace, the condition to not show the symbol (and the dash) is fine for other networks, too, but the second condition (if symbol is the same as name) should be Cardano-specific or omitted entirely. Also, the variable should be called `noSymbol` rather than `noName`, I believe.

**Comment by slowbackspace** [comment] 2022-11-23 15:16
> Thanks @slowbackspace, the condition to not show the symbol (and the dash) is fine for other networks, too, but the second condition (if symbol is the same as name) should be Cardano-specific or omitted entirely. Also, the variable should be called `noSymbol` rather than `noName`, I believe.

I agree the naming is confusing. Second condition is needed in cardano because name and symbol fields both fallback to asset fingerprint in case of missing token name/symbol (see example of the asset below) - don't ask why, I can't remember, but it was necessary if we did not want to rewrite half of the token management in suite which is really tailored only for ethereum tokens. 

```
{
    "type": "BLOCKFROST",
    "name": "asset1cvmyrfrc7lpht2hcjwr9lulzyyjv27uxh3kcz0",
    "address": "6b8d07d69639e9413dd637a1a815a7323c69c86abbafb66dbfdb1aa7",
    "symbol": "asset1cvmyrfrc7lpht2hcjwr9lulzyyjv27uxh3kcz0",
    "balance": "1",
    "decimals": 0
}
```

The condition is a workaround to figure out that the cardano asset doesn't have a name (technically there is no symbol in cardano asset, at least not on chain, only optional name prop. I think that's why we called the variable `noName` 😅).

Renaming it to `noSymbol` and evaluating that 2nd condition only in cardano should solve things, so do you want me to make a PR or will you take care of it?

I am still not sure you need that first part (`!t.symbol`), IIRC ethereum tokens without symbol are stripped away during account creation, but let's keep it to not break anything.

https://github.com/trezor/trezor-suite/blob/b26e0891f4addcb155298dbc4d41ca8fe79d98db/suite-common/wallet-utils/src/accountUtils.ts#L383

**Comment by komret** [comment] 2022-11-23 15:54
@slowbackspace Good, please create a PR and assign me.

**Closed as completed** 2022-11-24 15:28 UTC
Labels: bug, EVM

**Comment by bosomt** [comment] 2022-11-28 10:03
**QA OK**

<img width="737" alt="image" src="https://user-images.githubusercontent.com/31506317/204249935-1c29a0e1-bf42-4542-86bd-fd9a2cdfe249.png">

**Info:**
 - Suite version: web 22.12.0 (9eda6a34372ed709612b67c006f2602094d2c4c7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
