### ISSUE TITLE
LTC B32 account informs you about BTC B32 account lower fees

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4609] opened 2021-12-06 09:19 UTC
**Describe the bug**
LTC B32 account informs you about BTC B32 account lower fees.
See screenshot. Same result on Production and staging Suite.

**Steps to reproduce:**
1. Enable LTC accounts
2. Observe LTC Bech32 account

**Info:**
 - Suite version: web 21.12.1 (48d05025d88905d197da84538fb8d4c6d6b6b9e0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.4 regular

**Screenshots:**
<img width="800" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/144819868-5edf2284-d6f7-4cee-929b-f5b71cc32d21.png">

**Comment by prusnak** [comment] 2021-12-06 09:33
Fix in https://github.com/trezor/trezor-suite/pull/4610

**Comment by hynek-jina** [comment] 2021-12-06 10:02
Duplicate of https://github.com/trezor/trezor-suite/pull/4610

**Closed as completed** 2021-12-06 17:17 UTC
Labels: bug

**Comment by bosomt** [comment] 2021-12-06 19:10
**QA OK**

**Info:**
 - Suite version: desktop 21.12.1 (c2f3c43646f88ec791001606428cd78f14d3a482)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
