### ISSUE TITLE
Fee level won't update

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2536] opened 2020-10-07 09:54 UTC
![ezgif-6-063cee6b6d51](https://user-images.githubusercontent.com/29627086/95316224-d31c6400-0893-11eb-80b1-855e2969ab24.gif)

**Comment by wendys-cats** [comment] 2020-10-08 09:57
duplicate of https://github.com/trezor/trezor-suite/issues/2023#issuecomment-651112624

**Comment by wendys-cats** [comment] 2020-10-08 10:28
**QA NOK**

Nixos OS + Chromium 85
Device TT 2.3.4 public (50854b921)
**SUITE Branch:** develop **Type:** web **Commit:** **426ce98fbcb16af057d8b2f5d636f88f4e374a23**

**Expected**
Fee level will update everytime the user changes it correctly.

**Actual**
When Custom fee is changed: Send button dissapears alltogether when the fee type is changed from Custom to something else, even if the total sum is within the account´s funds.


**video:** https://drive.google.com/file/d/1Qzx-pKXrwY2fvZYTtW6naNQgybYPCA3B/view

**Comment by szymonlesisz** [comment] 2020-10-12 10:04
oh, you were testing on outdated branch :) 426ce98 was 2 days old while closing this.
it should be fixed on the upcoming build 0e4aaf9

**Closed as completed by szymonlesisz** 2020-10-12 10:04 UTC
Labels: bug, send

**Comment by bosomt** [comment] 2020-10-26 09:50
**QA OK**

Nixos + Chromium 86.0.4240.75
Suite dev master 91d61f8
Device model T fw 2.3.4 commit 50854b921
