### ISSUE TITLE
Remove loading box

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2290] opened 2020-09-03 11:01 UTC
Prerequisite of this is issue is:  #2373 

Skeleton loading will be used here instead.

![Screen Shot 2020-09-03 at 12 56 09](https://user-images.githubusercontent.com/29627086/92106549-d8921480-ede4-11ea-9593-56917e87603d.png)

**Comment by keraf** [comment] 2020-09-03 14:32
Is this a duplicate of #2289 @matejzak ?

**Closed as completed** 2020-12-07 11:03 UTC

**Comment by bosomt** [comment] 2020-12-10 08:15
@matejzak 

This is what I see when I disable all coins, is this part of Skeleton implementation ?

![image](https://user-images.githubusercontent.com/31506317/101739699-31e69f80-3ac8-11eb-88c9-efb80a683b07.png)

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5

**Comment by bosomt** [comment] 2020-12-16 18:58
**QA OK**

Nixos + Firefox 82
Suite web dev master commit e771fd3c9b850f781e06f03072b3be55b881dcb9
Device model T fw 2.3.5
