### ISSUE TITLE
Strange 1px grey line over the "discreet mode" button

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2861] opened 2020-11-03 16:26 UTC
**Describe the bug**
![Screenshot 2020-11-03 at 17 24 23](https://user-images.githubusercontent.com/3435913/98012635-9e9bb980-1df9-11eb-9e80-00c3f2f2723f.png)

**Comment by prusnak** [comment] 2020-11-03 16:27
Duplicate of https://github.com/trezor/trezor-suite/issues/2843

**Closed as completed by prusnak** 2020-11-03 16:27 UTC
Labels: bug
