### ISSUE TITLE
Issue verifying signature

### ISSUE THREAD

**Issue by stanislavkozlovski** [trezor/trezor-suite#3945] opened 2021-06-25 08:31 UTC
**Describe the bug**
Trying to verify the signature of the Trezor Suite I downloaded from https://suite.trezor.io, I had trouble cleanly verifying the GPG signature.

**Info:**
 - Suite Version: 21.6.1
 - OS: Ubuntu 20.04

**Steps to reproduce:**
Following https://wiki.trezor.io/Apps:Trezor_Suite#How_to_run
1. `gpg --import satoshilabs-2021-signing-key.asc`
2. `gpg --verify ./Trezor-Suite-21.6.1-linux-x86_64.AppImage.asc`

**Expected result:**
I expect to receive no warnings from the `gpg --verify` output

**Actual result:**
```
$ gpg --import satoshilabs-2021-signing-key.asc
gpg: key E21B6950A2ECB65C: 1 signature not checked due to a missing key
gpg: key E21B6950A2ECB65C: "SatoshiLabs 2021 Signing Key" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

```
gpg --verify ./Trezor-Suite-21.6.1-linux-x86_64.AppImage.asc
gpg: assuming signed data in './Trezor-Suite-21.6.1-linux-x86_64.AppImage'
gpg: Signature made Wed 09 Jun 2021 03:48:19 PM EEST
gpg:                using RSA key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C
gpg: Good signature from "SatoshiLabs 2021 Signing Key" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

**Comment by AdamSHurwitz** [comment] 2021-07-08 19:39
The same warning message, _This key is not certified with a trusted signature!_, is occurring with the following steps.

**Steps**

1. Download the .dmg file, signature, and signing key from [https://suite.trezor.io/][1].
   - Signature: _Trezor-Suite-21.6.2-mac.dmg.asc_
   - Signing key: _satoshilabs-2021-signing-key.asc_

2. Run the verify command: `gpg --verify Trezor-Suite-21.6.2-mac.dmg.asc`

**Output**

> gpg: Signature made Wed Jun 30 12:57:23 2021 CDT
gpg:                using RSA key EB483B26B078A4AA1B6F425EE21B6950A2ECB65C
gpg: Good signature from "SatoshiLabs 2021 Signing Key" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EB48 3B26 B078 A4AA 1B6F  425E E21B 6950 A2EC B65C

**Configuration**

- Trezor Suite: 21.6.2
- OS: macOS BigSur 11.4

[1]: https://suite.trezor.io/

**Comment by AdamSHurwitz** [comment] 2021-07-08 19:52
@stanislavkozlovski, Also, it may help this issue getting attention from the Trezor team by adding the warning message in the title, i.e, **Warning Verifying Signature - This key is not certified with a trusted signature!**

**Comment by adam-hurwitz** [comment] 2021-07-08 19:57
This issue is a duplicate of [warning when verifying binaries #3751](https://github.com/trezor/trezor-suite/issues/3751) and should be closed.

**Closed as completed** 2021-08-23 22:00 UTC
Labels: bug
