### ISSUE TITLE
Trezor Connect popup will produce unreadable error when loggin into Polymarket with Bitcoin Only FW

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#15164] opened 2024-11-01 08:55 UTC
Steps:
- Have Bitcoin Only FW on the Trezor 
- Pair it with Rabby
- Try to Log In with it (with Rabby) on [Polymarket](https://polymarket.com/)

**Expected behavior**
- I get an human readable error that tells me to install an universal FW.

![image](https://github.com/user-attachments/assets/c5eeb410-6164-494e-bfbb-009d08b0b8f1)

**Comment by Hannsek** [comment] 2024-11-01 08:58
Duplicate of [this](https://github.com/trezor/trezor-suite/issues/15032). 

> Try to Log In with it (with Rabby) on [Polymarket](https://polymarket.com/)

:shame-nun:

**Closed as not planned by Hannsek** 2024-11-01 08:58 UTC

**Comment by mroz22** [comment] 2024-11-01 09:01
https://github.com/trezor/trezor-suite/pull/15034
