### ISSUE TITLE
Missing fiat balance for some transactions

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#3662] opened 2021-04-19 09:54 UTC
**Describe the bug**

Some of my transactions in the transactions history are missing fiat equivalent (the suite shows `$0.00`) next to the transaction.

![Screenshot 2021-04-19 at 11 54 29](https://user-images.githubusercontent.com/42201/115217876-3a9a5280-a106-11eb-873e-d1135684b86d.png)

When I click on the TX detail I see the historical fiat balance is missing:

<img width="365" alt="Screenshot 2021-04-19 at 11 52 35" src="https://user-images.githubusercontent.com/42201/115217429-cbbcf980-a105-11eb-8d15-d78a89e8382d.png">

This is not limited to outgoing TXs. I see the same behaviour for some of the incoming TXs as well.

**Firmware version and revision**

FW 2.3.6

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite Desktop
 - OS: macOS
 - Browser 
 - Version: 21.4.1

**Expected behavior**

To see fiat balance on all transactions in the history

**Comment by slowbackspace** [comment] 2021-04-21 10:21
closing as duplicate of https://github.com/trezor/trezor-suite/issues/3459

**Closed as completed by slowbackspace** 2021-04-21 10:21 UTC
