### ISSUE TITLE
Labels disappear when you bump or finalize transaction

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#7157] opened 2022-12-07 10:03 UTC
**Describe the bug**
Follow up of https://github.com/trezor/trezor-suite/issues/5770#
If you bump or finalize tx before its confirmed labels will disappear.

**Steps to reproduce:**
1. Send tx with labels
2. Bump/finalize tx
3. Check if labels are present

**Info:**
 - Suite version: desktop 22.12.1 (8e04a0545667dc828b96e5aaef8e91479c4edc60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/205087120-e0f041c5-a4d0-4895-a29e-5ca4c059a09d.png)

<img width="531" alt="image" src="https://user-images.githubusercontent.com/31506317/205087294-0b9f1708-0900-4e3b-bd3b-76d9a098bcfc.png">

**Comment by mroz22** [comment] 2022-12-08 12:51
i am sure there is another issue for this already

**Comment by bosomt** [comment] 2022-12-09 15:28
@mroz22 if we find it we will close this one ;)

**Comment by komret** [comment] 2024-07-10 14:41
Closing as duplicate of https://github.com/trezor/trezor-suite/issues/10047.

**Closed as completed by komret** 2024-07-10 14:41 UTC
Labels: bug, labelling
