### ISSUE TITLE
`meta httpEquiv` translates to `httpequiv` not `http-equiv`

### ISSUE THREAD

**Issue by sunknudsen** [trezor/trezor-suite#4626] opened 2021-12-09 13:26 UTC
**Describe the bug**

".onion available" button not showing on Tor Browser (Tails and macOS)

**Info:**

 - Remembered Wallet: not applicable
 - Suite Version: https://suite.trezor.io/web/
 - Browser: Tor Browser 11.0.2
 - OS: Tails 4.25, macOS Big Sur 11.6.1
 - Bridge: not applicable
 - Firmware Version: not applicable

**How to reproduce**

1. Go to https://suite.trezor.io/web/ using Tor Browser on Tails or macOS

**Expected behavior**

".onion available" button should show (go to https://sunknudsen.com/ using Tor Browser on Tails or macOS to see expected behavior).

**Screenshots**

![Screen Shot 2021-12-09 at 8 11 43 AM](https://user-images.githubusercontent.com/2117655/145403682-1eb3c559-fe82-4dfe-8fc1-b7246ac64a46.png)

What works for me is using following line in NGINX config rather that using `<meta httpequiv="onion-location" content="http://…onion"/>`.

```
add_header Onion-Location http://…onion$request_uri;
```

**Comment by prusnak** [comment] 2021-12-09 18:04
The issue is here. 

https://github.com/trezor/trezor-suite/blob/780c9d2e46a97b149d99ae077b89cd4ac7b37af4/packages/suite-web/src/static/index.html#L20-L23

In 0390b4354e38c3c7f869624e9b3011f01d5311ac we replaced `packages/suite-web/pages/_document.tsx` with `packages/suite-web/src/static/index.html` but since the file is not processed by React anymore we have to convert `httpEquiv` to `http-equiv` manually.

Fix in https://github.com/trezor/trezor-suite/pull/4748

**Comment by prusnak** [comment] 2022-02-03 15:52
I can see the https://suite.trezor.io/ is fixed (contains `http-equiv`), but https://suite.trezor.io/web/ is still broken (contains `httpequiv`). Reopening.

**Comment by mroz22** [comment] 2022-02-08 08:42
It looks like it have been fixed in the meantime (judging by staging, and dev). So I am moving this to February 16 project Needs QA  col.

**Comment by bosomt** [comment] 2022-02-08 19:16
**QA OK**

staging of 22.2.1

<img width="775" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/153059199-2bd2b008-9a7b-49ea-9080-771ece134bf7.png">

**Info:**
 - Suite version: web 22.2.1 (520802b8052d558de9c5f0ee55f9151ea5122eb4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Closed as completed by bosomt** 2022-02-08 19:16 UTC
Labels: bug, low hanging fruit
