### ISSUE TITLE
Desktop app: Tor connection issues (Discovery error Accounts were not loaded properly /  All backends are down)

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#3218] opened 2021-01-04 14:14 UTC
**Describe the bug**
- When a user is using Trezor Suite Tor feature error message: 
```
Discovery error
Accounts were not loaded properly
Bitcoin: All backends are down
``` 

is displayed

**Info:**
 - Suite Version: app version 20.12.1 (latest)
 - OS: OSX 10.15

**Steps to reproduce:**
1. Launch Suite
2. Enable Tor feature
3. Go to Bitcoin Wallet
4. Error message: 
```
Discovery error
Accounts were not loaded properly
Bitcoin: All backends are down
``` 
is displayed
5. Once Tor feature is disabled wallet works as expected

**Expected result:**
Suite should be working even with Tor feature enabled

**Actual result:**
Suite is not working correctly when Tor feature is enabled

**Comment by tsusanka** [comment] 2021-01-04 18:23
@trezor/qa please retest

**Comment by bosomt** [comment] 2021-01-05 10:13
**QA NOK**

Tested in

Windows 10 
Suite dev master commit af3dc0e34cef17c0be4a3578f1525e526105ac60


Steps:

1) Enable Tor
2) Disable Tor
3) go to Accounts

Results : 

Message `Backend is down` and it tries to connect over and over again. 
Settings/Coins/Advanced settings: `Not connected to backend yet`
Nothing changes even when you wait few minute.
When I enable Tor nothing changes, Suite still fails to connect to backends

**Comment by tsusanka** [comment] 2021-01-05 10:23
Thanks, could you please try also with [20.11.2](https://github.com/trezor/trezor-suite/releases)?

**Comment by sorooris** [comment] 2021-01-07 17:18
**20.11.2** QA NOK

However: it is possible to use Tor when adding (standard and hidden) wallets; the issue described above **occurs after the Tor button is toggled**.

Reconnecting the device and entering the passphrase when Tor is already on _does_ discover all the coins but it takes a while as expected (1-2 minutes), given the nature of data transfer on the Tor network.

Suite: app 20.11.2 b0dacc34
OS: Win10 19042.685, macOS Big Sur 11.1
Device: 2.3.5 889a369

![image](https://user-images.githubusercontent.com/10185314/103921477-d9301400-5112-11eb-91f6-b23a6872f9ca.png)

**Comment by prusnak** [comment] 2021-01-07 22:56
More reports are included in https://github.com/trezor/trezor-suite/issues/2876 which I closed as a duplicate of this issue

**Comment by artembryksa** [comment] 2021-01-10 17:21
Can confirm this issue, happened on Windows 10, latest firmware of Trezor and Suite.

Except for the issues stated above, the Trezor Suite seems to report that the wallet is empty, and thus requires to re-enter the passphrase.

Upon doing so, these errors show up, and the assets are labelled as "not loaded correctly".

![trezor3](https://user-images.githubusercontent.com/16197623/104130358-82c01100-5370-11eb-94b5-a6468fe26f5b.png)

**Comment by prusnak** [comment] 2021-01-10 22:20
It seems there is massive Tor DDoS going on at the moment - https://darknetdaily.com/?p=1030 - the error might be caused by this outage and there is nothing wrong at our side.

**Comment by tsusanka** [comment] 2021-01-14 19:20
I have tested this now again and it works for me but you can tell the performance is degraded. Accounts load eventually though. Could someone confirm please?

If that's the case indeed and it's not on our side I will discuss with @matejzak how we can improve this from the UX side (inform the user somehow etc. though we might just solve it via #2752).

**Comment by prusnak** [comment] 2021-01-14 19:33
I wonder whether we have some kind of timeouts that should be increased (to double or triple values) in case when Tor is enabled.

And of course showing "Network connection error" or "Tor connection error" would be much nicer than "Worker runtime error: Unhandled error".

**Comment by tsusanka** [comment] 2021-02-04 18:02
@prusnak there is no easy way to check the "health" of the network right? We just wanted to make sure with @matejzak this is definitely on the network side not at ours. It was lagging yesterday again

**Comment by prusnak** [comment] 2021-02-04 20:40
Don't know of any way, but maybe there is one ...

**Comment by DerekMiner** [comment] 2021-02-06 20:55
This bug has made the Suite completely unusable on my mac running Catalina 10.15.7. I have had one successful connection several weeks back, but since then it always says backends are down for all the wallets. Turning Tor off is not an option and exposes your wallet addresses and IP address, essentially until this is fixed my trezor wallet is completely useless through the trezor suite. Neither Reinstalling the app or rebooting the machine change anything. I am on the latest version of the Suite 20.12.1

Disabling Tor does allow them to load, but I will not be doing that with an wallet with actual coins in it

![Screen Shot 2021-02-06 at 1 59 57 PM](https://user-images.githubusercontent.com/9966028/107129586-a600b200-6883-11eb-84d2-8936ddc9dd31.png)

**Comment by prusnak** [comment] 2021-02-07 11:17
Tor network has troubles recently. I am not sure anything can be done on our side of things ... :-/

**Comment by prusnak** [comment] 2021-02-07 21:18
I updated the Tor binaries in https://github.com/trezor/trezor-suite/pull/3353 - hopefully this fixes the issue.

**Comment by sorooris** [comment] 2021-02-08 14:41
Update: the issue is unrelated and present without toggling Tor on/off -> #3370 created.

Suite: app 21.2.1 20f555fc
OS: macOS Big Sur 11.2
Device: 2.3.5 RC

~~QA NOK~~

~~Launching Suite with Tor on (previous session was shut down with Tor on) loads only a few of the accounts and then stops loading with placeholder images animating.~~

[macos_log-Tor-retest.txt](https://github.com/trezor/trezor-suite/files/5944303/macos_log-Tor-retest.txt)
![image](https://user-images.githubusercontent.com/10185314/107233643-16920500-6a23-11eb-8b40-67efb48d40be.png)
![image](https://user-images.githubusercontent.com/10185314/107233656-185bc880-6a23-11eb-9c91-3a1919e21fb1.png)

**Comment by tsusanka** [comment] 2021-03-11 12:01
@sorooris as I am looking at your latest post and I guess we can close this one? Matej tried Tor just now and it worked flawlessly.

**Comment by sorooris** [comment] 2021-03-11 12:39
@tsusanka Agreed, closing!

**Closed as completed by sorooris** 2021-03-11 12:39 UTC
Labels: bug
