### ISSUE TITLE
webUSB broken in latest (Android) Chrome 106 version

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#6512] opened 2022-10-10 13:35 UTC
**Describe the bug**

webUSB does not detect Trezor in Chrome 106 version

Tested and device not detected:  
- Brave based on 106 version in Android
- Chrome 106 in Android
- Chrome 107 beta Android and chromeOS
- Chrome 108 dev Android

Works as expected:
- Chrome 106 macoARM
- Chrome 105 Android
- Kiwi browser 105
- Edge 105 Android

**Info:**
 - Suite version: web 22.11.0 (e9fd9bbc75be4328d98581badd15545922a59a0f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.0 Universal (revision fd4f8601cf73c5744978f0e8c0aa43d863032a37)
 - Transport: WebUsbPlugin

**Video**

https://user-images.githubusercontent.com/216917/194903163-52e12045-b098-4b9c-8652-876cef5987b8.mp4

**Comment by SabatinoMasala** [comment] 2022-10-10 20:10
We've been seeing this issue in the field as well. Currently we are downgrading Chrome to the last version where it was working (104 or 105) to mitigate this.

The issue is that Chrome is not showing the _device chooser_ popup, and instantly throws an error `no device selected`.

**Comment by sime** [comment] 2022-10-11 07:44
Edge on Android v105 works.

**Comment by sime** [comment] 2022-10-11 07:45
@SabatinoMasala Have you spotted any Chrome changelogs that might provide context?

**Comment by Elkfoot2** [comment] 2022-10-12 14:14
See [chromium Issue 1373502](https://bugs.chromium.org/p/chromium/issues/detail?id=1373502): WebUSB not working on Android Chrome Version 106
It is a bug accidentally introduced in 106

**Comment by tomasklim** [comment] 2022-10-16 19:30
Probably will be fixed soon https://bugs.chromium.org/p/chromium/issues/detail?id=1373502#c29

**Comment by STew790** [comment] 2022-10-18 09:55
**QA OK**
I just tried it today and it seems to work again now with the latest update of Chrome.

![image](https://user-images.githubusercontent.com/48477147/196397980-e90bdc26-e58e-47f1-8f4b-ea77003d70a2.png)

**Info:**
 - Suite version: web 22.9.3 (2b9595fdfee9d36935d72af4af536d2fe4742f5e)
 - Browser: Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36
 - OS: Linux armv8l
 - Screen: 393x873
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: WebUsbPlugin

**Closed as completed by STew790** 2022-10-18 09:55 UTC
Labels: bug

**Comment by bosomt** [comment] 2022-10-18 10:02
**QA OK**

tested on my Android phone with latest version of Chrome and it works as expected.

**Comment by parkerlreed** [comment] 2022-10-19 17:01
How recent are we talking? On the Kiwi nightly and still getting nothing

![Screenshot_20221019_125944_Kiwi Browser](https://user-images.githubusercontent.com/841440/196756871-d6c845b9-7557-4522-a61f-6b9eb556b9b5.png)

**Comment by parkerlreed** [comment] 2022-10-19 17:06
Yeah weird. Lower Chrome release is working 

![Screenshot_20221019_130555_Chrome](https://user-images.githubusercontent.com/841440/196757858-d1b0beb9-1351-4b75-9796-1a8fe8f3155c.png)

**Comment by parkerlreed** [comment] 2022-10-20 03:29
Head up

Chrome Stable 106.0.5249.126 works
Chrome Beta 107.0.5304.36 does NOT work
Chrome Dev 108.0.5359.10 works

Looks like it has regressed again between 106 and 107 but fixed again after 108

**Comment by bosomt** [comment] 2022-10-20 09:00
@parkerlreed probably expected
There was 106 public version and 107 beta when webUSB was broken.
They fixed it in 106 so they probably moved to 108 in beta release.

**Comment by sime** [comment] 2022-10-20 12:30
Just to add Chrome Canary 109.05367.0 works

_Hopefully_ 107* won't regress.

**Comment by parkerlreed** [comment] 2022-10-20 20:23
As for Kiwi this is working as of 107.0.5304.66 released 30 minutes ago! Looks like we're good.
