### ISSUE TITLE
FW upgrade: Compare fingerprints

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1628] opened 2020-04-24 15:59 UTC
while upgrading from fw 1.6.2 to latest (1.9.something) device shows some hash and "Compare fingerprints" message. The problem is I don't see any hash in the fw update modal. Then after clicking "Abort" on the device I get "NULL" error.

<img width="617" alt="Screenshot 2020-04-24 at 17 58 23" src="https://user-images.githubusercontent.com/6961901/80232435-32274d00-8655-11ea-8be0-464da50d708d.png">

<img width="467" alt="Screenshot 2020-04-24 at 18 02 16" src="https://user-images.githubusercontent.com/6961901/80232783-bc6fb100-8655-11ea-8f64-1746da3ee0bb.png">

**Comment by sorooris** [comment] 2020-05-13 14:53
From what i've gathered in the issue description the problems were following:
1) no fingerprint was displayed.
2) aborting the process displayed a 'null' error message.

Upgrading from an older fw (tested with 1.6.3) to the current one (1.9.0) **displays a fingerprint correctly**:
![image](https://user-images.githubusercontent.com/10185314/81828386-0acbed80-953a-11ea-84d9-615c96e466f3.png)
Aborting the process on device still displays a 'null' error message:
![image](https://user-images.githubusercontent.com/10185314/81827936-8c6f4b80-9539-11ea-986d-76ea08a2f7d4.png)

**Comment by mroz22** [comment] 2020-05-13 15:19
great report thanx! and rip 1.6.3 firmware. 
so the only  problems here are:
1. fingerprint styling? 
1. null message on abort
otherwise it works smoothly?

**Comment by sorooris** [comment] 2020-05-24 18:06
Will retest tomorrow in the office.

**Comment by bosomt** [comment] 2020-06-01 05:26
connected device with 1.6.0 to test it,
suite doesn't detect it in bootloader mode.
I can give you that device to troubleshoot it if needed.

trezorctl get-features
Features (30 bytes) {
    bootloader_mode: True,
    firmware_present: True,
    major_version: 1,
    minor_version: 3,
    patch_version: 0,
    vendor: 'bitcointrezor.com',

![image](https://user-images.githubusercontent.com/31506317/83378376-da5cce00-a3d8-11ea-995e-a8447f5db0f1.png)

![image](https://user-images.githubusercontent.com/31506317/83378459-0aa46c80-a3d9-11ea-95a9-3a052341d4a9.png)

**Comment by mroz22** [comment] 2020-06-15 08:10
It actually does not work with mytrezor either. Bootloader 1.3.0 just seems to be too ancient.. We are aming for 1:1 feature parity so I am closing this.

**Comment by STew790** [comment] 2021-08-09 13:20
**QA NOK**

This issue is still present.

I just tried to update a device with FW 1.6.0 (BL 1.3.2) to the latest FW (1.10.2) on staging Suite and the Suite forces me to update because of old FW (which is fine) but after connecting the device in BL mode and confirming the update, the device shows me the fingerprint to compare it with Suite but Suite doesn't respond/show this at all, it just gets stuck at 92% (as shown in the screenshot).

**Expected result:**

Suite shows the fingerprint so that it can be checked against the one on the device

**Actual result**

Suite just gets stuck on 92% of the FW update and doesn't show anything that corresponds to what is shown on the device.

**Screenshot**
![image](https://user-images.githubusercontent.com/48477147/128712642-92c39c95-89d4-4752-911e-19ede23a48d7.png)

**Comment by eshaghoff** [comment] 2021-08-14 04:42
I'm experiencing the exact same issue

**Comment by Goosaba** [comment] 2021-08-17 18:40
I’m also having the same exact issue! Stuck at 92% and nothing displayed on screen to compare it to.

**Comment by STew790** [comment] 2021-08-18 07:40
@eshaghoff @Goosaba You can actually just click on "Finish" on the device and it will install FW properly, it's just that Suite doesn't show the fingerprint anymore. So just fyi.

**Comment by eshaghoff** [comment] 2021-08-18 11:13
I wish that was the case. It looks like my device is completely unusable now. I plug it in, and it’s automatically in boot loader mode with no prompts or ability to do anything. It’s like frozen. Help please. 

Sam

**Comment by sorooris** [comment] 2021-08-18 11:53
Hi @eshaghoff, you are describing something a bit different than what is being tracked in this issue; with the little info you provide it seems like the update got stuck on the intermediary firmware part. Don't worry, it shouldn't be serious.

However I'd recommend you go through our troubleshooting guide https://trezor.io/support/ or further get in touch with our customer service in case you can't resolve it in the troubleshooter.

**Comment by eshaghoff** [comment] 2021-08-18 12:04
It definitely started out as what is being tracked in this issue, and during that issue I disconnected my device, and now the device is in permanent bootloader mode. I wish I only had the original issue.

**Comment by sorooris** [comment] 2021-08-18 12:09
Don't worry Sam, you just need to finish the update so please get in touch with our customer service and one of our agents will guide you through it. Khob mishe, dadash!

**Comment by eshaghoff** [comment] 2021-08-18 12:38
That was a nice surprise haha

**Comment by bz-j** [comment] 2021-08-23 19:42
@eshaghoff @sorooris was customer service able to resolve for you? I am experiencing the exact issue.

I opened a ticket, but there is currently a 20 day wait for support...

**Comment by eshaghoff** [comment] 2021-08-23 20:31
No resolution. They replied to my email with a generic response that clearly didn’t reflect a human actually reading my ticket. I’m forced to buy a new device and recover using my seed.This has been a very bad experience caused by a Trezor software issue, and compounded by an absentee customer service policy.

**Comment by tsusanka** [comment] 2021-09-02 18:47
@STew790 could you please extract your [comment](https://github.com/trezor/trezor-suite/issues/1628#issuecomment-895217126) to a new issue and close this one? This one is getting quite messy.

**Closed as completed** 2021-09-03 09:33 UTC
Labels: bug
