### ISSUE TITLE
Better UX/UI: Account menu + ERC20 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3747] opened 2021-05-12 10:56 UTC
**Design:** [Zeplin](https://zpl.io/Vk148OZ) 

**This release (June 9th):** 

- [x] Tag on ETH indicating number of individual Tokens 
- [x] Tab `Tokens` next to the Overview tab on ETH _(Zeplin to be added here)_
- [x] Add account button
- [x] Fonts (weight, size etc.)   
- [x] Hover + Selected Account state: [Zeplin](https://zpl.io/ad3398E)

**Future release (July 14th):** 

- Un/Archive + Un/Favourite + Sort #3748

**Comment by bosomt** [comment] 2021-05-29 09:49
**QA OK**


**Info:**
 - Suite version: desktop 21.6.0 (b65e29291276cd6a03c2fa8035966139a2847f90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.4 regular

**Comment by bosomt** [comment] 2021-05-29 10:03
ok not so OK after all :)

how to replicate:

1) open ETH tokens in one passphrase wallet
2) add another passphrase wallet
3) you are navigated to BTC token tab ;) 

<img width="603" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120066000-3ef24d80-c06c-11eb-94ef-b42aa70d5fbe.png">

**Comment by glacierbits** [comment] 2021-05-29 11:57
I would also like to kindly ask you @matejkriz  to keep the Account details / Tokens white box at the same distance as are the other tabs (Send, Recieve, Overview), so the content doesn't jump around when the uses is switching context. Thanks! 

<img width="157" alt="Screen Shot 2021-05-29 at 12 54 09" src="https://user-images.githubusercontent.com/29627086/120069311-33f3e900-c07d-11eb-9afa-dcd4ca19b438.png">

**Comment by bosomt** [comment] 2021-05-29 12:22
Maybe you can adjust this one too when on it. Looks as expected when there are no transactions.
But as soon transaction graph range selector appears it doesn't keep same distance. 
 
https://user-images.githubusercontent.com/31506317/120069984-9ac6d180-c080-11eb-8de8-74854162fc88.mov

**Comment by matejkriz** [comment] 2021-05-31 13:45
the routing issue on switching the wallet is more general - 
the issue is switching wallet on some tab not available on the first available account

how to replicate some case:
1. open Trade dialog on non-BTC account in one passphrase wallet
2. switch to another passphrase wallet
3. you are navigated to Trade dialog on first account available
![routing_issue](https://user-images.githubusercontent.com/3729633/120201196-76582a00-c225-11eb-8cee-dbf02493f4be.png)


other case (ETH as first available account and switch wallet on some coin with Account details tab e.g. VTC, DASH, BTC testnet):
![routing_issue2](https://user-images.githubusercontent.com/3729633/120202011-5c6b1700-c226-11eb-9b5b-86fdacea55f8.png)


@matejzak is it OK to always redirect to Overview tab (/accounts route index) when user switch the wallet (passhprase/device) on any other tab from Accounts screen? We already switching to first available account.

**Comment by matejkriz** [comment] 2021-06-01 13:58
@bosomt 
- First boxes in all the tabs on Account screen should be at the same vertical position now.

- The logic of redirection on device/wallet switch has changed, so would be nice to test switching device/wallet on all types of screens. The new logic is:

1. User is not on Dashboard or Accounts route? Go to Dashboard.
2. User is on Accounts route but on any of the "sub-routes"/tabs? Go to Accounts index = Overview tab of the first available account.

**Comment by wendys-cats** [comment] 2021-06-09 13:43
**QA OK**

Tag on ETH indicating number of individual Tokens OK
Tab Tokens next to the Overview tab on ETH (Zeplin to be added here - was NOT added am upset) OK
Add account button OK
Fonts (weight, size etc.) OK
BTC token bug OK
redirection logic OK

**info**
**Suite version** web 21.6.1 0ce310eb30cff6396b91939d3293b34e8e50d7c1
**Device** TT 2.4.0 regular
**Browser** Chromium Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by sorooris** [comment] 2021-06-10 15:54
Can or should we close this issue and approve?

**Closed as completed by sorooris** 2021-06-10 15:54 UTC
Labels: account
