### ISSUE TITLE
Passphrase is turned on by default in Suite and Connect UX does not reflect that

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4880] opened 2021-06-10 12:40 UTC
Suite turns on passphrase by default. That means this UI is shown to every Suite user who uses third party via Connect even to those who have no idea what passphrase is.

![image](https://user-images.githubusercontent.com/1835345/121526325-8deb9b80-c9f9-11eb-9981-e8b7bd173fb2.png)

We should rework this dialog basically to something like this 

![image](https://user-images.githubusercontent.com/1835345/121526527-bf646700-c9f9-11eb-9a00-e62a1f611e9f.png)

**Comment by sime** [comment] 2022-03-28 11:36
Attaching design Passphrase unification [Figma](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=1111%3A535).
<img width="1440" alt="Onboarding" src="https://user-images.githubusercontent.com/216917/160389696-726dd5c0-59d4-4f1d-9f24-77ebc55128fa.png">

**Comment by typercampbell** [comment] 2022-08-11 16:24
Hey everyone! I submitted issue #5975 (now closed as it was a duplicate of this effort)

After working one-on-one with many users, I believe that even displaying a text field for passphrase entry—as Trezor Suite currently does—leads users down an unintended path (especially those new to bitcoin and private keys). I think a drop-down to display then the passphrase entry field would be a significant improvement in this regard.

My non-designer background has this to offer 😅 :

![Trezor_Connect](https://user-images.githubusercontent.com/57573735/184181804-7804223c-4511-4f91-8cfb-2a8998bfa306.png)

**Comment by sime** [comment] 2022-09-22 09:52
This is resolved in Connect v9!

<img width="1147" alt="Screenshot 2022-09-21 at 11 13 53 (1)" src="https://user-images.githubusercontent.com/216917/191716280-24a5faf9-9a14-4995-a1be-85a87881e18d.png">

PS @typercampbell Doesn't include your suggestion, but still keeping it in mind.

**Closed as completed by sime** 2022-09-22 09:52 UTC
Labels: feature, connect, connect-popup

**Comment by bosomt** [comment] 2022-09-25 08:04
**QA OK**

tested in https://connect.trezor.io/9/#
