### ISSUE TITLE
Incorrect message in Dashboard when all coins are disabled

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3667] opened 2021-04-20 10:45 UTC
**Describe the bug**
When all coins are disabled, Dashboard shows an incorrect error message "Assets were not loaded properly", suggeting having all coins disabled is an error instead of something that Suite allows. 

**Info:**
 - Remembered Wallet: no
 - Suite Version: web 21.4.1 commit 1baa8ced16f2f6a5d60e9f4d7911669f856123d8
 - Browser: Chromium Version 88.0.4324.182 (Official Build) (64-bit)
 - OS: NixOS 21.03
 - Bridge: version: 2.0.30
 - Firmware Version: TT 2.3.5

**Steps to reproduce:**
1. Disable all coins in Settings
2. Return to Dashboard and look at Assets section

**Expected result:**
A warning message "All coins disabled" or "Assets were not loaded"

**Actual result:**
An error message "Assets were not loaded properly". 

**Screenshots:**
![image](https://user-images.githubusercontent.com/58593111/115381569-fb3a3780-a1d3-11eb-8d96-7f9c53fd2150.png)

**Comment by bosomt** [comment] 2021-07-20 13:52
**QA NOK**

Still same _Assets were not loaded properly_ misleading error.

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular

**Comment by STew790** [comment] 2021-09-13 14:14
**QA NOK**

Issue still present.

**Info:**
 - Suite version: web 21.9.1 (8b28b4c5df6eebb039ee30a35fab0016dd30679a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Comment by tsusanka** [comment] 2021-10-12 09:18
Closing as a duplicate of https://github.com/trezor/trezor-suite/issues/4051.

**Closed as completed by tsusanka** 2021-10-12 09:18 UTC
Labels: bug
