### ISSUE TITLE
connect-explorer build/images pollution

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5609] opened 2022-06-13 17:27 UTC
`connect-explorer` build produces tons on unnecessary/unused images in `build/images` directory probably because it's using `@trezor/components` package where they are defined

**Comment by martykan** [comment] 2024-07-30 08:12
Resolved in the new Connect Explorer

**Closed as completed by martykan** 2024-07-30 08:12 UTC
Labels: bug, connect

**Comment by mroz22** [comment] 2024-07-30 11:02
great, is it really resolved? I remember giving up trying to fix this since it was caused by some huge index export from @trezor/components
