### ISSUE TITLE
Trezor suite never release camera usage after you open and close scan in Send form

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13460] opened 2024-07-23 06:09 UTC
**Describe the bug**
Trezor suite never release camera usage after you open and close scan in Send form.
Managed to replicate issue in Firefox and Chrome.
You can turn off camera by reloading or closing tab, navigate out of send form does not help.

EDIT: found out if you wait some time before closing modal camera is released, but if you only open and close modal in less than 5 seconds /for example you clicked on scan button in mistake/ it will hang forever

**Steps to reproduce:**
1. Navigate to `Send` form
2. Click on `Scan` button
3. Close `Scan QR code` modal via `X` botton
4. Wait till camera turns off
5. It never turns off

**Info:**
 - Suite version: web 24.8.0 (3e342aaa5ba12e4aa6da3ef81b687a59a8c3ddf0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![telegram-cloud-photo-size-4-5836807929485967709-y](https://github.com/user-attachments/assets/6400fa1b-eaad-4116-be2c-cf829fae7c9c)

**Comment by Lemonexe** [comment] 2024-08-16 13:53
FIY: can't reproduce on Linux Ubuntu, so it has to be fixed by a developer with MacOS.

**Comment by MiroslavProchazka** [comment] 2024-09-18 11:00
@bosomt can you please test on newest MacOs Sequoia?

**Comment by komret** [comment] 2024-09-24 13:53
I could reproduce this by quickly opening and closing the modal. This seems to be a bug in the underlying library as reported [here](https://github.com/JodusNodus/react-qr-reader/issues/379). I opened an [issue](https://github.com/trezor/trezor-suite/issues/14512) to replace the library. Let's close this one.

**Closed as not planned by komret** 2024-09-24 13:53 UTC
Labels: bug
