### ISSUE TITLE
Selection of macOS platform needs better UI

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4424] opened 2021-10-25 15:06 UTC
On landing page https://suite.trezor.io/ (and https://suite.trezor.io/start) there is no feedback on selection of mac platform. The only option to see what mac platform is selected is to check the link and looking for x64 or arm64 in the filename...
<img width="244" alt="image" src="https://user-images.githubusercontent.com/3729633/138718210-564a1958-0f2d-4df5-b1a4-3ec819bdc994.png">

Check how e.g. Chrome solve it here https://github.com/trezor/trezor-suite/pull/4420#issuecomment-950659164

 It's not technically possible to detect Apple Silicon on web reliably and it's because there are so few Apple Silicon users that it would be too strong information for fingerprinting.

**Comment by jerechinsky** [comment] 2021-10-26 11:42
Duplicate of https://github.com/trezor/trezor-suite/issues/4206

**Closed as completed by jerechinsky** 2021-10-26 11:42 UTC
