### ISSUE TITLE
High RAM usage/memory leak

### ISSUE THREAD

**Issue by Transisto** [trezor/trezor-suite#3214] opened 2021-01-03 06:33 UTC
![image](https://user-images.githubusercontent.com/388716/103473178-a200e200-4d63-11eb-81ab-7e2507fa2cbb.png)

Very few transaction, nothing happening.

**Comment by keraf** [comment] 2021-01-05 11:29
Hi @Transisto,

Could you provide some additional info please? 
 - Suite version
 - Browser (if using web suite)
 - OS
 - Bridge version
 - Firmware version

Cheers!

**Comment by keraf** [comment] 2021-02-09 16:45
Recently reported on Reddit after Suite has been left open for too long: https://www.reddit.com/r/TREZOR/comments/lfvmt3/trezor_suite_using_ungodly_amounts_of_memory/

**Comment by slowbackspace** [comment] 2021-02-15 18:57
I spent 2 hours with suite on mac and I couldn't reproduce any memory leak/high ram usage (on latest release 21.2.2). I used 2 connected devices (all seed + personal), created multiple wallets, enabled around 5 coins, tried to sent tx, I clicked around basic UI (dashboard/accounts/settings tabs), and after 2 hours memory usage was still basically the same. 

I believe the first step to solve these memory leaks is to find a minimal reproducible case. 
@trezor/qa will you help us please? :)


ohh btw user on reddit provided more detailed breakdown of trezor suite process in task manager, but I guess it won't help us much:
![image](https://user-images.githubusercontent.com/6961901/107984530-66933d80-6fc8-11eb-895a-538a55859375.png)

**Comment by sorooris** [comment] 2021-02-16 13:37
There was an issue with the search input that would cause high RAM usage ([here](https://github.com/trezor/trezor-suite/issues/3376#issue-805465350) and [here](https://github.com/trezor/trezor-suite/issues/3376#issuecomment-776707804)) but @keraf resolved it; we'll try to replicate the issue some other way and we'll let you know.

**Comment by sorooris** [comment] 2021-02-26 10:23
Replicated the issue on 20.12.1 by launching the app and letting it run idle for approximately 15+ hours - which resulted in ~3GB memory usage. However it is resolved by relaunching the app, couldn't replicate the issue reported on reddit (that it persists after the app is relaunched).

**Steps to reproduce:**
1. Launch Suite,
2. Add Standard wallet, Hidden wallet,
3. Enable all coins and let discovery finish for both,
(device disconnected, not sure if relevant)
4. Let the app run for 15+ hours idle.

I'll attempt to replicate the issue on the latest (21.2.3) build.

![image](https://user-images.githubusercontent.com/10185314/109288168-d0131780-7824-11eb-8c54-52168d064257.png)

Suite: app 20.12.1 be4e3a3 
OS: Win10 19042.844
Device: 2.3.5 public

**Comment by sorooris** [comment] 2021-03-01 10:51
Replicated the issue on **21.2.3** by launching the app and letting it run idle for approximately 50+ hours - which resulted in up to ~5GB memory usage (screenshot taken later when the usage has dropped to 4GB). Same as above, resolved by relaunching the app, couldn't replicate the issue reported on reddit (that it persists after the app is relaunched). Couldn't retrieve log unfortunately.

![image](https://user-images.githubusercontent.com/10185314/109479704-f3cf9b00-7a7a-11eb-8ca7-1dbc34d1621d.png)

Wallet remembered: Standard, Hidden (all coins enabled)
Suite: app 21.2.3 9cf47b5
OS: Win10 19042.844
Device: 2.3.5 public

**Comment by prusnak** [comment] 2021-03-01 11:02
> Replicated the issue on **21.2.3** by launching the app and letting it run idle for approximately 50+ hours

Did you suspend the computer during these 50 hours or it was 50 hours of uninterrupted run?

**Comment by sorooris** [comment] 2021-03-01 11:12
@prusnak uninterrupted - no suspend, only screen was dimmed

**Comment by sorooris** [comment] 2021-03-01 12:48
MacOS build ended in a Suite renderer process crash after approximately 8 hours when ran idle. Full terminal output / log per request or available in Asana task.

Wallet remembered: Standard, Hidden (all coins enabled)
Suite: app 21.2.3 9cf47b5
OS: macOS Big Sur 11.2.1
Device: 2.3.5 public

**Log (clipped):**
```
2021-02-27T06:16:55.491Z - DEBUG(csp): Header applied to https://cdn.trezor.io/dynamic/coingecko/api/v3/coins/chainlink?tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false
2021-02-27T06:17:31.288Z - DEBUG(csp): Header applied to http://127.0.0.1:21325/listen
2021-02-27T06:17:31.297Z - DEBUG(bridge): Setting header for http://127.0.0.1:21325/listen
2021-02-27T06:17:55.810Z - DEBUG(csp): Header applied to wss://s-east.ripple.com/

<--- Last few GCs --->

[4137:0x2700000000] 28010891 ms: Mark-sweep 1988.9 (2070.8) -> 1984.9 (2071.0) MB, 2958.7 / 0.0 ms  (average mu = 0.206, current mu = 0.018) allocation failure scavenge might not succeed
[4137:0x2700000000] 28013907 ms: Mark-sweep 1989.1 (2071.3) -> 1984.9 (2071.5) MB, 2977.9 / 0.0 ms  (average mu = 0.120, current mu = 0.013) allocation failure scavenge might not succeed


<--- JS stacktrace --->

2021-02-27T06:19:18.572Z - ERROR(content): Render process gone (reason: crashed
2021-02-27T09:42:37.400Z - DEBUG(window-control): Focus
```


**Screenshots:**
Missing renderer process
![image](https://user-images.githubusercontent.com/10185314/109498513-d3f8a100-7a93-11eb-97a2-d5750bfc4ddc.png)
WSoD
![image](https://user-images.githubusercontent.com/10185314/109498561-e672da80-7a93-11eb-83b0-ce52c28f9699.png)

**Comment by prusnak** [comment] 2021-03-01 19:45
@sorooris which coins were enabled in the suite you left running?

**Comment by Transisto** [comment] 2021-03-01 21:30
I've used this software twice, This is how much it grew since 18h ago.

![image](https://user-images.githubusercontent.com/388716/109561607-69535f80-7aab-11eb-9327-681e49c419c9.png)

**Comment by prusnak** [comment] 2021-03-01 22:26
@Transisto which coins do you have enabled?

**Comment by Transisto** [comment] 2021-03-01 22:35
> @Transisto which coins do you have enabled?

BTC and ETH

**Comment by sorooris** [comment] 2021-03-02 10:33
@prusnak all coins enabled

**Comment by bosomt** [comment] 2021-03-02 22:46
I was able to kinda reproduce problem,
I got above 1GB in few hours 
I sent Ropstein TX and minimized app when notification about received TX was still present.
Wallet was saved /Standard wallet/ and coins that are supported by T1 were enabled.
 
See attached log

[logx.txt](https://github.com/trezor/trezor-suite/files/6072209/logx.txt)

Windows 10
Suite 21.2.3 9cf47b5b526bbb5cda585e717fbbf0f5b93b8cc0

**Comment by slowbackspace** [comment] 2021-03-04 11:50
So far we found 2 possible causes:
- connect log issue  https://github.com/trezor/connect/pull/771
- multiple blockchain-link workers https://github.com/trezor/trezor-suite/issues/3490 https://github.com/trezor/connect/pull/773 (waiting for new connect release & suite integration)

These should get out in March release and hopefully dramatically improve Suite memory usage.

**Comment by tsusanka** [comment] 2021-03-05 11:31
@slowbackspace merged in develop and cherry-picked to release. Let's close and reopen if needed?

**Comment by sorooris** [comment] 2021-03-08 15:45
**QA NOK**

The issue still persists.
- Launching Suite with all coins and labelling enabled and running it idle for ~28 hours still results in usage of 466 threads, becoming almost unusable.

Detailed log available [here](https://drive.google.com/file/d/1Dmtdkw3FeOmGuUQ1oprNY65pVNPfJnm7/view?usp=sharing).

Activity monitor:
![image](https://user-images.githubusercontent.com/10185314/110343353-b051cf80-802c-11eb-9eeb-739753b1ea55.png)

Wallet remembered: Standard, Hidden
Coins: All coins enabled
Labelling: enabled
Suite: app 21.3.1 1dbc5b720515c39a47f1dc58391dbebf1d766394
OS: macOS Big Sur 11.2.2
Device: 2.3.5 public, disconnected

**Comment by sorooris** [comment] 2021-03-09 10:00
I let the app run overnight with labelling off and seems to have improved.

Detailed log available [here](https://drive.google.com/file/d/1WegtVbdriKy_lIoJTO8yQLbVL4Vb_NJP/view?usp=sharing).

Wallet remembered: Hidden
Coins: All coins enabled
Labelling: disabled
Suite: app 21.3.1 1dbc5b7
OS: macOS Big Sur 11.2.2
Device: 2.3.5 public, disconnected

![image](https://user-images.githubusercontent.com/10185314/110453543-8b119f80-80c6-11eb-9250-b07dedb6568c.png)

**Comment by prusnak** [comment] 2021-03-09 10:15
> I let the app run overnight with labelling off and seems to have improved.

That's a good clue - maybe something within the labeling code is keeping references to old closed connections? @slowbackspace

**Comment by slowbackspace** [comment] 2021-03-09 15:25
> **QA NOK**
> 
> The issue still persists.
> 
> * Launching Suite with all coins and labelling enabled and running it idle for ~28 hours still results in usage of 466 threads, becoming almost unusable.
> 
> Detailed log available [here](https://drive.google.com/file/d/1Dmtdkw3FeOmGuUQ1oprNY65pVNPfJnm7/view?usp=sharing).
> 
> Activity monitor:
> ![image](https://user-images.githubusercontent.com/10185314/110343353-b051cf80-802c-11eb-9eeb-739753b1ea55.png)
> 
> Wallet remembered: Standard, Hidden
> Coins: All coins enabled
> Labelling: enabled
> Suite: app 21.3.1 [1dbc5b7](https://github.com/trezor/trezor-suite/commit/1dbc5b720515c39a47f1dc58391dbebf1d766394)
> OS: macOS Big Sur 11.2.2
> Device: 2.3.5 public, disconnected

Looking at log it looks like you were using filesystem as a storage for metadata, is that correct? Could you try to reproduce it with dropbox/gdrive? 
I wonder if could be something in our fs provider which handles storing/reading metadata files.

edit: does someone know why it reads all metadata files every 3 minutes? 🤔 
nitpick: if there was no memory leak/high ram usage then this is not a correct issue to reopen 😬

**Comment by slowbackspace** [comment] 2021-03-10 11:46
I made custom build where I change the interval for reading metadata files from 3 minutes to 6s, this is what I got after letting computer sleep during the night with suite running 😁 Still not completely sure if it is really related to labeling, but results are interesting.

Probably related to timers throttling discussed in https://github.com/trezor/trezor-suite/issues/3534 

<img width="823" alt="Screenshot 2021-03-10 at 12 29 23" src="https://user-images.githubusercontent.com/6961901/110624085-098d4080-819e-11eb-81c3-1e00c7eb83de.png">


<img width="886" alt="Screenshot 2021-03-10 at 12 29 02" src="https://user-images.githubusercontent.com/6961901/110624077-07c37d00-819e-11eb-8ac4-f8e7e7d6be79.png">

**Comment by sorooris** [comment] 2021-04-06 08:14
hey y'all, is the fix for this going to be included in the April release?

**Comment by tsusanka** [comment] 2021-04-06 08:22
I think we should retest on develop because some of the PRs @slowbackspace is mentioning did not make it into v21.3.1. But we can also wait for the Freeze and test on that.

**Comment by slowbackspace** [comment] 2021-04-06 08:23
> hey y'all, is the fix for this going to be included in the April release?

I'm not aware of any merged fixes related to high memory usage, in the other issue (discussion in https://github.com/trezor/trezor-suite/issues/3534#issuecomment-795360987 moved to https://github.com/trezor/trezor-suite/issues/3661) we've discussed other culprits that may be causing this, I haven't dig more into it since these issues two are basically the same and I believe fixing the discussed issues could move us in the right direction.

edit: fixed link

**Comment by slowbackspace** [comment] 2021-05-06 08:27
@keraf I'll assign this to you as the master of electron app 😁 Not sure if there is something else that can be done besides trying to fix that throttling behaviour which has separate issue.

**Comment by tsusanka** [comment] 2021-06-17 08:13
Let's retest on 21.6.1.

**Comment by sorooris** [comment] 2021-06-17 12:13
After quick check with @tsusanka Windows build will be tested with build version 21.6.2, macOS 21.6.1.

**Comment by sorooris** [comment] 2021-06-21 13:04
I let the apps run again on each device, first with all coins enabled and labelling on (25 hours), then additionally with Tor enabled (25 hours), and did not experience any peaks in memory usage - probably solved by the [Connect PR](https://github.com/trezor/trezor-suite/commit/564b3327af5c56659a20710a761f3c8462c292b8). I propose we close this issue and reopen in case anyone reports again.

 -| Win10 | macOS 
-|-|-
OS Build | 19042.1052 | Big Sur 11.4
Wallet remembered | yes | yes
Coins | All enabled | All except XRP (T1)
Labelling | enabled | enabled
Tor | disconnected, later connected | disconnected, later connected
Suite | app 21.6.2 c0e30df | app 21.6.1 0ce310eb
Device | TT 2.4.0 [ea3596](https://github.com/trezor/trezor-firmware/commits/ea3596ad8) |  T1 1.10.1 [3204fd](https://github.com/trezor/trezor-firmware/commits/3204fd68)

System monitor
![image](https://user-images.githubusercontent.com/10185314/122765619-fb70b500-d2a0-11eb-91b6-2a6b27a7639a.png)

Task manager
![image](https://user-images.githubusercontent.com/10185314/122765659-06c3e080-d2a1-11eb-8059-f67021f5bef7.png)

**Closed as completed** 2021-06-21 20:08 UTC
Labels: bug

**Comment by kelvinwop** [comment] 2022-05-09 10:08
![image](https://user-images.githubusercontent.com/30770221/167388628-a5eb70e3-88d6-4cda-a9b6-d1dce7774f5c.png)
![image](https://user-images.githubusercontent.com/30770221/167388683-b828285b-543d-4cf6-8060-c3efd54af817.png)

**Comment by kelvinwop** [comment] 2022-05-09 10:12
![image](https://user-images.githubusercontent.com/30770221/167389375-f9686fbc-910e-45b0-bed1-93a979b88413.png)

![image](https://user-images.githubusercontent.com/30770221/167389913-bd03b539-b844-477d-82f5-ad96b7075d22.png)

**Comment by sorooris** [comment] 2022-05-09 13:46
@kelvinwop hey Kelvin, screenshots alone don't usually qualify as bug reports; could you maybe provide precise steps to reproduce, ideally in a single comment to keep the issue tidy? Thanks!
