### ISSUE TITLE
Fiat price overlaps coin amount in left panel

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11010] opened 2024-02-02 14:37 UTC
**Describe the bug**
Fiat price overlaps coin amount in left panel when you have longer fiat value.
managed to replicate it with ARS and CZK

**Info:**
 - Suite version: web 24.2.0 (dff38a5be23e54353640a85a4845136131e24505)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T1B1 1.8.3 regular (revision df0963ec48f01f3d07ffca556e21ff0070cab099)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="189" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/109a781c-6f3b-4f25-b072-8aff311d0943">

**Comment by dahaca** [comment] 2024-02-02 15:40
duplicate of https://github.com/trezor/trezor-suite/issues/10815

**Closed as completed by dahaca** 2024-02-02 15:40 UTC
