### ISSUE TITLE
Errors shown during custom firmware installation

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#5807] opened 2022-07-18 14:19 UTC
**Describe the bug**
"Error: Device call in progress" is shown (four times) during custom firmware installation. Installation works, though.

**Steps to reproduce:**
1. Go to device settings
2. Install custom firmware (can be the same that is already installed
3. Look at the toast messages

**Info:**
 - Suite version: desktop 22.6.5 (62202b1294efebe1300ca806cf9108bbbbe18f21) - happens in 22.7.2 as well
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.5 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Expected result:**
No error messages displayed.

**Actual result:**
Error messages displayed.

**Screenshots:**
![Screenshot 2022-07-18 at 16 02 25](https://user-images.githubusercontent.com/42465546/179531082-d8fc1f1f-44ff-4a9a-8f34-8f5a342b6829.png)

**Comment by bosomt** [comment] 2022-08-01 09:02
**QA NOK**

i was i able to reproduce issue in latest public version of suite.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/31506317/182113159-ae78eb5d-8bf9-415b-a406-91d8bb41896b.png">

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: 
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment] 2022-08-03 07:45
**QA NOK**

looks like bigger problem to me than errors.
Custom FW dialogue is touching device that should ignore.

1. i have TT and T1 connected
2. trying to install custom FW to TT
3. suite asks me to reconnect device in BL mode
4. during re-connection i get 4 errors 
5. now T1 is asking me to reboot to bootloader mode
6. I confirm and i ended up with empty T1 due to TT firmware loaded to device ;)

<img width="345" alt="Screenshot 2022-08-03 at 9 39 55" src="https://user-images.githubusercontent.com/31506317/182552426-9f5181b7-a1ad-41c0-a679-04f123c714e1.png">

**Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 Universal (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment] 2022-11-14 08:13
**QA NOK**

issue is still present

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: bridge 2.0.32

**Comment by bosomt** [comment] 2023-10-10 14:01
**QA OK**

fixed in https://github.com/trezor/trezor-suite/issues/9577

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.2 regular (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33

**Closed as completed by bosomt** 2023-10-10 14:01 UTC
Labels: bug, settings
