### ISSUE TITLE
@suite-desktop > browser communication

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1420] opened 2020-04-02 08:29 UTC
- [ ] Handle requests from browser and open electron app
- [ ] Create webextension?
- [ ] trezor-connect (3rd party apps) requests handled in electron

**Comment by slowbackspace** [comment] 2020-04-02 12:15
related https://github.com/trezor/trezor-suite/issues/991 (I guess the old issue may be closed in favour of this one?)

**Comment by tsusanka** [comment] 2021-09-02 18:42
I think this is a duplicate of https://github.com/trezor/trezor-suite/issues/3294. Please reopen if I am mistaken.

**Closed as completed by tsusanka** 2021-09-02 18:42 UTC
Labels: feature
