### ISSUE TITLE
Desktop autoupdate - Win10 - download progress stuck at 0.00 B

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3202] opened 2020-12-21 19:27 UTC
**Describe the bug**
Confirming update displays a download progress modal which stays stuck on 0.00 B/0.00 
 B even though the download is in progress in the terminal.

**Info:**
 - Suite Version: app 20.12.1 be4e3a3 -> 21.1.0 
 - OS: Win10 19042.630
 - Firmware Version: 2.3.4 public

**Steps to reproduce:**
1. Launch Suite from terminal with the `--pre-release` flag,
2. Confirm the update modal,
3. Observe.

**Expected result:**
Download progress modal is displayed, file size in it is calculated correctly and active download progress is displayed.

**Actual result:**
Total file size is displayed as 0.00 B and download progress is displayed 0.00 B with no apparent progress.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/102807252-98b86280-43be-11eb-93bc-7e67d6526d1a.png)

**Comment by sorooris** [comment] 2020-12-21 19:28
#2965, #3151

**Comment by tsusanka** [comment] 2020-12-21 20:25
I think this sort of kind of happens more when you have done an autoupdate once before. I've had a proper progress bar the first time.

**Comment by bosomt** [comment] 2021-02-01 14:17
**QA OK**

Windows 10 latest update
Suite commit e6156ff4

**Comment by sorooris** [comment] 2021-02-01 17:03
**QA OK**

Couldn't replicate, download progress displayed correctly.

Suite: app 20.1.0 -> 21.1.0 48b5674
OS: Win10 19042.746
Device: 2.3.5 RC

**Comment by STew790** [comment] 2021-06-16 12:28
**QA NOK**

Unfortunately, this is happening again. Video attached. The update is downloaded but the progress bar is not reflecting the downloading progress.

https://user-images.githubusercontent.com/48477147/122218536-d8b05c00-ceae-11eb-915b-2cd8895f12d1.mp4



Suite: app 21.5.1 -> 21.6.2 4e29f3d
OS: Win10 
Device: 2.3.6

**Comment by tsusanka** [comment] 2021-06-16 12:38
@STew790 could you please test with 21.4.1 -> 21.5.1? Without `--pre-release` flag - these are production versions.

**Comment by STew790** [comment] 2021-06-16 13:17
@tsusanka Unfortunately, this is not possible. 21.4.1 is not showing me an update and even when I try to check for update in the settings it won't find any.

**Comment by tsusanka** [comment] 2021-06-16 14:12
Ok, so we have simulated this and it does the same for 21.4.1 -> 21.5.1.

**Comment by goodhoko** [comment] 2021-06-30 18:48
Just spent a good portion of my day digging through this. My findings so far:

Despite this issue was closed and then re-opened it was probably never directly addressed. The [linked PR](https://github.com/trezor/trezor-suite/pull/3224) mentioned this issue initially but the mention was later removed and the commits don't seem to do anything in this direction neither. I suspect the [QA](https://github.com/trezor/trezor-suite/issues/3202#issuecomment-771006247) [approvals](https://github.com/trezor/trezor-suite/issues/3202#issuecomment-770890059) can be blamed on the undeterministic nature of this bug (see below).

I could not reproduce this on mac - the progress worked just fine.

I could reproduce this on windows but very unreliably.
 - It happens more often after fresh install of Suite. Reproducing this in an app that has been launched a few times (and update rejected) was much harder. But not impossible. 🤷 
- Reinstall in itself doesn't guarantee the issue will happen. It seems the key lies in files that don't get deleted by the uninstallation wizzard. That is:
    - `C:\Users\<user>\AppData\Local\Roaming\@trezor`
    - `C:\Users\<user>\AppData\Local\@trezorsuite-desktop-updater`
    Uninstalling Suite, manually deleting these directories, then installing Suite again seems to reproduce this issue most reliably, but not 100%.
- On the other hand deleting the mentioned directories alone doesn't reproduce the issue neither - it must be done along re-installation of the whole App.

The problem and its eventual fix hides for 99% in the [electron-builder](https://github.com/electron-userland/electron-builder) package, or its [electron-updater](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater) sub-package to be specific. Suite merely [proxies](https://github.com/trezor/trezor-suite/blob/1e57daf24f8e9a9719949c8f1c483d3353357cf0/packages/suite-desktop/src-electron/modules/auto-updater.ts#L120-L128) the progress from `electron-updater` to the UI. When this bug occurs there is just no information coming from `electron-updater`.[1]


Possible next steps:
- Enable `electron-updater`'s logs by providing a logger [here](https://github.com/trezor/trezor-suite/blob/1e57daf24f8e9a9719949c8f1c483d3353357cf0/packages/suite-desktop/src-electron/modules/auto-updater.ts#L52) and dig deeper.
- Try to create a minimal reproducible example and submit it as a bug to the [electron-builder repository](https://github.com/electron-userland/electron-builder)

---

[1] Deduced from absence of ` DEBUG(auto-updater): Downloading xx% (xx MB/xx MB)` [logs](https://github.com/trezor/trezor-suite/blob/1e57daf24f8e9a9719949c8f1c483d3353357cf0/packages/suite-desktop/src-electron/modules/auto-updater.ts#L121-L126) when this bug occurs and conversely their presence when this bug doesn't occur.

**Comment by tsusanka** [comment] 2021-07-01 08:16
@goodhoko btw are we on latest `electron-builder` and/or `electron-updater`?

**Comment by tsusanka** [comment] 2021-07-01 08:25
Also this could be related? https://github.com/electron-userland/electron-builder/issues/5800

**Comment by tsusanka** [comment] 2021-07-01 08:26
I think we should: 
1. Wait for #3670 where node is upgraded (right?)
2. Update electron stuff to latest
3. Check if this does not get fixed

**Comment by goodhoko** [comment] 2021-07-01 12:31
> are we on latest `electron-builder` and/or `electron-updater`?

Good point! We're currently 5 patches behind the latest. Here's a [PR](https://github.com/trezor/trezor-suite/pull/3974) that bumps it to the latest version. That should be safe operation supposing `electron-updater` maintainers obey the semver semantics.

> Also this could be related? electron-userland/electron-builder#5800

I have that issue in mind. I wanted to enable the `electron-updater` logs to asses whether it's the same problem or not.

> I think we should: 
> 1. Wait for #3670 where node is upgraded (right?)
> 2. Update electron stuff to latest
> 3. Check if this does not get fixed

ACK. We can also do 2. before 1. hence my PR above.

**Comment by goodhoko** [comment] 2021-07-08 10:29
@trezor/qa  I just merged [a commit](https://github.com/trezor/trezor-suite/commit/92ffdec083487d6de6652332b696b1af5ffb3704) that *may* fix this. It **won't** be included in the upcoming release (July 14) to give us enough time to test it.

I assume you have the needed tools/procedures to test the autoupdate of develop builds, right?

I'll  optimistically close this. Let's reopen if the issue persists.

**Closed as completed by goodhoko** 2021-07-08 10:29 UTC
Labels: bug, autoupdate

**Comment by sorooris** [comment] 2021-07-08 12:28
@goodhoko FYI I've tested this yesterday with 21.7.1 and deleting the contents of the C:\Users\0xdeadbeef\AppData\Local\@trezorsuite-desktop-updater (and C:\Users\user\AppData\Roaming\@trezor\ for good measure as well) folder(s) resolves this issue for one update. Not sure if it's of any help for you.

Let's see what future testing brings us.

**Comment by sorooris** [comment] 2021-08-04 13:41
**QA OK**

Tested:
1. autopdate flow - all correct here
2. "re-download" - file was already present in "C:\Users\<username>\AppData\Local\@trezorsuite-desktop-updater\pending" and displayed very briefly progress bar, but installation modal almost immediately afterwards
3. deleting the file from the pending folder and re-initiating autoupdate - same as usual autoupdate flow, progress bar with correct downloaded size was displayed

Suite: app 21.8.1 8dfc3fbf9faa870f6c7e6017a63ffeb311cf5b16
OS: Windows 10 Pro 19042.1110
Device: model One 1.10.2

Screenshots:
1. autoupdate flow
![image](https://user-images.githubusercontent.com/10185314/128191086-ce1a9b02-edcb-4fb9-bf43-f7e7d5920398.png)
![image](https://user-images.githubusercontent.com/10185314/128191090-2df96da8-0507-4e24-9cbe-229022097c01.png)
2. didn't manage to catch the progress bar :sweat_smile: 
![image](https://user-images.githubusercontent.com/10185314/128191143-469280eb-2960-47ae-a8ca-4aa78ea07749.png)
3. progress bar after deletion
![image](https://user-images.githubusercontent.com/10185314/128191172-ce2206fd-6943-422f-ba22-f5cdf5f8afe2.png)
