### ISSUE TITLE
Frozen Transaction after Update Suite

### ISSUE THREAD

**Issue by Intastanio** [trezor/trezor-suite#3657] opened 2021-04-16 14:53 UTC
Hello, 

I have a transaction with a very low fee frozen.
I set the transacción two days ago in the night, the day after y updated the suite early in the morning  to 21.4.1 V,  after that the operation is frozen, Bump Fee and Cancel Trans doesn't works. always show "Not enough  Funds"

When i set the operation i almost empty the wallet, but know i have funds enough to cover all the operation amount, not just the double fee...

Cancell transaction also shows same Msg -> "Not enough  Funds" and button remain Grey.

I made another operations , still unconfirmed, and I'm able to bump the fee or cancel transaction, button changes to green.

Thanks a lot!!

Trezor One
Mac OS
V 24.4.1

![Captura de pantalla 2021-04-16 a las 16 52 20](https://user-images.githubusercontent.com/82665232/115042872-27a03c00-9ed4-11eb-8741-d376c2c513a0.png)

**Comment by prusnak** [comment] 2021-04-16 15:42
You can't bump the fee if there are not enough funds in the account.
This is a duplicate of https://github.com/trezor/trezor-suite/issues/3460

**Comment by Intastanio** [comment] 2021-04-16 16:12
Hello how are you,
Mthank you for the response.

I have funds  enought to bump it.
That’s the problem 

Original transaction was 285$, I bought 359$ this morning to bump it and I had same result.

Button doesn’t work.

Any idea?
Victor Olmos

**Comment by Intastanio** [comment] 2021-04-18 15:42
Hello all!!!

-Maybe i have not explained well.

When i made the operation, i almos empty the wallet.. right,  the transaction enter the pool, and i wait... no funds to bump it. (285$ total)

I updated the suite…next day.

After two days, i bought more BTC, enough to remade the entire operation agin if necessary, 350$.

I tried to bump it… Button remain grey, "no funds enough" —> with 350$ confirmed in the wallet.
i try  to cancel it.. "no funds enough" —> with 350$ confirmed in the wallet.

i made another operation as said in method “double commission” Child pay for father? -> to another wallet 100$ double fee, 24$… same result.

I made another operation, then bump it to prove if its working… correct, green button, operation bumped —> Ok.

Right know the operation is in the pool 

https://btc1.trezor.io/tx/992378b63814cc88617c10501044e4557e56f4a45ef76fd7096f8ebee7baa8a4

https://mempool.space/es/tx/992378b63814cc88617c10501044e4557e56f4a45ef76fd7096f8ebee7baa8a4


Can you help me? is there another way to bum ip?

I have 3 wallet in trezor suite  (2 Native SegWit
Bech32 , 1 SegWit) , I also tried trezor wallet, but it only shows one wallet (1 SegWit)… not the correct one for me.

Thank you.

is it possible to have a bug, that frozen pending transactions  if you update the suite?

**Comment by prusnak** [comment] 2021-04-23 07:38
This was confirmed as a duplicate of #3460

**Closed as completed by prusnak** 2021-04-23 07:38 UTC
