### ISSUE TITLE
Missing padding in Accounts view

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2948] opened 2020-11-12 00:01 UTC
**Describe the bug**
NITPICK ALERT! Feels like there should be some padding in "No transactions" view

**Screenshots:**
![image](https://user-images.githubusercontent.com/3112191/98878063-4c563a80-2482-11eb-80ba-ea11967fa52a.png)

**Comment by mroz22** [comment] 2020-11-12 08:50
And I add this.
![image](https://user-images.githubusercontent.com/30367552/98917226-66b50600-24cc-11eb-836d-dddede6aaa83.png)

**Comment by slowbackspace** [comment] 2020-11-12 10:50
@mroz22 that was most likely caused by the styled-components upgrade we reverted

**Comment by jerechinsky** [comment] 2021-04-15 07:02
I am guessing this has now been mitigated. Closing for now.   
<img width="1388" alt="Screenshot 2021-04-15 at 9 02 03" src="https://user-images.githubusercontent.com/75733878/114827704-8ec8ce00-9db8-11eb-8e66-bfd1399ef5ff.png">

**Closed as completed by jerechinsky** 2021-04-15 07:02 UTC
Labels: bug, good first issue
