### ISSUE TITLE
Cannot move the desktop window by grabbing the top panel

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#2761] opened 2020-10-26 19:00 UTC
This happens only when dev tools are open.

![image](https://user-images.githubusercontent.com/3112191/97215309-91ad1380-17c4-11eb-819b-5df4fb1d24b9.png)

Also, Icons are different than the other mac os apps - padding, size, etc.

**Comment by prusnak** [comment] 2020-10-26 22:11
Which revision is this? Grabbing the top panel works with 48edc16001ac0aad3085575774c65bc3b30e5501 **on Linux**

**Comment by vladimirvolek** [comment] 2020-10-26 22:43
> Which revision is this? Grabbing the top panel works with [48edc16](https://github.com/trezor/trezor-suite/commit/48edc16001ac0aad3085575774c65bc3b30e5501) **on Linux**

48edc16001ac0aad3085575774c65bc3b30e5501

**Comment by tomexx** [comment] 2020-10-27 14:02
I cannot reproduce the moving issue on my Mac. I tried dev mode and Mac build from both release branch `46ab9e5b99354942d8ddec2df8ccc5db734c12be` and commit `48edc16001ac0aad3085575774c65bc3b30e5501`) but it does work as expected.

Regarding the design, it was approved by @matejzak so if you think it is not correct, please discuss with him first. Thx

**Comment by keraf** [comment] 2020-10-27 14:20
I can reproduce it on the test Mac but I have no idea what could cause this. I've played around with `-webkit-app-region: drag;` but nothing helped. I have the feeling that I'm missing something really obvious :sweat_smile: I'm also very unfamiliar with this platform, any help would be appreciated!

Edit: The issue only happens while the Dev Tools are open. Not sure why and the fix from what I see online is just to close the Dev Tools when you want to move the window :smile: Can we close this as won't fix?

**Closed as completed** 2020-10-27 14:25 UTC
Labels: bug

**Comment by vladimirvolek** [comment] 2020-10-27 14:29
Created https://github.com/trezor/trezor-suite/issues/2771
