### ISSUE TITLE
Green outlining of send form boxes is missing

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#5330] opened 2022-05-04 16:32 UTC
**Describe the bug**
Green outline of the boxes in send form and also in sign and verify and OP_RETURN, that signalize the user filled out the boxes correctly, are not present in the new staging version of Suite. Wrong input is correctly shown as red.
I am not really sure if this is because of https://github.com/trezor/trezor-suite/issues/4632 but my guess it's very probable.

**Steps to reproduce:**
1. Go to Accounts and select an account (doesn't matter which coin, for example BTC)
2. Click on "Send"
3. Fill out any relevant BTC address
4. The text box for address doesn't turn green.

**Info:**
 - Suite version: desktop 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Expected result:**
Text boxes turn green when correctly filled out.

**Actual result:**
Text boxes doesn't turn green when correctly filled out.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/166728014-b614e5d5-7056-47da-8eee-8a4058581efd.png)

**Note(s):**

**Comment by dahaca** [comment] 2022-05-05 15:51
The absence of green is not a bug. The design has been changed, now here is no explicit `success` state, only the `error` state - input turns red. Green was too extra and it wasn't implemented for all inputs even. So in order to not turn forms into a traffic light I propose adding a check to the address input component, since it is in a way one of the most important inputs and giving a user a bit more confidence definitely would benefit :)

**Comment by hynek-jina** [comment] 2022-05-06 07:36
@dahaca 
So can we close the issue then?

**Comment by dahaca** [comment] 2022-05-06 08:34
@hynek-jina Nope I will link it to the PR with the Address input changes

**Closed as completed** 2022-05-09 09:23 UTC
Labels: bug

**Comment by STew790** [comment] 2022-05-10 08:15
**QA OK**

Green tick is present when correct address is entered.

![image](https://user-images.githubusercontent.com/48477147/167581712-a866a9f1-9817-4777-be01-a01f58e06e1e.png)
**Info:**
 - Suite version: desktop 22.6.0 (54abdebf4991620800bd7fe718fdb99f9efed80f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.5 regular (revision 3f12742669bd782cac374a1750d517f4fd88c43b)
 - Transport: bridge 2.0.31
