### ISSUE TITLE
Zero value ERC20 tokens

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#9659] opened 2023-10-16 11:25 UTC
**Describe the bug**
Support agents are handling sad users who sent their tokens to the wrong chain on a regular (weekly basis)
This is problematic for Exchange and Sell features in Suite

**Expected behavior**
Let’s not show tokens without FIAT value at all

**Screenshots**
![image](https://github.com/trezor/trezor-suite/assets/12121074/5154dd95-e1bd-442a-a508-74dfc1416064)
![image](https://github.com/trezor/trezor-suite/assets/12121074/16d20c4a-3647-4e57-8234-19b8c77cc8cf)

**Comment by Hannsek** [comment] 2023-10-16 11:31
Duplicate of [this](https://github.com/trezor/trezor-suite/issues/6595).

**Comment by Hannsek** [comment] 2023-10-16 12:35
misunderstood, my bad, sorry

**Closed as completed** 2023-10-18 14:37 UTC
Labels: bug, trading

**Comment by bosomt** [comment] 2023-10-19 10:47
**QA OK**

maybe we can consider to hide tokens that have 0 amount in account too ?

![Screenshot 2023-10-19 at 12 41 17](https://github.com/trezor/trezor-suite/assets/31506317/3c2f4a56-bb62-48c9-911c-f857bb377409)
![Screenshot 2023-10-19 at 12 41 24](https://github.com/trezor/trezor-suite/assets/31506317/3dccf686-6283-4792-922f-ee1e1600cea4)
![Screenshot 2023-10-19 at 12 43 14](https://github.com/trezor/trezor-suite/assets/31506317/4a63bd6c-34ff-42f0-8cfa-573e468c8cc6)


**Info:**
 - Suite version: web 23.11.0 (1abb3790e0c6c87d94924d4c7d765c6392deed4a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 3840x2160
 - Device: Trezor T2T1 2.6.3 regular (revision b95b2182fa67f7823f25e724d6702e531312e918)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment] 2023-10-19 12:45
@bosomt It will be handled here https://github.com/trezor/trezor-suite/issues/6595
