### ISSUE TITLE
Intermediary firmware offered when updating old model T firwmare

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4135] opened 2021-08-11 06:38 UTC
**Describe the bug**

When you try to update old version od model T firmware Suite will try to install intermediary firmware.
This will trigger error on device and in Suite 

`Installation failed
Error: Invalid vendor header`

`Cannot install latest firmware. Will install intermediary fw instead.`

**Steps to reproduce:**
1. Connect device with 2.0.5 firmware
2. Try to update to current 2.4.1 firmware
3. Observe error on device and Suite

**Info:**
 - Suite version: web 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.0.5 regular

**Screenshots:**

<img width="637" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/128981073-de8c0b1d-536c-4192-b933-2464bd219ef2.png">

https://user-images.githubusercontent.com/31506317/128980975-f8338d59-d769-4802-bedb-8a51ca9291fa.mov

**Comment by bosomt** [comment] 2021-08-22 20:18
**QA OK**

empty 2.0.5 > 2.1.1 > 2.4.1
initialized 2.0.5 > 2.1.1 > 2.4.1 


**Info:**
 - Suite version: web 21.9.0 (dd23ecc920f7bf6fab3e63e7e30bdced32989cdd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular

**Comment by windsok** [comment] 2021-08-29 03:04
I have the same issue trying to update from 2.0.6 -> 2.4.1

**Comment by matejkriz** [comment] 2021-08-30 07:32
@windsok Please wait for new version 21.9.0, release is planned on September 8th. I'm sorry for that issue.

**Comment by STew790** [comment] 2021-09-13 13:44
**QA NOK**

I get a prompt to update to 2.1.1 first, unfortunately, the 2.1.1 FW is not in staging environment, so I can't finish the update.

**Info:**
 - Suite version: web 21.9.1 (8b28b4c5df6eebb039ee30a35fab0016dd30679a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.0.5 regular
 
 
![image](https://user-images.githubusercontent.com/48477147/133094635-c658ac00-2918-4954-b495-95018fd5d388.png)

**Comment by matejkriz** [comment] 2021-09-13 14:07
@STew790 I see where the issue is. It is broken for 2.0.5, 2.0.6 and 2.0.7. Could you please confirm that it is at least working with FW >= 2.0.8?

**Comment by STew790** [comment] 2021-09-13 14:31
@matejkriz When I tried to update from 2.0.8, 2.0.9 and 2.0.10 I got prompt to update to 2.4.2 and I was able to install it as well.

![image](https://user-images.githubusercontent.com/48477147/133102502-e5974c86-7eec-4cf3-9b92-180454bd3917.png)

![image](https://user-images.githubusercontent.com/48477147/133101607-7582630f-9a32-48bb-a092-cd972bd292a2.png)

**Comment by matejkriz** [comment] 2021-09-13 16:00
cool, thanks @STew790! and fix for oldest FWs is on the way (waiting just for deployment to staging)

**Comment by matejkriz** [comment] 2021-09-14 09:19
fixed in 21.9.2

**Comment by STew790** [comment] 2021-09-14 12:20
**QA OK**

Updated from 2.0.5 > 2.1.1 > 2.4.2 without any problem (multiple times).

**Info**:
 - Suite version: desktop 21.9.2 (cc85c69e3d6556e673c4d30f39953179f690b663)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Closed as completed** 2021-09-22 10:22 UTC
Labels: bug
