### ISSUE TITLE
Onboarding - device seemingly disconnected after completing onboarding with firmware update

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#4250] opened 2021-09-08 14:37 UTC
**Describe the bug**
Completing onboarding with a firmware update and selecting the Access Suite button redirects back to the Welcome page with the device seemingly disconnected, even though it's still connected and detected by Bridge.

**Info:**
 - Suite Version: app and web, 21.9.1 8b28b4c
 - Browser: none (app), Chromium 92.0.4515.107
 - OS: macOS Intel 11.5.2 Big Sur, NixOS 21.05
 - Bridge: Suite-bundled 2.0.31, webUSB
 - Firmware Version: model T 2.4.0 -> 2.4.2, model One 1.10.2 -> 1.10.3

**Steps to reproduce:**
1. Initiate onboarding,
2. Perform firmware update,
3. Complete onboarding (select the Access Suite button).

**Expected result:**
Suite's Wallet type selection modal is displayed.

**Actual result:**
Welcome page with a prompt to connect device is displayed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10185314/132529710-d21922de-4431-46bc-96a5-1ea73bd67e8b.png)
![image](https://user-images.githubusercontent.com/10185314/132530013-bc1681b0-34b9-42f5-943f-9bc3787499ca.png)

**Note(s):**
Firmware update is required for this bug to occur.

**Comment by bosomt** [comment] 2021-09-08 14:40
**QA NOK**

i was able to reproduce issue with empty 1.10.2 device onboarding that included update.
Reconnection of device solved it.

**Info:**
 - Suite version: desktop 21.9.1 (8b28b4c5df6eebb039ee30a35fab0016dd30679a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by sorooris** [comment] 2021-09-08 14:42
@bosomt's log [trezor-suite-log-1631109649788.txt](https://github.com/trezor/trezor-suite/files/7129682/trezor-suite-log-1631109649788.txt)

**Comment by STew790** [comment] 2021-09-08 14:47
**QA NOK**

I was able to reproduce this as well with 1.10.2 device updated in onboarding to 1.10.3.
Reconnection also solved the issue for me

**Info**:
 - Suite version: web 21.9.1 (8b28b4c)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model 1 1.10.3 regular

**Comment by wendys-cats** [comment] 2021-09-08 14:59
Was not able to reproduce this issue on 21.8.1 - update from T1 1.10.1 to 1.10.2.

**Suite**: APP 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
**OS**: Win10
**Device**: T1 1.10.2 regular

**Comment by tsusanka** [comment] 2021-09-08 18:52
I tried to replicate this and it seems to me it happens only during an update from 1.10.x. When onboarding from an empty device (no FW) it seems to work. Just seemed worth pointing out :).

- Suite version: web 21.9.1 (8b28b4c)
- OS: NixOS Firefox 90.0.2
-  Device: T1 1.10.2 regular

**Comment by bosomt** [comment] 2021-09-09 07:06
i had same result with empty Trezor model T with firmware 2.4.1

**Info:**
 - Suite version: desktop 21.9.1 (8b28b4c5df6eebb039ee30a35fab0016dd30679a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Comment by jerechinsky** [comment] 2021-09-23 08:10
fixed by #4258, I believe

**Closed as completed by jerechinsky** 2021-09-23 08:10 UTC
Labels: bug
