### ISSUE TITLE
can not close or cancel window "Hidden wallet"

### ISSUE THREAD

**Issue by ybaidiuk** [trezor/trezor-suite#3618] opened 2021-04-10 13:48 UTC
macOS , trezor one. 
after chose "Add Hidden wallet" i can not close or cancel window "Hidden wallet"

**Comment by prusnak** [comment] 2021-04-10 13:50
Suite Version?

**Comment by ybaidiuk** [comment] 2021-04-10 13:57
> Suite Version?

Version 21.3.2 (21.3.2.10723)

**Comment by ybaidiuk** [comment] 2021-04-10 18:09
Same stuff for transaction verification. 
Window "Enter PIN Check your Trezor screen for the keypad layout."
I can not cancel operation with "X" or "Esc" or my Trezor.

<img width="352" alt="Screenshot 2021-04-10 at 20 08 37" src="https://user-images.githubusercontent.com/11969255/114280222-a1e64180-9a38-11eb-9646-a7000542a5fd.png">

**Comment by glacierbits** [comment] 2021-09-14 08:40
Related #1576

**Comment by tomasklim** [comment] 2023-04-26 10:13
Duplicate of #6941

**Closed as completed by tomasklim** 2023-04-26 10:13 UTC
Labels: feature

**Comment by bosomt** [comment] 2023-04-28 05:59
**QA OK**

**Info:**
 - Suite version: desktop 23.5.0 (0e2010aa3ca28fd407107948cb608de5c36a02b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.0 Bitcoin-only (revision a97dfd3a4f4a709a08e125946f6e1c96a0cc7ec0)
 - Transport: BridgeTransport 2.0.27
