### ISSUE TITLE
Transaction detail border detail visual glitch

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13539] opened 2024-07-29 09:08 UTC
Border should have the save width as it's content. 

Current state:

<img width="818" alt="Screenshot 2024-07-26 at 18 12 35" src="https://github.com/user-attachments/assets/70a550ba-6163-43df-b1a3-0e172188eccd">

**Comment by hstastna** [comment] 2024-08-02 13:32
Hi @jvaclavik I cannot reproduce, looks ok to me:
![light_mode](https://github.com/user-attachments/assets/986225ce-a45a-488d-8d15-111f1bc7a5ff)
![dark_mode](https://github.com/user-attachments/assets/09b3cb58-2c27-429a-a0f5-458433aacf1e)

I think this was already fixed by PR https://github.com/trezor/trezor-suite/pull/13146. WDYT?

**Comment by hynek-jina** [comment] 2024-08-05 09:27
Looks good.. thanks 👍

**Closed as completed** 2024-08-06 18:52 UTC
Labels: bug
