### ISSUE TITLE
Feedback & Suggestion - missing empty input validation

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3823] opened 2021-06-02 11:25 UTC
**Describe the bug**
Both Feedback and Bug inputs/textareas are missing empty input validation and can be sent without any info provided.

**Info:**
 - Remembered Wallet: any
 - Suite Version: web 21.6.1 7d50da6b
 - Browser: Chromium 91.0.4472.77
 - OS: NixOS 20.09
 - Bridge: any
 - Firmware Version: T1 1.10.0

**Steps to reproduce:**
1. Navigate to the top-right settings menu -> Learn & Discover -> Feedback or Suggestion,
2. Select either Bug or Suggestion,
3. Leave form empty and send.

**Expected result:**
Empty input is validated and is not allowed to be sent.

**Actual result:**
Input is not validated for 0 characters and is sent.

**Screenshots:**
N/A

**Comment by goodhoko** [comment] 2021-06-04 10:29
@sorooris Thanks for detailed description of the bug. I'll assign this to @tomasklim who'll work on the UI part, that handles (or should) the validation soon.

**Closed as completed** 2021-07-01 12:03 UTC

**Comment by goodhoko** [comment] 2021-07-01 13:50
@trezor/qa  The intended behaviour is described in [this commit](https://github.com/trezor/trezor-suite/commit/3d123d44b5d65bb825a19c403f7a366e89efa6e7):
> Disable the submit button when
> - the description is empty or
> - category is empty on bug-submission page or
> - rating is empty on feedback-submission page.

**Comment by sorooris** [comment] 2021-07-06 07:57
**QA OK**

Suite: 21.7.0 8b018e2f
Browser: Chrome 91.0.4472.77
OS: NixOS 21.05
Device: model T 2.4.0 ea3596ad8
