### ISSUE TITLE
New notification panel

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3226] opened 2021-01-06 09:28 UTC
Design: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5ff5ed4f7fb47d77f3be6017) 

To be positioned this way: 

<img width="1230" alt="Screenshot 2021-01-07 at 10 45 24" src="https://user-images.githubusercontent.com/29627086/103880476-73736600-50d9-11eb-8f33-e6f6369a85cd.png">

**Comment by robertbrada** [comment] 2021-01-11 12:07
@matejzak  What is the difference between **Notifications** and **All activity** tabs? Does the **Notifications** tab display only transaction-related information? It seems to me there is nothing like **All activity** in the current Suite version.

**Comment by bosomt** [comment] 2021-01-29 10:24
@robertbrada looks like only tx notifications 

![image](https://user-images.githubusercontent.com/31506317/106263348-8aaefa80-6224-11eb-9658-18e532765c24.png)

**Comment by robertbrada** [comment] 2021-01-29 11:04
> @robertbrada looks like only tx notifications
> 
> ![image](https://user-images.githubusercontent.com/31506317/106263348-8aaefa80-6224-11eb-9658-18e532765c24.png)

@bosomt  Can you be more specific about what you mean by that?

**Comment by robertbrada** [comment] 2021-01-29 11:07
I made the distinction by myself and marked these notification types as important. However, this can be changed easily any time of course
 
![image](https://user-images.githubusercontent.com/44506010/106267835-8259be00-622a-11eb-8454-3b6e5ea8e0b8.png)

**Comment by bosomt** [comment] 2021-01-29 11:07
@robertbrada you asked 18 days ago: " Does the Notifications tab display only transaction-related information? It seems to me there is nothing like All activity in the current Suite version." so i tried to give you answer

**Comment by robertbrada** [comment] 2021-01-29 11:10
Yes thank you for your answer, later I got the context haha. I thought you were pointing at some bug since this was closed and merged already

**Comment by bosomt** [comment] 2021-01-29 13:38
@matejzak 

I don't see `View details` box in dark mode. See difference 

![image](https://user-images.githubusercontent.com/31506317/106281400-775d5880-623f-11eb-990e-4bf290fc8520.png)
![image](https://user-images.githubusercontent.com/31506317/106281442-8217ed80-623f-11eb-8baa-d037c51be895.png)

**Info:**
 - Suite version: desktop 21.1.0 (e73dfba83051f953b15baa216b0d14697680078c)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Comment by sorooris** [comment] 2021-02-02 16:08
Issue still persists, details above; reopening.

**Comment by robertbrada** [comment] 2021-02-02 16:10
> @matejzak
> 
> I don't see `View details` box in dark mode. See difference
> 
> ![image](https://user-images.githubusercontent.com/31506317/106281400-775d5880-623f-11eb-990e-4bf290fc8520.png)
> ![image](https://user-images.githubusercontent.com/31506317/106281442-8217ed80-623f-11eb-8baa-d037c51be895.png)
> 
> **Info:**
> 
> * Suite version: desktop 21.1.0 ([e73dfba](https://github.com/trezor/trezor-suite/commit/e73dfba83051f953b15baa216b0d14697680078c))
> * OS: Linux x86_64
> * Screen: 1920x1080
> * Device: model One 1.9.4 regular

@matejzak 

Is this an issue to be solved? The problem is that the Dropdown in dark mode has the same background as the tertiary button. 
But both of these colors follow the design guidelines. So there are three options:

1. leave as it is
2. make the tertiary button background lighter **for this specific use case**
3. make the dropdown's background darker, but it does not look good according to the screenshot 
![backgroud](https://user-images.githubusercontent.com/44506010/106627621-4485ce00-6579-11eb-8c22-b9349213654a.png)

**Comment by slowbackspace** [comment] 2021-02-03 16:21
I am for changing the color of panel background, I even think that's the proper way to go since design uses BG_WHITE, that means in dark mode it should looks exactly like in 3rd option @robertbrada posted. But I do agree that contrast is not stellar.

**Comment by glacierbits** [comment] 2021-02-16 13:13
Discussed with Ondra, let's go for the 3rd option. 🙏🏽  Contrast issues to be fixed eventually.

**Closed as completed** 2021-02-27 21:22 UTC
Labels: notifications

**Comment by bosomt** [comment] 2021-03-01 16:54
**QA OK**

Nixos 20.09
Suite dev master commit 6451544a2dbfc9cc582b69c112fb4d2585483da2
Device 2.3.5 public version
