### ISSUE TITLE
Click outside of modal should close it

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1381] opened 2020-03-25 11:48 UTC
On all modals (where it logically makes sense - close button is available) user should be able to close it by a clicking outside of the modal area.

**Comment by slowbackspace** [comment] 2020-03-25 12:01
duplicate of https://github.com/trezor/trezor-suite/issues/257 Closing old one so it doesn't look like it has been such a low priority that we didn't solve it in one year :)

**Comment by glacierbits** [comment] 2020-03-25 12:04
@slowbackspace Haha, thanks!

**Comment by szymonlesisz** [comment] 2020-03-26 20:40
not ALL modals, there are certain modals that are "not-closeable", for example ApplicationState modal ("Device is in bootloader mode" / "Device required FW update" etc...)

**Comment by glacierbits** [comment] 2020-03-26 21:04
Sure! As mentioned in the description: Only the modals that make logical sense and have the close button or X inherently enabled / present.

**Comment by wendys-cats** [comment] 2020-04-07 12:10
Issue: Cannot close by clicking outside of modal in some cases
 
Check recovery seed  scenario
Steps to reproduce: 
1 Click on Settings - device - Check recovery seed

Expected behavior
Modal can be closed by clicking outside of it

Actual behaviour
Modal has a Cancel button, but closing it by clicking out of modal bounds does not work.

**Closed as completed** 2020-04-10 14:36 UTC
