### ISSUE TITLE
Chrome Freezes When Scanning QR Code

### ISSUE THREAD

**Issue by schulzemic** [trezor/trezor-suite#3165] opened 2020-12-09 17:21 UTC
When testing https://github.com/btcpayserver/btcpayserver/issues/2110, I noticed that the Chrome browser on Android freezes each time when scanning QR Code.

**Info:**
 - Suite Version: suite.trezor.io, https://github.com/trezor/trezor-suite/commit/6629e9f2c9712322ed2d0a1c93b6b328071c1418
 - Browser: Chrome, version 86.0.4240.198
 - OS:  Android 11, Oxygen OS 11.0.5.6.KB05BA
 - OnePlus 8T

**Steps to reproduce:**
1. Access Trezor using https://suite.trezor.io/web
2. Select "Send" and Scan scan any of the requests as described in https://github.com/btcpayserver/btcpayserver/issues/2110

**Expected response
Process payment request

**Actual result:**
Chrome freezes immediately, but can be revived with the "Square" button.

**Screenshots:**
Mode a small video here: https://drive.google.com/file/d/1YRIjGXQxTTY9DtWNPd6mSaQdu-hhMDmg/view?usp=sharing

**Comment by bosomt** [comment] 2020-12-10 12:10
**QA OK**

Chrome 87 
Andorid 9 /Huawei P20 Lite/
Suite.trezor.io commit 6629e9f2c9712322ed2d0a1c93b6b328071c1418

I was able to scan same BTC address, suite says unsupported address format and you have to click on `Convert to lowercase format` but it works.

**Comment by slowbackspace** [comment] 2020-12-10 12:33
Hello @schulzemic! Thanks for filling a bug report.
 It seems like an issue with newer Android release as I also wasn't able to reproduce it on Android 9 (oneplus 3t), but also ran into issues on Android 11 (pixel 3a). I'll look into it.

edit: chrome 86.0.42... on android 10 oneplus 7t also works fine.
edi2: I also can't reproduce it inside android emulator running x86 android 11 & chrome 83/87. I need to get my hands on some android 11 phone real soon 😅 

edit3: Bug tracked in [Chrome's bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1148532) (eh actually it is duplicate of [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=1138823)), in the meantime we'll try to apply a workaround

**Comment by NandanSpeedshield** [comment] 2021-04-21 07:15
Hello, the error still exists in Pixel 4 (Android 10). Any workaround for the issue?

**Comment by bosomt** [comment] 2021-05-12 13:09
tested via Xiaomi Redmi Note 10 4GB/128GB Pebble White  with **Android 11**
yes Chrome freezes , but when i switch to other app and back immediately address is correctly scanned

**Comment by STew790** [comment] 2021-05-13 16:37
Tested this on Redmi Note 9 Pro 6GB RAM with Android 10 QKQ1 and Chrome 90.0.4430.210 and works just fine.

**Comment by glacierbits** [comment] 2021-09-02 15:40
Let's re-open if issue re-appears.

**Closed as completed by glacierbits** 2021-09-02 15:40 UTC
Labels: bug
