### ISSUE TITLE
Coinmarket: Learn more button is on two lines

### ISSUE THREAD

**Issue by LukasRada** [trezor/trezor-suite#14041] opened 2024-08-30 12:08 UTC
**Describe the bug**
I assume the text Learn more of the button/link should be on single line, but it is on two lines currently. Be aware that the fee component is used also on another places (components).

**How to reproduce**

1. Select any account in Suite
2. Go to trade section
3. Go to Exchange
4. Select Custom fee

**Expected behavior**
I assume the text Learn more of the button/link should be on single line.

**Screenshots**
![image](https://github.com/user-attachments/assets/5c50fd8b-f552-4210-a4e8-34cb25879cc1)

**Comment by MiroslavProchazka** [comment] 2024-08-30 12:13
This is caused by redesing ob Suite banners, cc @jvaclavik

**Comment by MiroslavProchazka** [comment] 2024-09-18 09:11
Should be fixed in develop, @trezor/qa please check

**Comment by bosomt** [comment] 2024-09-18 10:23
**QA OK**

<img width="648" alt="image" src="https://github.com/user-attachments/assets/d654264b-481c-4499-9ca0-6572a450108d">



**Info:**
 - Suite version: web 24.10.0 (92e5a0598bafb8ccc1b1e30734db0778fe9885c4)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0

**Closed as completed by bosomt** 2024-09-18 10:23 UTC
Labels: bug
