### ISSUE TITLE
Transaction signing error: Encountered invalid prevhash

### ISSUE THREAD

**Issue by ThanaNL** [trezor/trezor-suite#4746] opened 2022-01-14 16:54 UTC
**Describe the bug**
Tried to send DOGE from my wallet and received this error message: Transaction signing error: Encountered invalid prevhash

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Computer app
 - Browser: no browser, desktop app
 - OS: Win 10
 - Bridge: version
 - Firmware Version: Trezor One, 1.10.4

**How to reproduce**
1. Go to DOGe coin
2. Click on Send, then Review & Send
3. Confirm on device

**Expected behavior**
No transaction only an error message: Transaction signing error: Encountered invalid prevhash

**Screenshots**
![image](https://user-images.githubusercontent.com/69053769/149554125-911bf292-612f-4845-bb4b-6fd37d63f3a1.png)

**Comment by prusnak** [comment] 2022-01-14 17:56
Which version of the Suite is this?

**Comment by ThanaNL** [comment] 2022-01-14 20:47
Tha most recent one. It says no update is available.
21.12.2

**Comment by hynek-jina** [comment] 2022-01-17 07:48
Duplicate of: https://github.com/trezor/trezor-suite/issues/4698

**Closed as completed by hynek-jina** 2022-01-17 07:48 UTC
Labels: bug
