### ISSUE TITLE
Receive: Brushup

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2365] opened 2020-09-16 15:48 UTC
- [x] Add header (spacing as is in the Send form) 

<img width="293" alt="Screen Shot 2020-09-16 at 17 44 29" src="https://user-images.githubusercontent.com/29627086/93360784-5f62da80-f844-11ea-8ed8-47bcb94606f7.png">

- [x] Add tooltip to the header (explanation for BTC-like coins of how to deal with addresses) 

- [x] Same input component (size and spacing) as is in the Send form

**Comment by bosomt** [comment] 2020-09-30 09:52
Please check that green space between tab name and tab content is inconsistent.
First and third  tab are same but Receive tab has much smaller space.
@matejzak if it's Ok then please close and move to approved.

**OK**
![image](https://user-images.githubusercontent.com/31506317/94670483-e6b75000-0312-11eb-9fa9-c3eaeb85ca70.png)


**NOK**
![image](https://user-images.githubusercontent.com/31506317/94670505-ee76f480-0312-11eb-9440-61b95290ce74.png)


**OK**
![image](https://user-images.githubusercontent.com/31506317/94670525-f6cf2f80-0312-11eb-8e18-d9de57b15604.png)

Nixos + Chromium 85
Suite dev web maser commit fc5e15a
Device TT fw 2.3.3 commit 0d5f00668

**Comment by sorooris** [comment] 2020-09-30 10:26
The _AppNavigationPanel__Content-gm56o1-1 blYclB_ panel in the Accounts section is indented 25px more to the right when the Receive tab is selected than the other two (first and third), regardless of the window size.
Overview | Receive
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/94673661-5a5b5c00-0317-11eb-91ab-d7b57eb0db50.png) | ![image](https://user-images.githubusercontent.com/10185314/94673806-90004500-0317-11eb-94c6-275865ff8745.png)

> Suite version: web develop fc5e15a
> Browser: Chromium 85.0.4183.102
> OS: Nixos
> Device: model T 2.3.3 0d5f00668

**Comment by slowbackspace** [comment] 2020-09-30 13:05
isn't it because of scrollbars not being visible in receive?

**Comment by sorooris** [comment] 2020-09-30 13:06
@slowbackspace who are you reacting to? :D

**Comment by slowbackspace** [comment] 2020-09-30 13:07
@sorooris oh sorry, I didn't notice there are more comments beside yours 😁 I think it will be the scrollbar!

**Comment by sorooris** [comment] 2020-09-30 16:01
@slowbackspace i wanted to check it again with focus on the scrollbar but couldn't replicate it - is it already fixed?

**Comment by slowbackspace** [comment] 2020-10-03 19:00
@sorooris Nothing changed afaik. My theory is that the receive tab doesn't have that much content so it fits on the screen without the overflow so browser won't render a scrollbar. When you go to Activity (where list of txs is) browser will show a scrollbar and thus making usable viewport area smaller and pushing it 15px to the left aand since the content in the app is centered it will visually move to the left, by 15px. 🕵️‍♂️

Shame we didn't catch that earlier, maybe custom scrollbars would at least help with the issue. (btw macs without connected mouse aren't affected as macos scrollbars won't take any space)

**Comment by sorooris** [comment] 2020-10-05 14:37
@slowbackspace indeed, you were right with the vertical scrollbar not being present:
- verified with an account with **no used receive addresses** (new passphrase)

> Suite version: web develop a6bf817
> Browser: Chromium 85.0.4183.102
> OS: Nixos
> Device: model T 2.3.3 0d5f00668

Overview | Receive
------------ | -------------
![image](https://user-images.githubusercontent.com/10185314/95093228-d515e400-0728-11eb-93ee-5c42be420bf2.png) |  ![image](https://user-images.githubusercontent.com/10185314/95093294-e828b400-0728-11eb-9c32-c4c3ca49288f.png)

**Comment by slowbackspace** [comment] 2020-10-06 12:59
waaait a second. there is is a scrollbar in each of these tab. but there is ONE MORE scrollbar in overview. That's stupid and definitely a bug.

I was always talking about difference between one scrollbar and none. Not this 💩 😬

**Comment by slowbackspace** [comment] 2020-10-06 13:00
But the bug is reproducible in overview, not in receive (issue was for receive tab 😛 ). CLOSING THE ISSUE (jk)

**Comment by sorooris** [comment] 2020-10-06 13:06
I thought we just really liked scrollbars. 🤷🏻‍♂️

**Comment by slowbackspace** [comment] 2020-10-06 13:32
To summarise things:
The double scrollbar thing is bug and will be fixed. 

The jumpiness while switching between long overview tab and short receive tab is basically normal browser behaviour (albeit stupid one) as explained in https://github.com/trezor/trezor-suite/issues/2365#issuecomment-703150088. There is a change some magical javascript scrollbars will solve this issue (Issue for scrollbars https://github.com/trezor/trezor-suite/issues/2226), but right now I wouldn't consider it as a bug. As the behaviour wasn't introduced by implementing receive page anyway I am praying for quick close of this issue 🙏

**Closed as completed** 2020-10-15 12:34 UTC
Labels: bug, receive

**Comment by bosomt** [comment] 2020-10-23 08:19
**QA OK**

In my opinion it looks strange that every tab starts after different  green "space" see : https://www.youtube.com/watch?v=4LkEVzUQi70&feature=youtu.be

QA OK

Nixos + Firefox 81 + Chrome 85
Suite dev web 4d4a9f3
Device model T fw 2.3.4 commit 50854b921
