### ISSUE TITLE
Device not remembered/connected, wallet loaded

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3577] opened 2021-03-28 13:27 UTC
Device not connected, not remembered ›  Yet, wallet data loaded 

This happened to me twice in a short time span on 2 different devices, and 2 totally different situations, so I am just raising it to make sure there isn't some bigger problem behind it. 

(1) After FW update (from 2.3.4 to 2.3.5.) › Resulted in device disconnected › Reconnecting didn't do anything (screenshot below)
(2) Simply after reopening the web app › Device was locked › Suite showed it as disconnected, wallet data loaded

  - Both were Suite version: web 21.4.0 (a8710a4ff8f5b667fa9d439621b046b05ed04f6c), Chrome
 
<img width="1781" alt="Screen Shot 2021-03-28 at 15 17 30" src="https://user-images.githubusercontent.com/29627086/112753735-2c5e8800-8fd9-11eb-8351-34469f75b915.png">

**Comment by jerechinsky** [comment] 2021-04-06 07:25
@trezor/qa could you please try to reproduce this?

**Comment by bosomt** [comment] 2021-04-06 07:40
I was not able to reproduce issue via 2.3.4 > 2.3.5 upgrade
But I will watch out for this issue during regular testing.


**Info:**
 - Suite version: web 21.4.0 (13e39799cd9a620f1f3235238fc353f5312fa479)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.5 regular

**Comment by slowbackspace** [comment] 2021-04-06 08:36
I also wasn't able to reproduce this, but it is possible there is a glitch hidden somewhere because during the fw update we are really storing the device till the update it completed, but then it should get removed from the database and, so far, it does in my testing. I would keep the issue open for now and I'll keep an eye on this while rewriting the onboarding (thus also fw update flow).

**Comment by slowbackspace** [comment] 2021-04-06 08:40
> I also wasn't able to reproduce this, but it is possible there is a glitch hidden somewhere because during the fw update we are really storing the device till the update it completed, but then it should get removed from the database and, so far, it does in my testing. I would keep the issue open for now and I'll keep an eye on this while rewriting the onboarding (thus also fw update flow).

Heh, but due to how this works I realized there is another "glitch" that you can trigger, just disconnect the device after fw installation is completed, but BEFORE  before closing fw update modal. Device stays remembered, but reconnecting the device shows the correct status (connected) so no biggie 😁. Maybe @matejzak's issue is combination of this and some real bug we have yet to find.

**Comment by slowbackspace** [comment] 2021-05-06 07:42
I've never experienced this, let's reopen if QA will be able to reproduce 🙇

**Closed as completed by slowbackspace** 2021-05-06 07:42 UTC
Labels: bug
