### ISSUE TITLE
Increase the bottom spacing

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2379] opened 2020-09-18 18:35 UTC
Increase the bottom spacing in all Settings tabs. 

<img width="955" alt="Screen Shot 2020-09-18 at 20 35 24" src="https://user-images.githubusercontent.com/29627086/93632952-7cd3a800-f9ee-11ea-94ac-44d897b3f408.png">

**Comment by slowbackspace** [comment] 2020-09-25 12:11
duplicate of https://github.com/trezor/trezor-suite/issues/2355

**Closed as completed by slowbackspace** 2020-09-25 12:11 UTC
Labels: settings
