### ISSUE TITLE
CoinJoin stuck on CriticalCoinjoinPhase modal

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#6846] opened 2022-11-08 15:33 UTC
**Describe the bug**
When I was trying to do a CoinJoin, the process got stuck on the critical coinjoin phase modal with "Establishing connection" and 0 seconds left. I can't quit the modal or do anything, other then restart or quit the Suite. I should be able to cancel this or quit the modal using the "X".

**Steps to reproduce:**
Unfortunately, no exact steps to reproduce. Just one round of CoinJoin randomly stuck.

**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
I should be able to cancel CoinJoin or at least quit the modal.

**Actual result:**
I can't cancel CoinJoin or quit the modal.

**Screenshots:**
![image](https://user-images.githubusercontent.com/48477147/200607509-d2a3cad8-31c7-4031-a948-4c285b691410.png)

**Comment by bosomt** [comment] 2022-11-08 16:35
I was able to reproduce issue :)


**Info:**
 - Suite version: desktop 22.11.1 (73ccf723353e0575a64f58b2f5775d20f072311f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by hynek-jina** [comment] 2022-11-15 13:29
How long were you stuck at this?
@bosomt @STew790 

Isn't this potentially solution? https://github.com/trezor/trezor-suite/issues/6909

**Comment by dahaca** [comment] 2022-11-15 13:47
FYI:

1) We don't want to allow users to hide this modal for now, since we want to be sure they don't do anything we don't expect
2) The timers are only estimates and are not 100% precise, hence them being stuck at 0 seconds.

**Comment by hynek-jina** [comment] 2022-11-15 13:51
I think we can close this one for now.. Any objections? 😄

**Comment by STew790** [comment] 2022-11-15 14:18
I haven't been able to reproduce this, so I think we can.

To answer your questions @hynek-jina , I think it is a different "stage" with #6909 and I don't really know for how long I have been stuck there, but at least for half an hour iirc.

**Comment by dahaca** [comment] 2022-11-15 14:30
@STew790 if it was half an hour it's serious. Let's wait and see if it occurs more and not close the issue for now @hynek-jina. Leave it in the backlog.

**Closed as not planned** 2022-11-16 10:42 UTC
Labels: bug, coinjoin
