### ISSUE TITLE
Suite becomes unusable after doing a firmware reinstall

### ISSUE THREAD

**Issue by ondracja** [trezor/trezor-suite#9608] opened 2023-10-07 19:52 UTC
**Describe the bug**
When the user updates their TT firmware via Suite on firmware `≥2.6.0`, Suite becomes unusable by not fully recognizing the device.

Behaviour is not reproducible on current prod version

**Prerequisites:**
- no wallets remembered
- Trezor T with `≥2.6.0` firmware installed

**Steps to reproduce:**
1. Connect Trezor to the PC and launch Suite `23.10.1`
2. Navigate to `Settings/Device`
3. Click on `Up to date` or `Update firmware` button in the `Firmware` section
4. Follow instructions on the device until the update is successfully done
5. Observe that Trezor seems to be normally connected
6. Also observe that suite is no almost completely unsuable (apart from changing non-device releated settings) and that the button `+ Add wallet` behaves as if no trezor was connected

**Info:**
 - Suite version: desktop 23.10.1 (0b3ccfe0b8e9bc2af00609d640bc1be31ab8edaa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1728x1117
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Suite recognizes the device fully and prompts the user to add a wallet as normal.

**Actual result:**
Suite becomes "stuck" as if waiting for the `wallet switcher` modal

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/9817938/7b39402f-8e13-494e-9c88-78825938d1ad)
![image](https://github.com/trezor/trezor-suite/assets/9817938/f22915d5-9407-4748-95e0-4afded31f67d)
![image](https://github.com/trezor/trezor-suite/assets/9817938/afc2452c-d3b2-4719-a3c8-be9fd0511dd8)

**App log:**
[trezor-suite-log.txt](https://github.com/trezor/trezor-suite/files/12838772/trezor-suite-log.txt)

**Comment by mroz22** [comment] 2023-10-08 17:36
possibly related https://github.com/trezor/trezor-suite/pull/9584

**Comment by mroz22** [comment] 2023-10-09 11:24
unable to reproduce on c84270e1380aae02460266029f7fc356c5dc8cf1 (origin/develop)

**Comment by mroz22** [comment] 2023-10-10 07:03
probably fixed by https://github.com/trezor/trezor-suite/pull/9613

**Closed as completed by mroz22** 2023-10-10 07:03 UTC

**Comment by STew790** [comment] 2023-10-10 12:53
**QA OK**
FW update of all devices went OK.

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.2 bitcoin-only (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33
