### ISSUE TITLE
Trezor Suite not connecting from within Tails OS through TOR to Trezor Servers

### ISSUE THREAD

**Issue by NotwhatIwanttotell** [trezor/trezor-suite#5819] opened 2022-07-20 13:29 UTC
Trezor Suite does not connect to Trezor servers trough Tails OS

-   Remembered Wallet: yes
-   Suite Version: 22.7.2 Linux Appimage
-   Browser: Tails OS 
-   OS: Tails OS 5.2
-   Bridge:
sudo iptables -I OUTPUT -p tcp --dport 21325 -j ACCEPT -s localhost -d localhost
sudo iptables -I INPUT -p tcp --dport 21325 -j ACCEPT -s localhost -d localhost
-   Firmware Version: 2.5.1

Trezor Suite used to work very well from within Tails OS after running the "iptables" in a terminal and enabling traffic through the Tor network. Lately the suite does not connect to Trezor servers and its impossible to see the crypto addresses in the wallet.

![image](https://user-images.githubusercontent.com/83304971/179992364-65aba816-37e2-4d71-ad86-4020826e5b96.png)
![image](https://user-images.githubusercontent.com/83304971/179990873-bea78e70-2372-4df1-b973-f00dd1fa170a.png)
![image](https://user-images.githubusercontent.com/83304971/179991050-da7a3201-04b2-49fa-96c2-491c0a87a2b4.png)
![image](https://user-images.githubusercontent.com/83304971/179991191-ce5a1448-af54-4135-afd2-b35333816cd4.png)
![image](https://user-images.githubusercontent.com/83304971/179991643-5816347d-5338-4d0a-9ad7-5f49a6298a84.png)

The Suite tries to connect to Trezor servers but after approximately 30 seconds it fails. As you can see the Trezor T is connected (left upper corner of first screenshot), unfortunately the addresses are not visible.

Suggestion:
Make Trezor Suit loadable through Synaptic Package Manager. Make Trezor Suit work through Tails OS/Tor in the same way as Electrum and Featherwallet. If Electrum.appimage works from within Tails OS Trezor should be able as well.

**Comment by NotwhatIwanttotell** [comment] 2022-07-26 17:22
As both Trezor Suit and Tails OS has been updated recently I decided to run a test. Unfortunatelly the issue is still present. Trezor Suit can not connect to Trezor servers from within Tails OS.

Suite Version: 22.7.3 Linux Appimage
Browser: TOR Browser 11.5.1
OS: Tails OS 5.3

Tried bridge:
sudo iptables -I OUTPUT -p tcp --dport 21325 -j ACCEPT -s localhost -d localhost
sudo iptables -I INPUT -p tcp --dport 21325 -j ACCEPT -s localhost -d localhost
and
sudo iptables -I OUTPUT 3 -o lo -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp --dport 21325 --syn -m owner --uid-owner amnesia -m conntrack --ctstate NEW -j ACCEPT

Both should make Trezor Suit connect but unfortunatelly thats not the case any longer.

**Comment by Hercules1122** [comment] 2022-10-18 11:22
Hope that gets resolved as well. 
https://github.com/trezor/trezor-suite/issues/6588

**Comment by prusnak** [comment] 2022-10-19 12:53
ISTM that Trezor Suite runs its own instance of Tor on (running on random port), but connecting to it is prevented by Ferm (Tails OS port firewall).

Is there a reason why we don't use the Tor daemon provided by the system (running on port 9050) if there is one already running? I vaguely remember we were doing that originally. @karliatto 

For the record, here is the Tails OS Ferm config: https://gitlab.tails.boum.org/tails/tails/-/blob/stable/config/chroot_local-includes/etc/ferm/ferm.conf (basically list of enabled ports).

**Comment by karliatto** [comment] 2022-10-20 06:43
> Is there a reason why we don't use the Tor daemon provided by the system (running on port 9050) if there is one already running? I vaguely remember we were doing that originally. @karliatto

@prusnak The reason we do not use the Tor daemon provided by the system is because we want to run it with ContolPort enable in order to be able to listen to the events that Tor emits so we can make it more stable for example when bootstraping, we make sure that we do not start any communication until Tor let us know that the circuits have been established and they are ready.

**Comment by prusnak** [comment] 2022-10-20 15:08
Thanks @karliatto for the answer. 

I think Tor in Tails OS has ControlPort enabled, so in case system-provided daemon listens on 9050 (proxy) and 9051 (control port), we could just use that, right?

**Comment by karliatto** [comment] 2022-10-21 07:35
> I think Tor in Tails OS has ControlPort enabled, so in case system-provided daemon listens on 9050 (proxy) and 9051 (control port), we could just use that, right?

It depends if the ControlPort run by Tail OS has [CookieAuthentication](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n3786) or it does not have any authentication at all.

If it has CookieAuthentication and the user running trezor-suite has access to it (most likely in Tor default data directory) then yes. 

We could check that Tor is running in 9050 (proxy) and that we can successfully connect to 9051 (ControlPort) using the default `control_auth_cookie` and use it.

It would be great if that works with the defaults for Tail OS.

**Comment by Hercules1122** [comment] 2022-10-23 15:51
Tried to get MyWallet working on Tails and Whonix to connect to Trezor Wallet. 
On Tails no Ethereum Network connection on MyCrypto. Therefore can't proceed further to detect Trezor Wallet. 
On Whonix there is connection to Ethereum Network on MyCrypto. 
But still Trezor Bridge doesnt work. Doesn't detect the Trezor. 
Same with Tor Browser on both OS and Windows also doesn't work. 

That's a huge assertion, but maybe Trezor Team disabled all other functionality options that everyone needs to connect over their Suite App? 

I just would like to have a possibility that Trezor is working on a Tor by default OS and/or connecting over Tor Browser.

Hope the Trezor Team is working on that! :)

Thanks!

**Comment by Hercules1122** [comment] 2022-11-01 22:15
Does anyone get the Trezor working on another OS than Windows?

On Tails doesn't work.

On Whonix I run on Terminal in the folder sudo dpkg -i trezor-bridge_2.0.27_amd64.deb and sudo dpkg -i trezor-udev_2_all.deb.
Than open Suite and says ' Trezor Bridge not running '.
I got a notification though that a new Version of Suite is available, but I dont get access to Tor when I want to connect at the switch.
The Download starts.
Tor Browser on Whonix also doesnt show up http://127.0.0.1:21325/ the Trezor device.
So the Device doesnt get recognized on Whonix as well... and I dont get connection to Tor on Suite on Whonix. 

On Whonix I can start the App 'MyCrypto' and I get connection to the Ethereum Network.
Which doesn't work on Tails actually.
Than I get asked ' How would you like to connect to your Wallet? '
There is Trezor listed. ' Connect to Trezor ' - no device connected.
As the device doesnt get recognized on Whonix.

On Kali Linux, I see the http://127.0.0.1:21325/status/ page, but says connected Devices: 0
Also on Suite App it says ' Connect your Trezor '.

I would like to have the Trezor running on a Tor by default OS or Tor Browser.

**Comment by Hercules1122** [comment] 2022-11-01 22:18
For sure on Tails the Trezor works for Electrum. 
But what about others coins? 

Just to have it running on Tor Browser would be the nicest option.

**Comment by hynek-jina** [comment] 2022-11-02 07:49
@Hercules1122 Please don't copy your comments to various issues.. it makes the job more complicated.

**Comment by abradshaw** [comment] 2024-01-01 16:47
I would really like this to be resolved in someway - even some manual workaround or editing settings files but really you like this to work in tails

**Comment by stevexyz** [comment] 2024-02-28 11:37
Still the same on the newly released Tails 6.
I think that at least some workaround until fix would be nice.
Tails and Trezor by design scream to work together.

**Comment by prusnak** [comment] 2024-02-28 14:44
> Tails and Trezor by design scream to work together.

Electrum works with Trezor out of the box in Tails.

**Comment by stevexyz** [comment] 2024-02-28 22:17
> > Tails and Trezor by design scream to work together.
> 
> Electrum works with Trezor out of the box in Tails.

Just tried, and unfortunately Tails 6 have incompatible versions of the two: Electrum says it wants a version of trezor 0.13 while installed there is a 0.12.4-2 !

**Comment by prusnak** [comment] 2024-03-02 17:02
> Just tried, and unfortunately Tails 6 have incompatible versions of the two: Electrum says it wants a version of trezor 0.13 while installed there is a 0.12.4-2 !

I wrote an email to Debian maintainers, they do not update packages very often sadly. In the meantime you can try updating the trezor package from PyPI. Maybe `sudo pip3 install trezor` will work?

**Comment by stevexyz** [comment] 2024-03-03 21:33
> I wrote an email to Debian maintainers, they do not update packages very often sadly. 

Did maintaners reply?

> In the meantime you can try updating the trezor package from PyPI. Maybe `sudo pip3 install trezor` will work?

Tails do not use PIP. I tried to install it but aborted halfway since was requiring virtual environments and other things and not sure this is the way to go (and all the time the would have to be reinstalled).

**Comment by stevexyz** [comment] 2024-04-07 17:39
Trezor Suite is still not working and Electrum/trezor packages versions are still mismatched...

There is someone that at least can suggest some workaround (e.g. how to properly install the trezor python library to be used by Electrum or some manual workaround to make Trezor suite working)? Surely will be appreciated!

**Comment by Shane-96** [comment] 2024-07-16 15:03
This open issue will be celebrating it's 2nd birthday this Sunday, I'll get the cake and candles ready! Jokes aside, can someone with experience in this project please provide a fix or a workaround for this issue? would be much appreciated!

**Comment by Shane-96** [comment] 2024-07-16 15:06
This open issue will be celebrating it's 2nd birthday this Sunday, I'll get the cake and candles ready! Jokes aside, can someone please provide a fix or a workaround for this issue? would be much appreciated!

**Comment by karliatto** [comment] 2024-07-16 15:11
@Shane-96 I am currently working on it. We are going to provide option to run Trezor Suite with external Tor daemon.

**Comment by Shane-96** [comment] 2024-07-16 17:02
@karliatto You're the man! Thank you ever so much for looking into this!

**Comment by F4bioo** [comment] 2024-11-21 00:06
> @Shane-96 I am currently working on it. We are going to provide option to run Trezor Suite with external Tor daemon.

Hi @karliatto , is there any update on this development? This would be really helpful for Tails users.

**Comment by karliatto** [comment] 2024-11-22 15:52
> Hi @karliatto , is there any update on this development? This would be really helpful for Tails users.

@F4bioo the experimental feature to allow Trezor Suite to use a external Tor daemon and keep all the Trezor Suite features is near completion. But after testing it in Tails I found out that Tails is really protecting Tor, so the Tor ControlPort is only allowed via control socket as you can see in their documentation  https://tails.net/contribute/design/

> access to the Tor control port is only granted to the root user, as well as to the members of the debian-tor group (via the control socket). A filtering proxy to the control port runs on port 9051 (i.e. the default Tor ControlPort), 

I think using `control socket` instead of `control port` as we use now under a flag for Tails users might be possible but it requires more development. Other solution would be to allow experimental feature where Trezor Suite could use external Tor without Control Port, but some feature would not be available and it would be less stable.

For now I would move forward the External Tor experimental feature since it is basically completed and I think it already adds value for people that wants to use for example Tor bridges that we have not implemented directly but unfortunately that is not going to be enough for Tails. 

But after that, I think we can explore the 2 other options:

1. Using external Tor without control port (probably quick solution but less stable and some features are not going to work)
2. Using external Tor  with control port via control socket (if it really works in Tails, it should allow all the features and stability that Trezor Suite Tor integration wants to achieve)

**Closed as completed** 2024-12-16 17:37 UTC
Labels: bug, Linux, tor

**Comment by karliatto** [comment] 2024-12-17 08:06
This issue has been close since a fix is coming out in next Trezor Suite release.
We have added new experimental feature that allows to use Tor external daemon running in port `9050` Tor default port.
Documentation on how to use it will be coming along this experimental feature in the Trezor Knowledge Base, but for Tails it is quite simple, just enable the experimental feature and it works.

**Comment by Shane-96** [comment] 2024-12-18 12:49
Hi @karliatto,

Thanks for your contributions and resolving this.

Sorry in advance for all the questions, I'm just curious and would like to have a better understanding of what was implemented here and hopefully it also answers someone else's question in the future.

**1) Can you confirm whether tor will still be bundled with Trezor Suite and natively supported? for example, no need to install tor browser as all the dependencies are already in the trezor-suite as it currently is?**

[feat(suite-desktop-core): support external Tor](https://github.com/trezor/trezor-suite/pull/15642/commits/9a9eef2a42aef75cdc6a2a59da34113848089dec) - create new TorExternalProcess to allow handle external Tor and update the Tor module so it can change from bundled Tor to External Tor.

I read this like TorExternalProcess is a flag that when enabled it will use external tor and when disabled it will use bundled tor, however; I would like confirmation on this as I can read it both ways, as in that it's been permanently changed from using bundled tor to external tor, which I hope is not the case for the use cases when a user want's to use trezor suite without installing tor.

[feat(suite-desktop-api): support external Tor](https://github.com/trezor/trezor-suite/pull/15642/commits/0670fffb9ad01784e7baca1e78c9b223dc481475) - new type in TorSettings useExternalTor
[feat(suite): external-tor experimental feature](https://github.com/trezor/trezor-suite/pull/15642/commits/0628e5179e6f35f373a3b1f16ccffb794244a858) - Add External Tor to experimental features in Suite.

These two variables make it sound like it is indeed just a flag, but confirmation on this would be nice.


**2) Regarding checkSocks5Proxy function, is this just checked once when feature is enabled? or is this checked periodically?**
The reason I ask is because it would be nice that if trezor suite doesn't detect the socks5proxy then it disables network connectivity and it would be nice if this could be done instantly which would prevent IP leaks. Think of a KillSwitch like most VPN providers have in their software.

**3) Regarding Snowflake, if I understand correctly, this is like a bridge? would it not be worth keeping the snowflake function in the code?**
As now maybe there's someone in a country that blocks TOR and they are a non-technical user and just want to connect to trezor suite, but now with the removal of snowflake, if I understand correctly; they would have to set the tor to external, which would also mean they would have to download tor themselves and configure that properly and as you said yourself "Like every great power it comes with great responsibility, so when running Tor External user could do something wrong that ruins their privacy so user has to know what he is doing when using this feature.", whereas If the snowflake function will provide the user with a bridge without all the manual configuration then I see value in that for the non-technical users.

**4) Regarding (watch -n 1 'lsof -i TCP | grep electron')**

I like how you included this so people can check their connection runs through TOR, but the fact you included the command in the PR doesn't leave me very confident that Trezor Suite will always run through TOR and the fact it's a watch command, make's me think you want us having a terminal open just for checking traffic is 100% going through tor. With this being said, and also my point earlier regarding kill switch, if you have not already; could you possibly add some fail-safe features to prevent IP leaks?

Thank you once again @karliatto for your contributions here, I look forward to hearing your response.

**Comment by karliatto** [comment] 2024-12-18 16:23
> 1) Can you confirm whether tor will still be bundled with Trezor Suite and natively supported? for example, no need to install tor browser as all the dependencies are already in the trezor-suite as it currently is?

Yes, I can confirm Tor will still be bundled with Trezor Suite, it does not change anything in the current way Tor works in Trezor Suite if user does not enable the new experimental feature.


> 2) Regarding checkSocks5Proxy function, is this just checked once when feature is enabled? or is this checked periodically?

It just checks when feature is enabled. But when using Tor External experimental feature it is the responsibility of the user that that port is running Tor. 

> 3) Regarding Snowflake, if I understand correctly, this is like a bridge? would it not be worth keeping the snowflake function in the code?

Yes, snowflake is like a bridge https://snowflake.torproject.org/  - We are thinking in different ways to make the usage of Tor bridges like snowflake easier and sustainable. Hopefully soon.

> 4) Regarding (watch -n 1 'lsof -i TCP | grep electron')

I think it is good to test that things are working as expected. But the comments in the Pull Request are more intended for testers and developers at Trezor, it is not intended for the users to test it.
Trezor Suite already has multiple levels of protection to ensure that there are no clear-net connection when Tor is enabled.

**Comment by Shane-96** [comment] 2024-12-19 11:17
> > 1) Can you confirm whether tor will still be bundled with Trezor Suite and natively supported? for example, no need to install tor browser as all the dependencies are already in the trezor-suite as it currently is?
> 
> 
> 
> Yes, I can confirm Tor will still be bundled with Trezor Suite, it does not change anything in the current way Tor works in Trezor Suite if user does not enable the new experimental feature.
> 
> 
> 
> 
> 
> > 2) Regarding checkSocks5Proxy function, is this just checked once when feature is enabled? or is this checked periodically?
> 
> 
> 
> It just checks when feature is enabled. But when using Tor External experimental feature it is the responsibility of the user that that port is running Tor. 
> 
> 
> 
> > 3) Regarding Snowflake, if I understand correctly, this is like a bridge? would it not be worth keeping the snowflake function in the code?
> 
> 
> 
> Yes, snowflake is like a bridge https://snowflake.torproject.org/  - We are thinking in different ways to make the usage of Tor bridges like snowflake easier and sustainable. Hopefully soon.
> 
> 
> 
> > 4) Regarding (watch -n 1 'lsof -i TCP | grep electron')
> 
> 
> 
> I think it is good to test that things are working as expected. But the comments in the Pull Request are more intended for testers and developers at Trezor, it is not intended for the users to test it.
> 
> Trezor Suite already has multiple levels of protection to ensure that there are no clear-net connection when Tor is enabled.
> 
> 

Thank you for the explanation and thanks for resolving this once again.

Kind Regards
