### ISSUE TITLE
Scroll to current/active output in ReviewTransaction modal

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3858] opened 2021-06-08 07:57 UTC
while confirming tx (btc-like) with multiple outputs (or rbf) the list in ReviewTransaction modal is quite long.

i happens that current output displayed on Trezor is not corresponding with the view in suite (the output you confirming is below the viewport and not currently visible in modal, you need to scroll to it manually)

**Comment by jerechinsky** [comment] 2021-10-08 13:37
Duplicate of #3414

**Closed as completed by jerechinsky** 2021-10-08 13:37 UTC
