### ISSUE TITLE
Hologram explanation tooltip is too large

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#8953] opened 2023-07-19 15:40 UTC
Which causes it to stick out of the app window.

<img width="1440" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/d298b7c9-b4b3-45af-b63b-5e6ed9229b49">

**Comment by Hannsek** [comment] 2023-07-19 17:46
Probably duplicate of this: https://github.com/trezor/trezor-suite/issues/6263

**Closed as not planned** 2023-07-20 11:38 UTC
Labels: bug, UI
