### ISSUE TITLE
Trezor Suite password protection 

### ISSUE THREAD

**Issue by pdmcrypto** [trezor/trezor-suite#3247] opened 2021-01-08 16:39 UTC
Forgive me if this has been discussed already.. but in upcoming updates to Trezor Suite, can we expect to see password protection for the desktop app itself. Coming from Ledger Live, you need to input a password just to open the app, but not for Trezor Suite. Therefore, if I set Suite to remember my device for “unplugged viewing”, then anyone can click the Suite logo on my desktop and view my portfolio balances. I think a basic password protection for the overall app would go a long way

**Comment by prusnak** [comment] 2021-01-08 17:09
Duplicate of https://github.com/trezor/trezor-suite/issues/3166

**Closed as completed by prusnak** 2021-01-08 17:09 UTC
