### ISSUE TITLE
Amount in Send form not reseted after you change token or from/to Sol

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#14389] opened 2024-09-17 14:15 UTC
**Describe the bug**
Amount in send form not reseted after you change token or from/to SOL

**Steps to reproduce:**
1. Navigate to send form of account that contain SOL and some tokens
2. Click on send max after selecting token or enter amount higher than SOL amount in account
3. Change to different token with lower amount or to SOL or to token with different decimals
4. Observe error

**Info:**
 - Suite version: web 24.10.0 (d34ecbd7f29f72f9765deeeeba21a08713624d46)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport

**Note(s):**
Probably same or similar issue to this: https://github.com/trezor/trezor-suite/issues/13494

**Comment by tomasklim** [comment] 2024-10-03 11:55
Also `Send max` should reset

**Comment by tomasklim** [comment] 2024-11-24 14:54
Closing, duplicate of #13494

**Closed as completed by tomasklim** 2024-11-24 14:54 UTC
Labels: bug
