### ISSUE TITLE
Not possible to generate second address

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#10343] opened 2023-12-14 20:28 UTC
1. Generate first ADA adress
2. Try generate another one => window gets closed before anything is showed on device.

Edit: replicated also with other coins. But it seems that it happens after first Cardano receive. See the video with replication:
https://drive.google.com/file/d/1L_WTS7SE8DfCp3wg62YjWfa61I7jFIaH/view?usp=drive_link

**Comment by juriczech** [comment] 2023-12-19 14:06
![Image](https://github.com/trezor/trezor-suite/assets/36101761/f595d34e-a28f-4eca-8924-fef17ee40c40)

Seems to be caused by this error message.

**Comment by juriczech** [comment] 2024-01-02 12:26
@mnuky Not able to reproduce on localhost with device emulator. Can you please retest that this wasn't "accidentally" fixed by something in connect?

**Closed as completed** 2024-01-09 15:51 UTC
Labels: mobile

**Comment by bosomt** [comment] 2024-01-10 10:01
**QA OK**

24.01.1 (673)
96d12a4 - [develop] - fix(suite): fix label drop for RBG transactions
Android 13 - Nothing phone 1
Trezor model Safe 3
