### ISSUE TITLE
Notifications - selecting the View details button does not focus on the item

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3613] opened 2021-04-08 10:18 UTC
**Describe the bug**
Selecting the View details button only redirects to the correct account but does not focus on the item from the notification (e.g. transaction received or sent).

**Info:**
 - Remembered Wallet: either (tested both)
 - Suite Version: app 21.4.1 
 - Browser: N/A, Chromium 89.0.4389.82
 - OS: macOS 11.2.3, Nixos 20.09
 - Bridge: 2.0.31 (rev 5f53132)
 - Firmware Version: model One 1.9.4 ffa96205

**Steps to reproduce:**
1. Send an arbitrary transaction,
2. Select the notification icon, 
4. Select the View details button of the transaction,
3. Observe.

**Expected result:**
Focus is on the transaction that was displayed in the notification.

**Actual result:**
Focus is just on the Account Overview of the transaction that was displayed in the notification.

**Screenshots:**
![Peek 2021-04-08 11-37](https://user-images.githubusercontent.com/10185314/114010527-76aaf900-9864-11eb-8c17-349eeeed31db.gif)

**Comment by sorooris** [comment] 2021-04-08 10:39
Also, the notifications dropdown stays displayed after selecting the button (which is apparent from the screencap above).

**Comment by jerechinsky** [comment] 2021-04-09 09:17
Duplicate of #2208

**Closed as completed** 2021-04-13 12:46 UTC
Labels: feature, notifications, transactions
