### ISSUE TITLE
gpg Signing key Expired

### ISSUE THREAD

**Issue by daltek** [trezor/trezor-suite#3272] opened 2021-01-17 22:57 UTC
**Describe the bug**

The gpg signing key is expired 

**Info:**
 - Suite Version: n/a
 - Browser: , n/a
 - OS:  n/a 
 - Firmware Version: n/a

**Steps to reproduce:** 

    gpg --list-keys

     pub   rsa4096/0x26A3A56662F0E7E2 2020-10-20 [SC] [expired: 2021-01-01]
           Key fingerprint = 5406 7D8B BF00 5541 81B5  AB8F 26A3 A566 62F0 E7E2
     uid                   [ expired] SatoshiLabs 2020 Signing Key
     
     pub   rsa4096/0x91F3B339B9A02A3D 2012-03-07 [SC] [expired: 2021-01-14]
           Key fingerprint = 86E6 792F C27B FD47 8860  C110 91F3 B339 B9A0 2A3D
     uid                   [ expired] Pavol Rusnák <pavol@rusnak.io>
     uid                   [ expired] Pavol Rusnák <stick@gk2.sk>
     uid                   [ expired] Pavol Rusnák <stick@satoshilabs.com>
     uid                   [ expired] Pavol Rusnák <prusnak@opensuse.org>
     uid                   [ expired] [jpeg image of size 2449]

**Expected result:**

gpg keys that are currently valid

**Actual result:**

gpg keys that are expired

**Screenshots:**

see pasted output in *Steps to reproduce*insert here

**Note(s):**

Thanks.

**Comment by prusnak** [comment] 2021-01-17 23:06
This is expected. See https://github.com/trezor/trezor-suite/issues/3249 for more info

Duplicate of https://github.com/trezor/trezor-suite/issues/3249

**Closed as completed by prusnak** 2021-01-17 23:06 UTC
Labels: bug
