### ISSUE TITLE
Review: Start discovery when add new coin

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#10579] opened 2024-01-09 14:37 UTC
(high priority)
<img width="730" alt="Screenshot 2024-01-09 at 15 05 47" src="https://github.com/trezor/trezor-suite/assets/858321/3993342b-e202-4793-8057-dff8020a45c9">

**Comment by dahaca** [comment] 2024-01-09 20:48
Duplicate of https://github.com/trezor/trezor-suite/issues/10021

**Closed as completed by dahaca** 2024-01-09 20:48 UTC
Labels: code
