### ISSUE TITLE
Receive XRP - no fresh addresses list

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#1536] opened 2020-04-14 13:48 UTC
![image](https://user-images.githubusercontent.com/3112191/79232033-473af980-7e67-11ea-860f-fa2dc712a30f.png)

**Comment by slowbackspace** [comment] 2020-04-15 08:32
duplicate of https://github.com/trezor/trezor-suite/issues/1520

**Closed as completed by slowbackspace** 2020-04-15 08:32 UTC
Labels: bug
