### ISSUE TITLE
Trezor Suite hangs up  when Tor is enabled and you want to quit Trezor Suite

### ISSUE THREAD

**Issue by jschbe** [trezor/trezor-suite#12626] opened 2024-05-28 15:57 UTC
**Describe the bug**
Trezor Suite hangs up when Tor is enabled and you want to quit Trezor Suite. Output on terminal is:
`accountUnsubscribe error: Tried to call a JSON-RPC method "accountUnsubscribe" but the socket was not "CONNECTING" or "OPEN" ("readyState" was 3)`

**Info:**
-   Remembered Wallet: yes
-   Suite Version: 24.5.2 (Trezor-Suite-24.5.2-linux-x86_64.AppImage)
-   OS: Arch Linux (`Linux 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux`)
-   Bridge: n/a
-   Firmware Version: Trezor Safe 3, Firmware version 2.7.0

**How to reproduce**
1. Start Trezor Suite
2. Make sure that Tor is enabled, you do not need to connect a hardware wallet to reproduce the issue
3. Press the "X" Button (upper right corner) to quit Trezor Suite

**Expected behavior**
I expect Trezor to simply quit and not hang up.

**Comment by MiroslavProchazka** [comment] 2024-06-03 11:03
Hello @jschbe 
can you confirm that you had SOL account active on the moment of closing the SUite please?

**Comment by komret** [comment] 2024-07-10 16:04
Closing as duplicate of https://github.com/trezor/trezor-suite/issues/12628.

**Closed as completed by komret** 2024-07-10 16:04 UTC
Labels: bug
