### ISSUE TITLE
Incorrect timestamp in transaction list

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2211] opened 2020-08-13 08:54 UTC
**Info:**
 - OS: Nixos
 - Browser: , xxx
 - Wallet Version: app, commit 74b74b0c70658ff4cad66541441aa7274f949308
 - Firmware Version: model 1.9.2  , revision 0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea
 
**Describe the bug**
Incorrect timestamp in transaction list, looks like in transaction list we ignore timezone

**Steps to reproduce:**
1. start linux app and send transaction
2. compare transaction list and activity list
3. compare with web version of same suite version

**Expected result:**
both timestamps are same

**Actual result:**
They use same timestamp like blockbook: mined Thu, 13 Aug 2020 08:40:26 UTC

**Screenshots:**

Web vs App, same accounts

![image](https://user-images.githubusercontent.com/31506317/90114254-c1668680-dd52-11ea-9dc9-b1e44010283c.png)

Activities  log that shows correct timestamp
![image](https://user-images.githubusercontent.com/31506317/90114263-c4fa0d80-dd52-11ea-8800-334773ddd604.png)

**Comment by bosomt** [comment] 2020-08-13 09:52
time zone is auto and time is OK too :) 

![image](https://user-images.githubusercontent.com/31506317/90120802-77ce6980-dd5b-11ea-8b0a-12337f40607c.png)

**Comment by slowbackspace** [comment] 2020-08-14 08:49
can't reproduce, could you please retest with other OS (eg debian based linux distro and win) 🙏 

The date in activities is the date the notification appeared, it is not related to the tx in any way.

**Comment by glacierbits** [comment] 2020-10-08 06:52
@bosomt I am closing the issue to move it to the `merged` column for testing. If you won't be able to reproduce it, feel free to move it to `approved.` Thanks!

**Comment by wendys-cats** [comment] 2020-10-08 18:02
**QA NOK**
**Issue persists**
Nixos OS + Chromium 85 (and Windows10 Home Edition + APP commit bcf7ad8a43857cd90086a558a49c23a0df65216c)
Nixos OS + APP commit bcf7ad8a43857cd90086a558a49c23a0df65216c

**Expected**
Timestamps will be correct on transaction lists

**Actual**
Timestamps are not the same, APP for Nixos ignores time zones, while web version and app for Windows check timezones and adjust the timestamps correctly. 

**Nixos OS + APP commit bcf7ad8a43857cd90086a558a49c23a0df65216c**
![image](https://user-images.githubusercontent.com/58593111/95494035-90df4980-099d-11eb-890b-0829b9e8f2a1.png)

**Nixos OS + Chromium 85 bcf7ad8a43857cd90086a558a49c23a0df65216c**
![image](https://user-images.githubusercontent.com/58593111/95495931-62af3900-09a0-11eb-9e5f-3bade4949199.png)

**Comment by pdreyfuss** [comment] 2021-04-27 13:11
I also just now ran into this issue and that is why I am here. It did not ignore time zone, but did not recognize daylight time. I am in the eastern time zone of the US. Here's my question for trezor - can't you simply use UTC and make everyone's life simpler and easier? Remember the KISS Principle?

**Comment by tsusanka** [comment] 2022-03-09 20:24
@wendys-cats could you please retest on non-NixOS Linux, e.g. Linux Mint or Ubuntu?

**Comment by pdreyfuss** [comment] 2022-03-09 20:28
It's been a long time since my original email. Could you forward that info back to me to refresh my memory?_____________________________
Peter
**********************
"My name also is Ransom,” said the Voice.--from Perelandra by C.S. Lewis
********************** 

    On Wednesday, March 9, 2022, 03:24:57 PM EST, Tomas Susanka ***@***.***> wrote:  
 
 


@wendys-cats could you please retest on non-NixOS Linux, e.g. Linux Mint or Ubuntu?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wendys-cats** [comment] 2022-03-14 12:53
Checked on Ubuntu (20.04) with 22.3.1 EAP version (6b7e7fa). App reacts correctly to timezone and after reloading is adjusts timestamps of transactions accordingly.

**Comment by pdreyfuss** [comment] 2022-03-14 14:28
Sorry, but I have no idea what you are talking about. I know that I have had problems with timestamps but don't remember these details. Can you please restate my original problem?_____________________________
Peter
**********************
"My name also is Ransom,” said the Voice.--from Perelandra by C.S. Lewis
********************** 

    On Monday, March 14, 2022, 08:53:48 AM EDT, Simona ***@***.***> wrote:  
 
 


Checked on Ubuntu (20.04) with 22.3.1 EAP version (6b7e7fa). App reacts correctly to timezone and after reloading is adjusts timestamps of transactions accordingly.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Closed as completed** 2022-03-14 15:28 UTC
Labels: bug
