### ISSUE TITLE
How to wipe/reset T1 PIN with Suite?

### ISSUE THREAD

**Issue by uj** [trezor/trezor-suite#4644] opened 2021-12-13 23:59 UTC
With web wallet, you can wipe T1 because you can [X] the pin pad on screen.

With Suite, you cannot wipe T1 (with forgotten PIN), as there is no [X] on the pin pad to get past that point.

A recent email says that web wallet is going away.

Will Suite be fixed before that time?  Many people have mentioned not being able to wipe, and the answer has always been to use the old web wallet instead, which works.

What about after January?

**Comment by bosomt** [comment] 2021-12-14 07:12
@uj yes it will be possible to wipe it.
Work in progress here: https://github.com/trezor/trezor-suite/issues/2542

**Comment by hynek-jina** [comment] 2021-12-14 07:56
Duplicate of https://github.com/trezor/trezor-suite/issues/2542

**Closed as completed by hynek-jina** 2021-12-14 07:56 UTC
Labels: bug
