### ISSUE TITLE
Landing page for new devices

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3968] opened 2021-07-01 08:54 UTC
Let's create a new landing page for new devices: **suite.trezor.io/start** (also redirected from trezor.io/start).

The design will be identical to: **suite.trezor.io** however the copy will be changed (via Crowdin).

**Comment by goodhoko** [comment] 2021-07-02 12:38
Done in #3978

I'll push the translation keys to crowdin soon.

**Comment by goodhoko** [comment] 2021-07-02 13:27
## Next steps
@matejzak The translations keys are now in Crowdin. You can find all of them in the green-highlighted area [here](https://github.com/trezor/trezor-suite/pull/3978/files#diff-988baecac61429698981f7b86b979d1627f33f484918f65402c4b345b5c57cba). Please edit the copy as you wish and then assign this back to me.

## Before launch
- We'll need to do the Crowdin sync once again before release. @alex-jerechinsky 
- We'll also need to deploy the `suite.trezor.io` website. @tsusanka 

## Acceptance criteria
@trezor/qa This one is simple: just check that there's a page at `suite.trezor.io/start` and it looks identical (modulo copy) to `suite.trezor.io`. The copy is still in making. I'll ping you here once this is completely ready for QA.

**Comment by tsusanka** [comment] 2021-07-02 13:47
> We'll also need to deploy the suite.trezor.io website. @tsusanka

The landing page is part of the deployment process as well so there is nothing to do extra luckily.

**Comment by bosomt** [comment] 2021-07-06 11:50
@tsusanka https://suite.corp.sldev.cz/suite-web/develop/start/ right ?

**Comment by sorooris** [comment] 2021-07-06 11:52
@bosomt let's please retest as soon as the copy is ready, as Jen mentions above; i.e when the issue is closed.
>The copy is still in making. I'll ping you here once this is completely ready for QA.

**Comment by glacierbits** [comment] 2021-07-07 07:39
Copy edited ✅ Thanks!

**Comment by bosomt** [comment] 2021-07-07 07:54
Please keep us updated, they are still not identical, start version is using old version that not include spend info from invity

<img width="1422" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/124721331-4fb69e80-df09-11eb-8a13-5097d82a9955.png">

**Comment by goodhoko** [comment] 2021-07-08 08:13
This is done.

@trezor/qa Sorry for the delays. The page should be now ready for your review. (Thanks for reporting the discrepancy @bosomt) The only difference from the index page should be the main heading and its subheading.

**Comment by tsusanka** [comment] 2021-07-08 10:06
(It will be on staging tomorrow)

**Comment by bosomt** [comment] 2021-07-09 10:30
**QA OK**

Only difference I see is welcome text, but this is expected as i expect ;)

<img width="1669" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/125064744-436d4580-e0b1-11eb-88c7-8d3879287cbe.png">

**Comment by sorooris** [comment] 2021-07-09 11:06
Should we congratulate anyone who visits the landing page on getting a Trezor? What about people who didn't buy one or people who aren't visiting the first time?

> <img alt="obrazek" width="1669" src="https://user-images.githubusercontent.com/31506317/125064744-436d4580-e0b1-11eb-88c7-8d3879287cbe.png">

**Comment by goodhoko** [comment] 2021-07-09 11:25
@sorooris The page that congratulates is *only* the `/start` which is the page a user navigates to after booting up their trezor for the first time. AFAIK we don't plan to link to this page from anywhere else. The current landing page `/` should remain intact.

**Comment by sorooris** [comment] 2021-07-09 11:44
@goodhoko Okay, didn't know that and it makes sense now, thanks!

**Comment by sorooris** [comment] 2021-07-12 15:52
**QA OK**

Suite: landing page, 21.7.1 ca85ae5c
Browser: Chromium 91.0.4472.77
OS: NixOS 21.05
Device: model T 2.4.0 ea3596ad8

**Comment by wendys-cats** [comment] 2021-07-13 12:02
**QA OK**

**Suite**: landing page, 21.7.1 3d90909aa68da250490f474b2d4cab02c0aad272
**Browser**: Chromium 88.0.4324.182 (Official Build) (64-bit)
**OS**: NixOS 21.03 
**Device**: T 2.4.0 regular public

**Comment by sorooris** [comment] 2021-07-13 13:34
What about the redirect from the **/start/** page to **/web/**? @vdovhanych reported and I verified that the redirect is to **/start/web/** which results in 404.

**Comment by tsusanka** [comment] 2021-07-13 13:39
We need to fix this for the release @alex-jerechinsky. @goodhoko any chance you could have a look?

**Comment by tsusanka** [comment] 2021-07-13 14:46
@matejkriz was so kind: https://github.com/trezor/trezor-suite/pull/4026.

**Comment by matejkriz** [comment] 2021-07-14 08:12
the Download buttons and Signature links are also wrong... fix coming soon
![image](https://user-images.githubusercontent.com/3729633/125587436-acaba3ab-8e46-4587-9d45-3073756f2e0e.png)

**Closed as completed** 2021-07-14 10:04 UTC
Labels: release

**Comment by STew790** [comment] 2021-07-14 11:49
**QA OK**

Links are working. They all link to /web/whatever and not to /start/web/whatever.

**Comment by sorooris** [comment] 2021-07-14 11:54
**QA OK**

Redirected from /start/ to /web/ correctly; Suite builds offered and downloaded correctly.

Suite: web 21.7.1 24cc565a
OS: NixOS 21.05
Device: N/A

**Comment by bosomt** [comment] 2021-07-14 11:59
**QA OK **

staging works as expected

 - Suite version: browser 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.1 regular
