### ISSUE TITLE
Bridge update offered even though Bridge is already installed

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#3182] opened 2020-12-15 11:08 UTC
**Describe the bug**
Bridge update prompt window appears i The Suite desktop even though the same Bridge version is already installed

**Info:**
 - Suite Version: 20.12.1, desktop
 - Browser: N/A - desktop
 - OS: macOS Mojave (version 10.14.6)
 - Bride: 2.0.27

**Steps to reproduce:**
1. Connects device to the Suite
2. Wait
3. Bridge update prompt window appears

**Expected result:**
As Bridge is installed no need to prompt the installation of the given version

**Actual result:**
Bridge update prompt window appears i The Suite desktop even though the same Bridge version is already installed

**Screenshots:**
![image](https://user-images.githubusercontent.com/37402530/102207184-fb48c480-3ecd-11eb-838b-568cd4cd8586.png)

**Comment by tsusanka** [comment] 2020-12-16 07:40
@yohaaan could you please verify the user has really 2.0.27 installed? Because this happens for older versions and I think that's what we are having here. If possible please ask them to go to http://127.0.0.1:21325/status/ with the Suite closed and report the version. I am really skeptical they have 2.0.27.

**Comment by yohaaan** [comment] 2020-12-16 09:36
@tsusanka this was confirmed upon your request prior to creating the issue, user confirmed that 2.0.27 is installed and recognized by the status page in both cases - when using Suite and also when Suite is closed.

**Comment by tsusanka** [comment] 2020-12-16 10:06
Hm, thanks, that's just weird. @sorooris will retest when he has Mac available.

**Comment by glacierbits** [comment] 2021-01-05 10:54
Can we close this @tsusanka ?

**Comment by keraf** [comment] 2021-01-05 11:25
I encountered this issue (or a similar one) at home using Pop!_OS. Can't remember how I got it to work at the end but I will check again tonight.

**Comment by tsusanka** [comment] 2021-01-06 10:15
Ping @trezor/qa please retest

**Comment by sorooris** [comment] 2021-01-06 11:54
Could not replicate issue, more instructions needed.
- tried reconnecting device with PIN and/or passphrase disabled, resetting Suite, force quitting Bridge - all to no avail

> Suite Version: app 20.12.1 be4e3a3
> OS: macOS Big Sur 11.1 (Mojave unavailable)
> Firmware Version: 2.3.4 public

**Comment by tsusanka** [comment] 2021-01-06 12:05
@sorooris @yohaaan could you please try to work this one out with each other and/or the customer? We should either be able to reproduce it or come to some conclusion.

**Comment by sorooris** [comment] 2021-01-06 12:50
@tsusanka @yohaaan told me that this issue was reported by one person only, i suggest we close this for now and reopen in case it is reported again or if @keraf remembers.

**Comment by keraf** [comment] 2021-01-06 12:55
Let's keep this issue open for now, I think I've encountered this again on my Ubuntu machine. I'll investigate and close the issue if there are no findings.

**Comment by yohaaan** [comment] 2021-01-26 09:02
@tsusanka @sorooris user claimed that after uninstalling of Bridge the issue was gone. Is the solo Bridge clashing with the built-in Suite Bridge? Is this expected behavior?

**Comment by keraf** [comment] 2021-01-26 10:22
> @tsusanka @sorooris user claimed that after uninstalling of Bridge the issue was gone. Is the solo Bridge clashing with the built-in Suite Bridge? Is this expected behavior?

Now that we have logging, we can have a better idea of what's happening :slightly_smiling_face: But I also noticed the Bridge to launch more reliably since I refactored the code (and maybe some previous refactoring introduced new issues). What version of Suite is the user running?

**Comment by keraf** [comment] 2021-04-06 14:21
Could we have another @trezor/qa sweep on this one? If it's reproducible, with some logs please :slightly_smiling_face: Otherwise, burn this issue :fire:

**Comment by bosomt** [comment] 2021-04-06 17:13
I was never able to reproduce this issue.
I think we can close this issue and of course reopen it it reappears and we will be able to reproduce it or we will have log file.

@yohaaan close ?

**Comment by sorooris** [comment] 2021-04-07 12:54
I came across an issue #3608 that could be somewhat related to this.

- what happens is that when Suite is running with a standalone Bridge instance and for whatever reason the trezord process is killed, the prompt to install Bridge is displayed (after ctrl+R at least) and Suite needs to be relaunched to make it run with the bundled Bridge instance.

Suite: 21.4.1 3ed454e
Bridge: 2.0.31 standalone, 2.0.31 bundled
OS: macOS Big Sur 11.2.3
Device: model One 1.9.4 ffa96205f

**Comment by tsusanka** [comment] 2021-04-09 15:00
I think it is fair to assume that this issue is actually #3608. So I am closing this one and let's move there, the description is more descriptive.

**Closed as completed by tsusanka** 2021-04-09 15:00 UTC
Labels: bug
