### ISSUE TITLE
Scrolling area on get help screen is to big

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#11595] opened 2024-03-15 08:23 UTC
**Describe the bug**
Get help screen is not that long but it has a really long scrolling area (see screenshot
**Info:**

-   Mobile Suite Version: 24.3.1
-   OS: iOS

**How to reproduce**

1. Go to setting screen
1. Click on get help

**Expected behavior**
Scroll area should be just under the last element as usually.

**Screenshots**
![IMG_2688](https://github.com/trezor/trezor-suite/assets/66002635/41ecb3d0-3272-4984-8858-65b91b2ba18c)

**Comment by mnuky** [comment] 2024-04-19 13:29
closing - duplicate of https://github.com/trezor/trezor-suite/issues/9275

**Closed as completed by mnuky** 2024-04-19 13:29 UTC
Labels: bug, low hanging fruit, mobile, UI
