### ISSUE TITLE
Model T freezes if host goes to sleep before simulated recovery process is completed

### ISSUE THREAD

**Issue by Tondoshi** [trezor/trezor-suite#4634] opened 2021-12-10 17:01 UTC
**Describe the bug**
Using a Trezor Model T and Trezor Suite 21.12.2, user completed onboarding and clicked Check backup to initiate simulated recovery. During recovery, the host computer (MacBookAir 10,1, Apple M1) briefly fell asleep. This caused Suite to show an error that the recovery had failed. The Trezor Model T allowed the user to continue the process until the 12th and final word, then froze for several minutes until it was unplugged. It worked correctly once reconnected.  

**Info:**
 - Remembered Wallet: no
 - Suite Version: desktop app, 21.12.2 - commit TBC
 - Browser: n/a
 - OS: macOS 11.5.2 (20G95)
 - Bridge: TBC
 - Firmware Version: Model T,  2.4.3 

**How to reproduce**
1. Perform simulated recovery using Check backup through Device Settings 
2. Enter several words using TT
3. Let host computer fall asleep
4. Trezor Suite displays error: recovery failed 
5. continue entering seed words until TT hangs. Trezor Suite does not respond during this time. 

**Expected behavior**
During Check backup the process should continue uninterrupted once computer is woken from sleep, allowing you to confirm all 12 words and states recovery is successful

**Comment by wendys-cats** [comment] 2021-12-15 09:34
I was able to reproduce this, upon entering last word of dry run TT soft freezes. Closing modal ("Recovery seed check failed") ends the soft freeze, but user is unable to re-do the dry run. **Looks like a discovery error** triggered when host computer went to sleep (network suspended). Once Dashboard has been opened and discovery is done, user is able to re-do the dry run successfully. 

Confirming it only happens during dry run and not during actual wallet restoration.

**Info:**
 - Suite version: desktop 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular

User is unable to re-do the dry run after soft freeze due to discovery error 
![image](https://user-images.githubusercontent.com/58593111/146098390-ca3ed86d-3660-433f-9a77-23ce98eba94f.png)

Looks like a discovery error
![image](https://user-images.githubusercontent.com/58593111/146098499-b0b2ca1e-0b03-420b-aad3-fd121a083cb1.png)

**Comment by STew790** [comment] 2022-07-28 15:00
**QA OK**
I was not able to reproduce it. Neither with killing the internet connection, nor with putting PC to sleep. I was able to finish the dry-run recovery.

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.27

**Closed as completed by STew790** 2022-07-28 15:00 UTC
Labels: bug
