### ISSUE TITLE
Missing type UnlockPath when using Angular 13

### ISSUE THREAD

**Issue by linhnguyen2809** [trezor/trezor-suite#6799] opened 2022-11-04 11:32 UTC
**Describe the bug**
Missing type UnlockPath when using Angular 13
<img width="799" alt="image" src="https://user-images.githubusercontent.com/96286224/199961547-ebf61b43-1e13-470a-856e-b13fee199ff6.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/96286224/199961813-a22930b6-56c9-448e-8aa8-5c6d1ffa226d.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/96286224/199961867-120f6e87-23d3-44aa-9319-3d75f48f39f4.png">

- In node_modules/@trezor/connect/lib/types/api/unlockPath.d.ts required PROTO.UnlockPath but in export * as PROTO from '@trezor/transport/lib/types/messages' file does not have any type of UnlockPath

**Info:**
-   Suite Version: web, "@trezor/connect-web": "^9.0.3"
-   Browser: chrome
-   OS: MacOs
-   Web framework: Angular v13

**How to reproduce**
1. Create Angular app via command: ng new project-name
2. Install @trezor/connect-web package via command: npm install @trezor/connect-web
3. Install @types/w3c-web-usb package via command: npm install --save @types/w3c-web-usb
4. Start Angular app via: ng serve

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/96286224/199962835-ceb2000b-3a14-4246-960a-c60f07856815.png">

**Comment by sime** [comment] 2022-11-04 13:31
@mroz22 The @trezor/transport package looks like it needs to be released?

@linhnguyen2809 Could you share a repo where this is reproducible? That will help in testing the issue.

**Comment by linhnguyen2809** [comment] 2022-11-04 13:58
https://github.com/linhnguyen2809/Trezor-angular, just created it, tks for your quick response

**Comment by sime** [comment] 2022-11-04 14:05
@linhnguyen2809 Brilliant, that repo helps a lot.

**Comment by sime** [comment] 2022-12-07 14:41
Note: waiting on next Connect release, ideally next week.

**Comment by linhnguyen2809** [comment] 2022-12-08 02:28
> Note: waiting on next Connect release, ideally next week.

Tks for your support

**Comment by Hannsek** [comment] 2023-03-10 09:56
Closing this as this should be already solved.

**Closed as completed by Hannsek** 2023-03-10 09:56 UTC
Labels: bug
