### ISSUE TITLE
When you send to yourself then transaction detail amount is only fee

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1856] opened 2020-05-21 07:28 UTC
When you send to yourself then transaction detail amount is only fee.
I don't know if this is feature or bug but i sent 1$ and not 3 cents, that's fee.

![image](https://user-images.githubusercontent.com/31506317/82534443-6e12dc80-9b45-11ea-8976-0aa56f748345.png)

**Comment by szymonlesisz** [comment] 2020-05-21 08:15
not a bug not a feature, it's a valid behaviour.
Since you send to yourself 1$ you also receive $1 so the only amount you have "lost" is transaction fee

**Comment by szymonlesisz** [comment] 2020-05-21 08:21
reopening on second thought
TOTAL OUTPUT in this case looks confusing

**Comment by glacierbits** [comment] 2020-10-27 12:45
@robertbrada Please make the `Fiat` amount in transaction detail the actual amount the user sent (not just the fee).

**Comment by robertbrada** [comment] 2020-12-08 11:56
I found out that if I send Ethereum tokens to myself, the transaction does not have  **sent  to myself** status. (see the screenshot, both of the transactions in the picture were sent to the same address)

I guess this is not a big deal, I just wanted to mention it's there.

(It probably has something to do with the fact, that if the user makes an Ethereum token transfer, he is not literally sending tokens to himself. Instead, he is calling a smart contract that handles token balances of different addresses.)

![image](https://user-images.githubusercontent.com/44506010/101479731-f5ddfe00-3952-11eb-96da-93967d0238b0.png)

**Comment by slowbackspace** [comment] 2021-02-16 16:01
@matejzak since may 2020 design change a bit, is this issue still relevant? We are no longer showing total input/total output fields.
In case of sent to self transaction, as @szymonlesisz mentioned, it makes sense that amount = fee. It is the same behaviour we are using in account overview and I believe also in transactions graph. If you really want to include the actual amount that user sent, then to keep things consistent this change needs to be considered across whole UI, thus being out of scope of this issue. Feel free to reopen if you feel different :)

**Closed as completed by slowbackspace** 2021-02-16 16:01 UTC
Labels: bug
