### ISSUE TITLE
Too many requests fired if app was running in the background

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3661] opened 2021-04-19 11:35 UTC
Whole discussion here https://github.com/trezor/trezor-suite/issues/3534#issuecomment-795360987

TL;DR:
If you let your computer sleep, or just keep suite running in the background without a focus then on focus it will start firing all http requests that were supposed to be fired while it didn't have a focus (fiat rates, auto updater, gdrive/dropbox for labeling...). 

I found out that electron/chrome applies `backgroundThrottling`.
```
Whether to throttle animations and timers when the page becomes background. This also affects the Page Visibility API. Defaults to true.
```
https://www.electronjs.org/docs/api/browser-window

imo could be worth to try disabling it and see if it prevents gobbling up the requests.

**Comment by tsusanka** [comment] 2021-04-19 11:59
@alex-jerechinsky we should solve this before the public launch so our backends do not die when lots of new people are coming in.

**Comment by slowbackspace** [comment] 2021-04-20 06:51
Huh, this is interesting, I can't reproduce this behaviour anymore (21.5.0 from few days old develop). @keraf Is it possible that it got fixed somehow?

Hm it could be, we've upgraded to electron 12. If you won't be able to reproduce this issue let's close this and pray that all is good now 😁

**Comment by jerechinsky** [comment] 2021-05-06 08:34
@tomasklim Maros couldn't reproduce it. Could you please try?

**Comment by tomasklim** [comment] 2021-05-27 09:15
Unable to replicate on macOS 11.4 with Suite version 21.5.1.

If app is in background, it fetches all request the time it wants to.
If I sleep my computer and wake it up after some time, it does not fire any request from the time it slept. It just continues as nothing happens.

**Comment by jerechinsky** [comment] 2021-05-27 09:17
Thank you @tomasklim. Since neither you or Maros could reproduce this, I will be closing this for now.

**Closed as completed by jerechinsky** 2021-05-27 09:17 UTC
Labels: bug
