### ISSUE TITLE
Missing connect Trezor animation

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#11202] opened 2024-02-15 10:50 UTC
**Describe the bug**
Nice animation for connecting Trezor is missing

**Info:**

-   Mobile Suite Version: 23.3.1/2434be24
-   OS: Android 13

**How to reproduce**

1. Tap 'Connect Trezor'

**Expected behavior**
Nice animation that is on production

**Screenshots**
![Screenshot_20240215-114418701 (1)](https://github.com/trezor/trezor-suite/assets/216917/e3a53b82-25f5-41ae-8799-58e7b6f1a83f)
![Screenshot_20240215-114756451](https://github.com/trezor/trezor-suite/assets/216917/9ca63a83-70af-4af4-8c3f-5bb2fad25c85)

**Additional context**
Commit hash is really long

**Comment by juriczech** [comment] 2024-02-16 13:40
Seems like this issue is caused by upgrading `lottie-react-native` from `6.5.1` to `6.6.0`. According to the documentation, they changed some requirements about width and height settings. It might be worth checking out the changelog before implementing fix for this. Since there is problem with xcode privacy settings on expo servers, I might drop the version to try and fix that issue. It might fix this one as well then but I'm not sure. cc @matejkriz @Nodonisko 

<img width="932" alt="image" src="https://github.com/trezor/trezor-suite/assets/36101761/f087cc99-f235-41a2-9349-0b1a9149ebc9">

**Comment by matejkriz** [comment] 2024-02-16 13:56
> Seems like this issue is caused by upgrading `lottie-react-native` from `6.5.1` to `6.6.0`. According to the documentation, they changed some requirements about width and height settings. It might be worth checking out the changelog before implementing fix for this. Since there is problem with xcode privacy settings on expo servers, I might drop the version to try and fix that issue. It might fix this one as well then but I'm not sure. cc @matejkriz @Nodonisko
> 

What problem on expo servers you mean?

We can try to downgrade temporarily, but I would prefer other fix. `borderWidth` is working. But we should try to set `width` as proposed in the changelog.

**Comment by matejkriz** [comment] 2024-02-16 13:58
`width: '100%'` works fine, I'll create PR. Let me know if there is some issue on expo server we need to address too.

**Comment by juriczech** [comment] 2024-02-16 14:11
@matejkriz Yeah, addressing the expo server issue separately, won't downgrade until necessary. Point of the comment was to provide more info about the bug since I've checked the changelog and saw this.

**Closed as completed** 2024-02-16 14:28 UTC
Labels: bug, low hanging fruit, mobile

**Comment by bosomt** [comment] 2024-02-22 13:26
**QA OK**

Android 14 - Nothing Phone 1
24.3.1 (24) dev version
