### ISSUE TITLE
Total including fee not hidden in descrete mode

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2617] opened 2020-10-14 06:02 UTC
Info:
- OS: NixOS
- Browser: desktop app
- Suite Version: https://staging-suite.trezor.io/ - release/2020-10 - e6ba320
- Firmware Version: 1.9.0

**Describe the bug**
Total including fee not hidden in Send dialog:

![image](https://user-images.githubusercontent.com/1835345/95949744-a1efe680-0df3-11eb-98f3-fe41c4b40c81.png)

**Comment by szymonlesisz** [comment] 2020-10-14 09:57
i'm not even sure if this feature should be enabled in send-form at all, what's the point of blurring "total" or "fee" and not blurring Amount inputs? @matejzak

**Comment by glacierbits** [comment] 2020-10-14 10:27
I do agree with @szymonlesisz . Let's disable it for Send altogether. I believe there is a "review" associated risk, since the user's ability to check they are sending the correct amount(s) would be limited.

**Comment by tsusanka** [comment] 2020-10-14 16:38
I have to say I disagree. If I use discreet mode I expect all amounts to be hidden. Imagine you are sending 10 BTC, I think it is as sensitive as the fact that you _have_ 10 BTC. 

> I believe there is a "review" associated risk, since the user's ability to check they are sending the correct amount(s) would be limited.

Don't forget the values are still to be confirmed on Trezor.

But it is a product thing so @matejzak should have the last word here.

**Comment by glacierbits** [comment] 2020-10-14 18:00
Coming back to the @szymonlesisz 's original point, how do you manage the inputs? The user inputs the value, and it immediately disappears? What about errors and hover effects that we have in the inputs? And mobile version? I don't thing it's a worthwhile challenge, and one that can only bring more "review-like" problems to the user unable to check what they have just typed. 

To take this to the extreme: We don't use the discreet mode on the device, while the font is of the similar size to host (display size doesn't matter to CCTV camera or random onlooker, font's does). The main use case of the discreet mode, as it was designed, is to hide balances, when user wishes to check them in uncomfortable place. Not sure we do have to optimize this for somebody who wants to send 10 BTC from a crowded coffee place.

**Comment by tsusanka** [comment] 2020-10-14 19:07
Very well then :).

**Comment by slowbackspace** [comment] 2020-10-19 14:18
I think this has already been resolved as there is linked merged PR above. Feel free to reopen if I missed something.

**Closed as completed by slowbackspace** 2020-10-19 14:18 UTC
Labels: bug

**Comment by bosomt** [comment] 2020-10-23 07:49
QA OK

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T fw 2.3.3 + 2.3.4 commit 50854b921

Looks like this:

![image](https://user-images.githubusercontent.com/31506317/96970952-b54a3280-1514-11eb-8a48-fe267ec97077.png)
