### ISSUE TITLE
Minor issues in Settings/Coins section

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12074] opened 2024-04-19 06:28 UTC
**Describe the bug**
Minor issues in Settings/Coins section
- `Activate coins` button is always active even device is disconnected, pressing it will end with forever loading state
- You are not allowed to change backends when device is disconnected
- `Connect device to change Crypto settings` message does not reflect that we renamed Coins section From Crypto back to Coins

**Info:**
 - Suite version: desktop 24.4.2 (22d7c411755389aef139a5c705da2dda7f3e4af1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
<img width="924" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/46278d62-f17c-48bb-b1e4-ba23399a2ac3">

**Comment by Lemonexe** [comment] 2024-08-09 11:47
I took a look and can't reproduce the first issue - but maybe I am looking at wrong place..

EDIT: I was indeed looking at the wrong place, and both parts of the issue still stand.

**Comment by Lemonexe** [comment] 2024-08-16 08:14
Fully resolved by #13836

**Closed as completed by Lemonexe** 2024-08-16 08:14 UTC
Labels: good first issue

**Comment by bosomt** [comment] 2024-08-16 09:13
**QA OK**

- Activate coins button inactive ✅ 
- You are still not allowed to change backends when device is disconnected 🤷🏿‍♂️ , probably expected
- Connect device to change Coins settings ✅ 

**Info:**
 - Suite version: web 24.9.0 (5d77d96a2d5f48208e335047813c881415f6b31d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32
