### ISSUE TITLE
Settings > Passphrase: missing space

### ISSUE THREAD

**Issue by rating89us** [trezor/trezor-suite#4037] opened 2021-07-14 20:15 UTC
![image](https://user-images.githubusercontent.com/45968869/125686844-9cfaca68-fd7c-460e-885b-7d797a4f21b7.png)

**Comment by jerechinsky** [comment] 2021-08-16 10:00
Fixed now. Thanks @rating89us.

**Closed as completed by jerechinsky** 2021-08-16 10:00 UTC
Labels: bug

**Comment by jerechinsky** [comment] 2021-08-16 13:53
Actually not fixed but still a duplicate of #4007 so I'm keeping it closed.
