### ISSUE TITLE
FIAT balance on altcoins is incorrect on asset detail

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7090] opened 2022-12-01 14:15 UTC
Balance of altcoins displayed incorrect balance on asset detail
Example ETH - video attached:
https://user-images.githubusercontent.com/84183817/205077542-e23b5610-4ee8-4766-b604-92bf5c453595.MP4

**Comment by bouchja1** [comment] 2022-12-02 09:58
I investigated it a little bit and this is related somehow to a graph. The fiat balance represents a selected graph point. But I couldn't reproduce the state from your attached video. My values are either 0 (if a graph is not shown) or sth around 33 USD if a graph is shown.

**Comment by mnuky** [comment] 2022-12-02 10:22
Might be fixed with new version of the graph, lowering the priority and wait if it will work with the new graph

**Comment by Nodonisko** [comment] 2022-12-06 18:35
Moving this to QA, since this value originating from graph data and this part was completely refactored.

**Comment by bosomt** [comment] 2022-12-12 16:05
**QA OK**

tested on Android and multiple coins. FIAT value match Suite app.

**Closed as completed** 2022-12-12 16:49 UTC
Labels: bug, mobile
