### ISSUE TITLE
All coins show as not-supported in settings

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1304] opened 2020-03-11 12:31 UTC
fw: 2.1.0 (I think that `unavailableCapabilities` field had value 'no-capability' for every coin)
(works fine after an upgrade to 2.1.8)

![image](https://user-images.githubusercontent.com/6961901/76417041-6fcd6080-639c-11ea-8fc7-e88d8539a93c.png)

**Comment by szymonlesisz** [comment] 2020-03-16 12:09
looks like a connect bug

**Comment by szymonlesisz** [comment] 2020-03-17 16:33
should be fixed by https://github.com/trezor/connect/commit/a1de0bfb37dab1599bd207afb9bc540589d880e7

Steps to reproduce:
- go to https://suite.corp.sldev.cz/suite-web/develop/settings/wallet/ with ~ TT@2.1.0 connected

**Closed as completed by szymonlesisz** 2020-03-17 16:33 UTC
Labels: bug
