### ISSUE TITLE
New onboarding: Trezor T FW update is missing animated instructions to enter bootloader mode

### ISSUE THREAD

**Issue by stepmes** [trezor/trezor-suite#3986] opened 2021-07-02 15:13 UTC
**Describe the bug**
Starting FW update on TT through new onboarding: Animated instructions are missing, s. screenshot. 

**Info:**
Suite Version: https://suite.corp.sldev.cz/suite-web/develop/web
Browser: Chrome Version 91.0.4472.114
OS: MacOS BigSur 11.4

**Steps to reproduce:**
1. Connect Trezor T with an outdated FW
2. Go through new onboarding
3. Start firmware update

**Screenshots:**
insert here
<img width="1280" alt="Screen Shot 2021-07-02 at 5 08 00 PM" src="https://user-images.githubusercontent.com/54173889/124295066-b1b58380-db58-11eb-9250-b05984ee7482.png">
<img width="1280" alt="Screen Shot 2021-07-02 at 5 08 02 PM" src="https://user-images.githubusercontent.com/54173889/124295117-bf6b0900-db58-11eb-9bb8-1050c054c26b.png">

**Comment by sorooris** [comment] 2021-07-13 10:06
Duplicate of #4011, closing.

**Closed as completed by sorooris** 2021-07-13 10:06 UTC
Labels: bug, onboarding
