### ISSUE TITLE
ETH internal contract transactions not shown

### ISSUE THREAD

**Issue by gulikoza** [trezor/trezor-suite#3057] opened 2020-11-24 13:20 UTC
**Describe the bug**
ETH internal contract transactions are not shown and accounts with only contract transactions are not detected.
Some exchanges (eg. Bitstamp) withdraw through a smart contract. When withdrawing to a fresh address, the balance will not be seen unless the account is manually added. Even if account is manually added, no transactions are shown in history although balance is > 0.

**Info:**
 - Suite Version: 20.11.2 / b0dacc34e574235daa2427c08b8d2985baa2dc13
 - Browser: Chrome 87
 - OS: Windows 7
 - Firmware Version: Model One, 1.9.3

**Steps to reproduce:**
1. Transfer ETH to a fresh address through smart contract
2. Wait for transaction to be confirmed
3. c

**Expected result:**
ETH should be shown in balance on Dashboard and Account should have transaction visible

**Actual result:**
ETH does not show in balance, no Account is visible. If this is the first Account, coin has to be disabled and enabled again to get the balance to show.

**Screenshots:**
insert here
![image](https://user-images.githubusercontent.com/9161433/100099646-06c14680-2e60-11eb-930b-e89655ceee9e.png)

**Note(s):**

**Comment by bitofit** [comment] 2021-02-15 23:03
- Can confirm.  Although total ETH deposited from the contract is displayed as balance at the top of the account, the ETH _transaction_ from the smart contract is not displayed in the "Transactions" area.
- Transfer ETH from Argent to Trezor address to re-create
- Trezor Suite 21.2.2

**Comment by aspiers** [comment] 2021-06-11 10:21
This is extremely disappointing I'm afraid :-(  It has caused my first experience with a Trezor device to look like this:

1. Install Trezor Suite
2. Enable Ethereum as one of the coins.
3. Use the deposit address of the first account to receive some ETH from a service, which happens to have been transferred as an internal contract transaction.
4. Not only does the transaction not show up in the Suite UI, but the balance stubbornly stays at 0 ETH too, even after multiple restarts.  There is no manual refresh button in the UI, but even if there was, I guess this issue with internal contract transactions would prevent that from helping.

The following tools *all* have no issues whatsoever recognising this transaction, and they all clearly show that the correct balance is non-zero too:

- Etherscan
- Koinly
- Accointing
- CoinTracker

I really want to love Trezor products - the hardware seems great, and I love the open source approach. 
 But to spend 169 EUR on a hardware wallet which can't even report its balance correctly is, well... I'm sure you can appreciate how utterly disappointing that is.  This is not a "nice to have" feature, or some minor inconvenient bug.  It's an absolute show-stopper.  I really hope Trezor's product management and engineers can prioritise this.  It's already 7 months since it was reported!

**Comment by aspiers** [comment] 2021-06-11 10:33
Some more info - despite Trezor Suite claiming the balance was 0 ETH, I was able to send some of the ETH elsewhere via MetaMask.  After this, the balance is finally showing correctly in Suite's UI, but the original internal transaction is still not shown there.

**Comment by tsusanka** [comment] 2021-11-04 08:46
Duplicate of https://github.com/trezor/trezor-suite/issues/3658.

**Closed as completed by tsusanka** 2021-11-04 08:46 UTC
Labels: bug, feature
