### ISSUE TITLE
Incorrect total tx count from BlockBook with details=basic

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#8137] opened 2023-04-18 13:01 UTC
Calling [an endpoint for full details](https://btc1.trezor.io/api/v2/xpub/xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy) returns a different value in the `txs` field from [details=basic](https://btc1.trezor.io/api/v2/xpub/xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy?details=basic). 

One discovered issue caused by that is Suite always thinks an account [has changed](https://github.com/trezor/trezor-suite/blob/f1476a391bbd30ef14d8fa704dc03ecf7b583d6a/suite-common/wallet-utils/src/accountUtils.ts#L551) and requests and stores updated details.

**Comment by marekrjpolak** [comment] 2023-04-18 13:13
Blockbook issue, @martinboehm?

**Comment by martinboehm** [comment] 2023-04-20 15:29
@marekrjpolak Yes, it is caused by Blockbook. The API should be redesigned a bit so that it returns the count in different fields in the basic case and in the other detail levels.

Here is the explanation: the `details=basic` should be very cheap request. To get the exact number of transactions is fairly expensive because it is necessary to query all transactions for all xpub addresses, deduplicate them and then count. Therefore Blockbook does not do this for the basic details, it only sums transaction count for each xpub address (it has the count in a different DB table) without deduplication. The issue/confusion is that the API field is the same for basic and other levels.

My idea to fix this is to return `txs` field only for `details`>`basic`, where the exact deduplicated count is known. In addition to that, for all details levels create an additional field `addressTxCount` (or something like that) that will return the non deduplicated sum, which will be possible to compare across the all detail levels and can be used to check if there is a new transaction ready.

Or to make it  backwards compatible, the basic level will keep the `txs` with current value so that we do not completely break old versions of Suite.

Let me know it this would be a solution for you, it can be implemented very quickly.

**Comment by sime** [comment] 2023-04-20 15:41
Assigning to myself to bring visibility for next standup

**Comment by martinboehm** [comment] 2023-04-20 19:53
Additional clarification of when Blockbook can return what transaction count. For the detail levels `basic`, `tokens`, `tokenBalances` it is only the non deduplicated count of transactions, for the levels `txids`, `txslight` and `txs` it is able to return the correct deduplicated count of transactions. I do not think that it changes anything, just want to be more precise.

I prepared a backward compatible version of the fix here https://github.com/trezor/blockbook/commit/831fff087315a41c64e9205a6b60904f6383b135, it can be released to production any time you want.

**Comment by sime** [comment] 2023-05-05 09:35
@martinboehm Happy to proceed with the backwards-compatible fix, then we will adjust in suite as well.

**Comment by martinboehm** [comment] 2023-05-11 20:23
@sime The fix is deployed to production.

**Closed as completed** 2023-05-29 12:39 UTC
Labels: bug, connect
