### ISSUE TITLE
Coinmarket - redesign 2

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#13680] opened 2024-08-06 19:07 UTC
https://github.com/user-attachments/assets/c94f8070-57cc-496e-875c-c9e6be2631fd

https://github.com/user-attachments/assets/54fc8379-303c-4e81-898b-0779013b691d

**Comment by bosomt** [comment] 2024-08-07 05:33
This is what sell feature in coinmarket section does.
Managed to replicate it on yesterday dev build and on todays build.
Had to reset app storage via looking for /Users/bosomt/Library/Application Support/@trezor/suite-desktop-dev folder yesterday. 
Video is from today, screenshot is from yesterday
I consider it release blocker

<img width="1434" alt="Screenshot 2024-08-06 at 19 56 59" src="https://github.com/user-attachments/assets/11e61f6e-6d59-44b9-91cb-32a3fad023b9">


https://github.com/user-attachments/assets/41372ca1-9fa7-497a-a11a-2e07716da095

**Info:**
 - Suite version: desktop 24.8.0 (1c6c918e36e7413de1753b4658b80c81306203b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.8.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment] 2024-08-07 06:01
Navigating thru Sell and exchange generates lots of unexpected errors in app console.

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/19ecce42-8e42-4035-aa38-3bf019875d55">

**Comment by adderpositive** [comment] 2024-08-07 08:17
Looks like old version of the Sell sectiont - should be fixed by this PR https://github.com/trezor/trezor-suite/pull/13685

**Closed as completed** 2024-08-08 14:19 UTC

**Comment by STew790** [comment] 2024-08-09 15:20
**QA OK**
The issue is not present because the whole section was redesigned.

**Info:**
 - Suite version: desktop 24.8.1 (b4f8ad7e864cf72f3965f41e541e280bfa906a7d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
