### ISSUE TITLE
Trezor Suite does not show full balance in My accounts

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezor-suite#6880] opened 2022-11-10 16:30 UTC
**Describe the bug**
1440x810 pixel display. There is plenty of unused width in the My accounts to show the full BTC balance, but it cuts off the last two digits.

**Info:**

Version 21.7.1 linux

**How to reproduce**
Make trezor suite wide.
Observe something like

My accounts

Bitcoin 1
0.085045

Observe the Accounts page shows the full
Bitcoin 1
0.08504506 BTC

**Expected behavior**
Show the last two digits, there is at least 200 pixels of unused space in that My Accounts

**Screenshots**
I would, but it is confidential.

**Comment by tomasklim** [comment] 2023-04-26 07:53
Duplicate of #6456

**Closed as completed by tomasklim** 2023-04-26 07:53 UTC
Labels: bug
