### ISSUE TITLE
Use `Stop` instead of distinguishing `Pause` and `Cancel` in coinjoin account

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7871] opened 2023-03-20 14:03 UTC
**Why?**
During testing, it turns out that users don't understand the difference between `pause` and `cancel` in our UI. 

**Current behaviour**
`Pause` - Pauses the coinjoin, but the user can resume at any time with one click. _Cannot change conjoin parameters like `desired anonymity level` or `max mining fee`_
`Cancel` - Cancels the coinjoin. User must reconfirm terms with new coinjoin including reconfirmation of the total number of signatures on the Trezor. 

<details>
  <summary> Pause state is sometimes triggered automatically</summary>

 - entering Send section (continues after leaving the section)
 - losing internet/Tor connection (continues after reconnection)
 - turning off Suite (doesn't start automatically)
 
</details>

### Proposal

 - If the user stops the coinjoin
    - ~~He can resume coinjoin again with one click (as before pause)~~
    - Once user presses the play button he will have to confirm the terms and the new number of rounds again (until we implement: https://github.com/trezor/trezor-suite/issues/7456
    - Only way how to reach `pause` state (and automatically resume) is when user access the send page. And only until we solve it by https://github.com/trezor/trezor-suite/issues/8373

 - Rename feature to `Stop`
 - Remove `...` 
 
![Screenshot 2023-03-20 at 14 59 04](https://user-images.githubusercontent.com/26002916/226362629-850a80e3-e864-49a2-96ae-5ddd70bee630.png)

**Comment by andrewkozlik** [comment] 2023-03-21 09:49
> * If the user stops the coinjoin
>   * He can resume coinjoin again with one click (as before pause)
>   * He can change the parameters of coinjoin (_once he presses the play button he will have to confirm the terms and the new number of rounds again_)

I propose that if the user changes the parameters then:
1. They do not necessarily have to confirm the T&Cs. (It doesn't make sense, if you just press play then T&Cs confirmation is not needed, but if you increase anonymity level, then T&Cs confirmation is needed? T&Cs confirmation should be orthogonal to this issue. Suite should keep track of the T&Cs version that the user confirmed and require reconfirmation if the version changes.)
2. If the required number of rounds is less than the number left in the existing authorization (e.g. if the user decreased their target anonymity), then in principle they don't need to confirm on Trezor.

**Comment by hynek-jina** [comment] 2023-03-21 10:18
You are right that there is no need to confirm again T&C. Actually we need to confirm new T&C only when they are updated.. But it's another topic...

**Comment by komret** [comment] 2023-03-21 13:50
How should the top status bar react to it? Currently, it is visible during the `paused` state. This makes sense when the coinjoin is stopped temporarily/automatically, but not if the user stops it and does not intend to continue. We could make it closable.

Also, unless we want the user to confirm restarting the session on the device every time, we will need to introduce some flag indicating whether settings changed while it was stopped.

**Comment by andrewkozlik** [comment] 2023-03-21 13:55
> [...] if the user stops it and does not intend to continue. We could make it closable.

Closing the status bar could be equivalent to cancelling, I like that, i.e. Suite should send `CancelAuthorization` message to Trezor.

**Comment by Hannsek** [comment] 2023-03-21 14:15
So that closing the status bar will actually cancel cj? I do not think this is a good approach as I see the banner as a notification which I can close anytime and nothing would happen.

**Comment by hynek-jina** [comment] 2023-05-17 10:54
I think it is better to remove status bar when user stops coinjoin. And not being able to remove this status bar otherwise.

**Comment by dahaca** [comment] 2023-06-30 13:30
@hynek-jina what about the "pause CJ after this round" button from the critical phase modal? Change it to "stop" as well, right?

**Comment by hynek-jina** [comment] 2023-06-30 13:39
@dahaca 
Yes

**Comment by dahaca** [comment] 2023-06-30 14:30
@hynek-jina What about pausing when a critical error happens / acc is not synced / tor connection breaks? Not so informative to just stop the session imo, since you would not know the reason unless we add a modal or something.

**Comment by hynek-jina** [comment] 2023-06-30 15:02
We can disable coinjoin in such scenarios. Tooltip explaining what is happening and resume once it is back again

**Comment by dahaca** [comment] 2023-06-30 15:07
Meaning pausing? It cannot be auto resumed after being canceled. Also, a tooltip does not communicate that there was an error, since it's an event, not a permanent state, like tor malfunctioning. And what about disconnecting a device?

**Comment by dahaca** [comment] 2023-06-30 15:39
One more thing: a session will no longer be saved as `paused` with a remembered wallet, it will not be saved at all? And device authorization should be cleared as well on app launch?

**Comment by hynek-jina** [comment] 2023-06-30 18:03
Yes, pausing.
I think that with disconnected device you have to stop coinjoin anyway. Trezor will not remember preauthorization.
Do we need to store the session for any reason?

**Closed as completed** 2023-07-12 16:29 UTC
Labels: coinjoin

**Comment by bosomt** [comment] 2023-07-16 09:59
**QA OK**


**Info:**
 - Suite version: desktop 23.8.0 (9018aa1e38c9e37e963d67753a1ae8ff5dc1ab05)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.8.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision feed79d80b99e75665ff41c83d4cbf5a0760f107)
 - Transport: BridgeTransport 2.0.33
