### ISSUE TITLE
Error while scanning QR code 

### ISSUE THREAD

**Issue by JanVaclavek** [trezor/trezor-suite#8627] opened 2023-06-02 10:48 UTC
**Describe the bug**
I got the following error while scanning a bitcoin address represented as a QR code in the Send section in Trezor Suite. 

![image](https://github.com/trezor/trezor-suite/assets/61776178/4ce5459a-7175-4b6f-8cb7-309594670d1c)

**Info:**
-   Suite Version: app, version v23.5.2
-   OS: Ubuntu 22.02.2

**Expected behavior**
I expected that bitcoin address and amount will be recognized from the QR code.

**Comment by Hannsek** [comment] 2023-06-02 10:59
I couldn't reproduce it. The problem might be in the qr code as it is (in your case) not only an _address_ but _address and amount_.

Can you try qr code only containing qr code?

**Comment by tomasklim** [comment] 2023-06-05 06:43
This QR code breaks it
https://satoshilabs.sentry.io/issues/4205912544/?project=5193825&query=e.at+is+not+a+function&referrer=issue-stream&statsPeriod=14d&stream_index=0

 ![image](https://github.com/trezor/trezor-suite/assets/33235762/a2947a47-5000-4f6a-9df2-7e305e50002c)

**Comment by tomasklim** [comment] 2023-06-05 06:47
@dahaca 
<img width="361" alt="Screenshot 2023-06-05 at 8 47 24" src="https://github.com/trezor/trezor-suite/assets/33235762/d096803b-653b-487d-941c-ca5b1858b14c">

**Comment by matejkriz** [comment] 2023-06-05 11:31
already fixed in https://github.com/trezor/trezor-suite/pull/8595/files or different issue? @dahaca

**Comment by tomasklim** [comment] 2023-06-05 14:57
I took the screenshot in current dev, so probably new issue

**Closed as completed** 2023-06-06 12:22 UTC
Labels: bug, release
