### ISSUE TITLE
Change wallet focus

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5402] opened 2022-05-17 09:26 UTC
**Info:**

-   Suite Version: 22.5.2

**How to reproduce**

1. Open switch wallet modal
2. (Focus labeling button (focus color is the same color as background))
3. Click on remember switch
4. Leave the rectangle and focus is still there

**Screenshots**

https://user-images.githubusercontent.com/33235762/168777888-0ac3699f-8ccf-43eb-a4a6-c60272861ff2.mov

**Comment by bosomt** [comment] 2023-01-02 16:07
**QA NOK**

issue is still present in Suite app 


**Info:**
 - Suite version: desktop 23.1.0 (c657469ccc2bc2cfb66a4e230013c8ef93d50e55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.1.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by AdamSchinzel** [comment] 2023-08-10 10:22
Works for me on production now

**Comment by AdamSchinzel** [comment] 2023-08-10 10:22
@trezor/qa can you test again?

**Comment by bosomt** [comment] 2023-08-11 09:42
**QA OK**

i was able to reproduce issue via remember/unremember button ;)


https://github.com/trezor/trezor-suite/assets/31506317/f9f30fa2-5121-431e-a773-4b0eb4a19fc6

**Info:**
 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33

**Comment by dahaca** [comment] 2023-12-08 11:30
Fixed in suite-e
<img width="644" alt="image" src="https://github.com/trezor/trezor-suite/assets/45338719/1c213be0-99d0-4a2a-af59-22a9a13a2462">

**Closed as completed by dahaca** 2023-12-08 11:30 UTC
Labels: bug, good first issue, low hanging fruit
