### ISSUE TITLE
Infinite onboarding loop

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#3250] opened 2021-01-10 15:23 UTC
**Describe the bug**
Infinite loop in onboarding

**Info:**
 - Suite Version: all
 - Browser: all
 - OS: all
 - Firmware Version: all
**Steps to reproduce:**

1. Click 'Access Suite'

![image](https://user-images.githubusercontent.com/3112191/104126938-9f078200-535f-11eb-95a7-e030bde7521f.png)

2. Click 'Access Suite'

![image](https://user-images.githubusercontent.com/3112191/104126948-adee3480-535f-11eb-9773-11f0fafefea0.png)

3.

![image](https://user-images.githubusercontent.com/3112191/104126995-de35d300-535f-11eb-8303-adc5ec4b6d1b.png)

4. you are on the first screen again

![image](https://user-images.githubusercontent.com/3112191/104127009-edb51c00-535f-11eb-9c95-89584b91ba7e.png)

**Comment by slowbackspace** [comment] 2021-01-11 11:06
Discussed with @mroz22, it should be pretty straight-forward to break the loop and don't offer an option "Access Suite" in Onboarding if the device is not initialised. We should also cover this by e2e test to be sure it works correctly.

**Comment by tsusanka** [comment] 2021-01-15 08:41
Duplicate of https://github.com/trezor/trezor-suite/issues/2935. And I don't think it makes sense to solve it anymore since the onboarding is being redesigned completely. @matejzak

**Comment by glacierbits** [comment] 2021-01-15 09:25
Yes. With all respect, I will closed this issue. We identified 26 issues with the current onboarding in total.. 🔫 Good news is, the new onboarding prototype is 90% ready and much better both design & flow-wise. Expected to be released in March release.

**Closed as completed by glacierbits** 2021-01-15 09:25 UTC
Labels: onboarding
