### ISSUE TITLE
Test Suite in Constrained environment

### ISSUE THREAD

**Issue by goodhoko** [trezor/trezor-suite#3615] opened 2021-04-09 09:05 UTC
Before we go for the official release of Suite it would be nice to test it on a machine that is not as powerfull as machines of most developers. It might be, that this already happens within the QA team.

I think a very basic test of the very basic functionality should suffice eg. "does it launch, and connects to a trezor?" The goal is to make sure the app won't fail spectacularly, not that it will run smooth. We definitely don't want to waste time over-optimizing.

**Comment by glacierbits** [comment] 2021-04-15 09:45
I leave that for your (and QA's team) consideration @tsusanka . Thanks!

**Comment by tsusanka** [comment] 2021-04-16 11:00
I am afraid it is unreal to do it before public launch and since it is not a regression against wallet.trezor.io I would not enforce doing this before the launch. However, I agree we should do it at some point.

**Comment by tsusanka** [comment] 2021-08-10 20:55
@stepmes any feedback from users about performance?

**Comment by stepmes** [comment] 2021-08-16 07:58
@tsusanka there were several reports about Suite using too much CPU. I haven't heard much about the Suite itself being slow or laggy, but Suite slowing down the computer when it runs is being reported from time to time. https://www.notion.so/satoshilabs/Suite-taking-up-too-much-CPU-8be3fb92b07f442abb4e1dea4a7a2cce

**Comment by tsusanka** [comment] 2021-08-16 08:01
@stepmes do these concern latest two or three versions? Because this was indeed true few versions back but we did number of improvements then (in ~April or so, I can find the exact date if needed).

**Comment by stepmes** [comment] 2021-08-16 14:23
You're right, the user stories mentioning this are indeed rather old. I just scanned through the most recent feedback and haven't encountered anything that could point to this being an issue now. If the previous reports aren't relevant anymore, I think it should be all good.

**Comment by tsusanka** [comment] 2021-08-16 14:33
Ok, let me close this one and please speak up in case this reappears.

**Closed as completed by tsusanka** 2021-08-16 14:33 UTC
