### ISSUE TITLE
Show Bitcoin value in Satoshis (sat)

### ISSUE THREAD

**Issue by MatveiP** [trezor/trezor-suite#3004] opened 2020-11-18 10:51 UTC
_User's request:_
_"Add an option for viewing as whole btc or as satoshis. So if you have 0.1 btc it would show 10.000.000 satoshis"_

- Use only BTC/Sats (no bits, mBTC, uBTC, ... )
    - Bitcoin units whole names: `Bitcoin` / `Satoshis`
    - Next to amounts: `BTC` / `sat`
    
- [ ] Select in settings (not in Bitcoin card detail)
<img width="213" alt="image" src="https://user-images.githubusercontent.com/45338719/171172582-7bfdc396-b101-494b-aa17-c89a4bbad6bd.png">

- [ ] Settings should be visible only with activated at least one of the coins - `Bitcoin`, `Bitcoin Testnet`, or `Bitcoin Regtest`
- [ ] Changing the displayed Bitcoin unit globally by clicking on Bitcoin amount

Location | Change units on click
-- | --
Dashboard/ Bitcoin balance | ✅
Accounts/ Listed accounts | ✅

- [ ] On hover displays tooltip
<img src="https://user-images.githubusercontent.com/45338719/171172806-69d233c7-dc70-4d35-afcf-15dd014ffc8e.png" alt="drawing" width="400"/>

**Comment by prusnak** [comment] 2020-11-18 10:58
This needs to be synchronized with the firmware change, so we end up with showing the same on both Suite and Trezor - https://github.com/trezor/trezor-firmware/issues/324

**Comment by prusnak** [comment] 2020-11-23 11:34
We've decided that we'll add the denomination attribute to SignTx and Trezor will show amounts according to this.

The setting will be stored in the Suite.

**Comment by who-is-apo** [comment] 2021-01-15 11:35
Would be good to have a few more choices there, like mBTC and µBTC. Satoshis still seem to be too small of a value, given the current Bitcoin price.

**Comment by prusnak** [comment] 2021-01-22 13:13
This feature has been merged into the firmware via https://github.com/trezor/trezor-firmware/pull/1369 (BTC, mBTC, uBTC and sat denominations) and will be released during the next round of firmware updates on 10th of February.

That means we can continue with the next steps and implement this in Connect and Suite.

**Comment by hynek-jina** [comment] 2022-07-20 09:25
@dahaca 
I'm sorry for the confusion.. Please use `sat` instead of `Sats` to be consistent with Trezor device and fee expression. Thank you

**Comment by STew790** [comment] 2022-08-02 11:34
**QA NOK**
When I first open the app or the web Suite, in the settings there is no "default" settings for this feature, so the drop-down menu is just blank.

This also affects https://github.com/trezor/trezor-suite/issues/5590

![image](https://user-images.githubusercontent.com/48477147/182364822-74a6581c-2563-4931-9dba-ed34fd89d355.png)

**Info:**
 - Suite version: desktop 22.8.0 (4692fffe7467553f430d248c630b74f6aad6ad58)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment] 2022-08-03 08:18
**QA NOK**

when i fill in sats in Send dialogue Suite thinks its whole Bitcoin

<img width="791" alt="image" src="https://user-images.githubusercontent.com/31506317/182559323-4bcbb29c-6d68-47f6-84c7-9cdf22f3bfa7.png">

**Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by STew790** [comment] 2022-08-03 08:45
Just want to add that the Send modal actually shows it correctly.

![image](https://user-images.githubusercontent.com/48477147/182565445-f4844dcb-1a08-4531-ac97-d785005468f5.png)


**Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by matejkriz** [comment] 2022-08-04 14:13
Other coins also show sats as unit in send form. All **except** Ethereum, Ethereum Testnet, Ethereum Classic and Cardano. So for example Cardano Testnet, XRP, ... are wrong.
![image](https://user-images.githubusercontent.com/3729633/182868141-4fdf824a-9d96-4221-bdef-cac050126977.png)

**Comment by matejkriz** [comment] 2022-08-04 14:36
> **QA NOK** When I first open the app or the web Suite, in the settings there is no "default" settings for this feature, so the drop-down menu is just blank.
> 
> This also affects #5590
> 
> ![image](https://user-images.githubusercontent.com/48477147/182364822-74a6581c-2563-4931-9dba-ed34fd89d355.png)
> 
@STew790  How to reproduce this one? I'm not able to reproduce it in 22.8.1.

**Comment by dahaca** [comment] 2022-08-05 12:23
> How to reproduce this one?

Was a problem with migrations, fixed, will be in the PR

**Comment by matejkriz** [comment] 2022-08-05 14:32
one more feature to test: bitcoin URI handlers

**Comment by STew790** [comment] 2022-08-05 15:01
**QA NOK**
I tried the bitcoin URI send form fillout and, unfortunately, it fills out as Bitcoin and not as Satoshis. Also, throws out an error as shown in the screenshot.

![image](https://user-images.githubusercontent.com/48477147/183104225-126089bc-153d-430a-bb41-5c463a9375d3.png)

**Info:**
 - Suite version: web 22.9.0 (2cbf18207db1f174d7fe9e08cc937039c09c6064)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment] 2022-08-09 09:04
Just testing 22.8.1 release candidate and left Satoshis enabled.
When i try to send all from accounts of coins like VTC or LTC Suite gets confused, nor sure if you already know about it.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/31506317/183609879-05365798-a5c9-4f5b-9ca8-6d459258ff28.png">

<img width="753" alt="image" src="https://user-images.githubusercontent.com/31506317/183609915-6782e4a8-2037-4a58-bd17-b8861c508010.png">



**Info:**
 - Suite version: desktop 22.8.1 (4ddcf5c6b05fefda0425919434a936e534482a1e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by dahaca** [comment] 2022-08-09 11:49
One more bug that I am fixing at the moment happens during this flow:

* **BTC** is the active unit
* User navigates to **SEND** and enters a valid amount
* User leaves the form and switches the units to **SAT**
* User returns to the form
* The amount is filled with the previously entered one, not in line with the currently selected unit
* Amount field likely has an error

**Comment by bosomt** [comment] 2022-08-11 08:15
**QA OK**

checked: 
https://github.com/trezor/trezor-suite/issues/3004#issuecomment-1209114134

**QA NOK**

bitcoin uri still fills out BTC to sats field, no sure if its somehow fixable 

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/31506317/184091731-ac15372c-e710-4bd0-8e1e-970c216fc6a7.png">

**Info:**
 - Suite version: desktop 22.9.0 (4d282475dccf0c52a0094e9b024fce5ad7c54e53)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.31

**Comment by bosomt** [comment] 2022-08-11 08:50
Found one discrepancy in transaction history export.
Even you change Suite from Bitcoin to sats transaction history is still exported in Bitcoin values.

Info:

    Suite version: desktop 22.9.0 (https://github.com/trezor/trezor-suite/commit/4d282475dccf0c52a0094e9b024fce5ad7c54e53)
    Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
    OS: MacIntel
    Screen: 1680x1050
    Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
    Transport: bridge 2.0.31

**Comment by bosomt** [comment] 2022-08-11 10:57
EDIT:
**QA OK**

 - Suite version: web 22.9.0 (0e8641eddc9e9915056ad7959f2759e477485656)
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.31

**QA NOK**

It's not possible to bump or finalize BTC or TEST transactions when sats are enabled
Transaction signing error: Parameter "amount" has invalid value "0.00007624". Integer representation expected.

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/31506317/184118831-37ad98db-c298-4b47-8613-86bea5ee7d29.png">

**Info:**
 - Suite version: web 22.9.0 (4d282475dccf0c52a0094e9b024fce5ad7c54e53)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Comment by matejkriz** [comment] 2022-08-11 14:31
> Found one discrepancy in transaction history export. Even you change Suite from Bitcoin to sats transaction history is still exported in Bitcoin values.
> 
@bosomt That is not part of this issue, but follow-up https://github.com/trezor/trezor-suite/issues/5829

**Comment by bosomt** [comment] 2022-08-11 14:45
@matejkriz thank you ! haven't noticed it before...

**Closed as completed** 2022-08-29 15:38 UTC
Labels: bitcoin

**Comment by bosomt** [comment] 2022-08-31 09:05
**QA OK**

I have not found any issue.
If we find one we will create separate issue.

**Info:**
 - Suite version: web 22.9.0 (0e8641eddc9e9915056ad7959f2759e477485656)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Universal (revision eb182b923f39111d9307a25a86a49d395c6611b0)
 - Transport: bridge 2.0.31
