### ISSUE TITLE
[Improvment] - Unify Bitcoin Account types (Taproot, SegWit, etc) into a single Account

### ISSUE THREAD

**Issue by ffrediani** [trezor/trezor-suite#14427] opened 2024-09-19 04:26 UTC
Currently for each Bitcoin Account the user has to choose which type (Taproot, SegWit, etc) and it appears as separate accounts in the Dashboard.

Instead of having each account separated let users have a single one and inside it to turn on and off what types to work with for that account, with one of them being the default (e.g: Taproot) which will always be shown first. When willing to Show full address for deposits let the user choose, if desired another type instead.

This will bring the benefit to have all transactions being them Legacy, SegWit or Taproot under a single list and consolide things better into a single place. This also brings gains by making it always visible to users that Taproot addresses are also available should the source wallet has support to it encouraging its usage further, increasing adoption, improving network efficiency and reducing network fees.

Another advantage by having it into a single panel rather in separate accounts is that when having a default Taproot account type, should the user needs to deposit on his SegWit address it is easier to toggle and pick it instead, so it paves the way for Taproot become the default Bitcoin Account type sometime in the future.
The Details tab, Account type inside the Bitcoin account can be adjusted to let user toggle which types for that account and for showing each address either add a radio button near the Show full address or inside it let the user change which will reflect on Trezor for confirmation.

For reference Exodus wallet has an Advanced Options on the right tab which let user turn on and off Legacy and Taproot addresses. When turned on clicking on Receive it shows first the default on and let user change for the other types .

Taproot has been implemented on the vast majority of wallets and platforms missing just a few of them so it time to have such adjustments in order to encourage further adoption. Find a URL that show the status of Taproot adoption https://whentaproot.org/#support

**Comment by Hannsek** [comment] 2024-09-19 05:29
Hi @ffrediani, thanks for that issue. We are internally discussing whether or not to put Taproot address as the default on for over 2 years. We however haven't come to the clear decision that. The main argument against is that even some biger exchanges do not support withdrawals to Taproot address.

Regarding the one account, this is not the way to go in our opinion as more script types will come in the future and it would easily become messy. There are however other ideas how to cope with it, like having BTC unified account (derivation path `m/XXX’/coin’/account’/script_type/change/index`, where `XXX` is any arbitrary index), but it also has some downsides and we haven't come to the conclusion.

I am closing this issue now, but feel free to continue in the discussion.

**Closed as not planned by Hannsek** 2024-09-19 05:29 UTC

**Comment by ffrediani** [comment] 2024-09-19 14:18
I think you didn't understand it fully. The improvement request is not to have Taproot as the default Bitcoin wallet in Trezor yet. As mentioned this would be a consequence at some point in the future and this improvement can contribute for that to happen sooner. I understand the limitations there are around still.

For example I asked Binance about it and they said that you can already make withdraws to Taproot addresses. You can't however deposit into a Taproot as they only provide a SegWit address, which with this improvement would not be an issue at all as when sending funds from Trezor Suite it would detect the destination wallet is a SegWit and send it normally.

The single account simplifies the management by 1) letting the use choose which type he wants to have, 2) giving the chance to easily choose what address type he wants to receive funds, 3) have all Bitcoin funds inside a single account which simplify things in the suite, 4) have a single list of transactions in a single place simplifying things as well.

@Hannsek please don't close the issue just because you didn't understand it in fully or because you particularly don't find it useful in your personal point of view. If you censor like that you are making a decision on your own and remove any possibility people may find it easily, comment and contribute with more details. You mentioned not even your guys are sure internally yet. I understand developers may wish to have less issues as possible in the radar but this one has base and has been well elaborated. Let it mature please.

**Comment by Hannsek** [comment] 2024-09-20 07:51
> 1) letting the use choose which type he wants to have

Majority of users do not know that there are multiple types of addresses.

> 2) giving the chance to easily choose what address type he wants to receive funds

Again, standard user does not know. 

By these you actually make the experience worse.

**Comment by ffrediani** [comment] 2024-09-20 12:05
@Hannsek you seem to not being able to understand it properly and not even endeavoring much for it. Instead you seem to have some specific point of view and dismissing all the information I am bringing and not willing to do much effort to understand the details. You keep focusing that this will be a problem for the users and nothing else.

> Majority of users do not know that there are multiple types of addresses

They don't necessarily need to know. For those things will keep working as they are now with SegWit addresses as default.
But for those who know and are willing for example to have other addresses for scenarios where they understand what Taproot they would be able to change choose simply from a small menu.

Exodus Wallet have it already and works exactly this way I am mentioning.
Did you bother to check what other wallets do and how they do ? OneKey have a incredible simple interface that does exactly what I mentioned. You go into Bitcoin account and it shows by default the SegWit address for deposits and should the user wants he may choose a different type, all inside the same account. If he doesn't know what that is doesn't change anything from what is normally expected.

I have shared the information that Binance confirmed that it allows withdraws to Taproot addresses normally plus the majority of other main wallet softwares and this was ignored.

Again when sending funds in such scenario that is already covered and the suite can detect the type of address for when sending the transaction.

You seem to be refusing to re-open this issue and let other people participate and contribute. You seem to consider that you personal point of view is enough to consider this is not necessary and this in practice is censorship. If you don't accept to re-open this issue I will make a formal complain to the company's management to review this attitude and show that you are censoring valuable improvements just based on your own point of view that not necessarily represent what other would think.

**Comment by Hannsek** [comment] 2024-09-20 15:09
You are talking about two things:

1. UX of receiving funds: 
Your proposal is one among many we are researching. We need to make sure the UX would be unified across all assets in Suite and that users don't run into issues like receiving to legacy addresses, which leads to paying more fees for transactions. While we understand that more advanced users might want to choose between address types on the receiving modal, we need to carefully design this feature so it doesn’t add complexity for those who aren’t familiar with different Bitcoin address types. 

2. Account management:
Consolidating Bitcoin accounts into one has both pros and cons, which we are evaluating (compatibility issues, transaction and UTXO management, ...). It also add complexity into the firmware, as the device would need to handle spending from multiple script types within a single transaction.
We are exploring various approaches that would maintain the balance between simplicity for average users and flexibility for advanced users. 

Your point about encouraging Taproot adoption is valid, and we’re following the progress of Taproot support across exchanges and wallets. However, full adoption isn't universal yet. We're still evaluating whether making Taproot the default would present issues for users interacting with platforms that don’t yet support it.

Feel free to continue the discussion. The issue is not locked for new comments.

**Comment by ffrediani** [comment] 2024-09-20 18:40
@Hannsek good that you are researching and it is in the radar, means that it makes some sense.
Regarding a scenario where a user may receive funds in a legacy address (intentionally or not) that still not the end of the world. Funds would still be secured and the only bad point would be a higher fee.

Allow me the opportunity to put in a different way so we have a more clear view of this improvement suggestion:

- This is not about putting Taproot as the default wallet address for Bitcoin accounts now. It is understandable it may still not be the time for that given the reasons known.
- For basic users, it doesn't have any potential to confuse them because accounts can still keep being created by default as Native SegWit and show its address by default for user deposits.
- If the user knows what he is looking for he may choose a different address type from a dropdown menu (e.g: Taproot)
- Same way a more advanced user may choose to change his Bitcoin account to show Taproot addresses by default and should he needs a Native SegWit it is just a question of choosing it from the menu inside the same account.
- For sending funds from Trezor that should be a big issue give the detection of the destination address format (yes noted the concerns around transition and UTXO management - fair enough)

Regarding the second point about account consolidation it is a valid point about spending from multiple script types in a single transition.

You concern about simplicity is very valid for sure. Agree. That's why would be important to decide well (after the concerns on the backend are resolved) how to design the UX to make it available for those who know what they are doing, but doesn't make easy for mistakes of confusion.

**Comment by ffrediani** [comment] 2024-09-25 00:43
On the example transactions below it is possible to see withdraws from one of Binance's Hot Wallets to a **bc1p** address which shows this possibility.

https://www.blockchain.com/explorer/transactions/btc/93806c7f654a542a32e0240d0afdb14fa673d44d7c3aaab2f4064b932c10722e
https://www.blockchain.com/explorer/transactions/btc/3060511206d70a0773d717f70872ee9d8c0ee0b91f22b0b04063364166448c21
https://www.blockchain.com/explorer/transactions/btc/96b8d7afb5fe3250aa055e9bd6e29b02ac260f58dedcb5ffe60b30db25562c6e
