### ISSUE TITLE
Text missing in Ethereum staking, {symbol} instead of ETH

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#11633] opened 2024-03-19 09:15 UTC
**Describe the bug**
Text missing in Ethereum staking, {symbol} instead of ETH.
Bug is present in all languages, **except Czech.**

**Steps to reproduce:**
1. Load an account with ETH funds
2. Enable Debug mode
3. Staking banner will appear in dashboard

**Info:**
 - Suite version: web 24.3.2 (f67de55c38fb87853e66fafc2143fe3b17ac6e54)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Correct text with ETH is showing.

**Screenshots:**
![Screenshot 2024-03-19 at 10 02 06](https://github.com/trezor/trezor-suite/assets/63164324/31691272-023a-4774-b9cb-cfa24ea37ef0)
![Screenshot 2024-03-19 at 10 02 56](https://github.com/trezor/trezor-suite/assets/63164324/0bf97588-ba15-4f70-b096-d1b75910e034)
<img width="1552" alt="Screenshot 2024-03-19 at 10 04 18" src="https://github.com/trezor/trezor-suite/assets/63164324/f6e122ca-a6bb-4689-99a9-d8cfa3530ca5">

**Comment by sime** [comment] 2024-03-19 09:27
Keeping an eye on this, it's fixed in develop.

**Comment by tomasklim** [comment] 2024-03-20 10:25
It was caused by crowdin sync from develop merged into release branch

**Closed as not planned by tomasklim** 2024-03-20 10:25 UTC
Labels: bug

**Comment by sime** [comment] 2024-03-20 23:15
EAP issue only.
