### ISSUE TITLE
New onboarding - ConnectDevicePrompt inconsistencies

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3971] opened 2021-07-01 11:47 UTC
**Describe the bug**
Implementation of the ConnectDevicePrompt's copy and icon differs from the design provided, suggesting an error state was achieved instead of just a different or other device state.

**Info:**
 - Suite Version: app + web 21.6.2, commit 41f736b3bfb09303a2acfbae5ef2bd55ee73985c
 - Browser: Chrome 91.0.4472.77, Firefox 88.0.1
 - OS: NixOS 21.05, Win10 19042.1052
 - Bridge: 2.0.27 standalone, 2.0.31 Suite-bundled
 - Firmware Version: model T 2.4.0

**Steps to reproduce:**
1. Lauch Suite and wait for the Welcome screen,
2. Connect a device in either:
   -  bootloader mode,
   - a not-initialized device,
   - a device with no firmware,
   - a device with an old firmware that requires update before it can be used,
3. Observe the ConnectDevicePrompt title and icon.

**Expected result:**
"Device connected" is displayed.

**Actual result:**
"Device detected in incorrect state" is displayed.

**Screenshots:**
Actual:
![image](https://user-images.githubusercontent.com/10185314/124119388-bef84280-da72-11eb-8923-edf07d7e3aff.png)
Expected:
![image](https://user-images.githubusercontent.com/10185314/124119421-ca4b6e00-da72-11eb-93f2-2fe29fb9d5b1.png)

**Comment by dimasivan** [comment] 2021-08-09 12:32
I can see error screen just in case if device is in boot-loader mode which is correct

Next cases work as expected after storage clean
- if device has no firmware installed -> connect your device -> firmware check -> firmware installation
- if non-initialized device -> connect your device -> firmware check -> init process
- if device w/ old firmware -> connect your device -> firmware check -> update firmware

**Comment by sorooris** [comment] 2021-08-10 14:17
There are currently 169 tickets on support with people being very confused by the copy "Device detected in incorrect state" and it would be nice to resolve this issue ASAP so the number of tickets does not multiply further.

Current solution suggested by support agents is available in [notion](https://www.notion.so/satoshilabs/Device-detected-in-incorrect-state-bdf5783d34814ab7b8da9f7a5050b036).

cc @tsusanka @alex-jerechinsky

**Comment by tsusanka** [comment] 2021-08-10 14:56
>   - bootloader mode,
>   - a not-initialized device,
>   - a device with no firmware,
>   - a device with an old firmware that requires update before it can be used,

I agree with @pingpwned that I see this screen only for the first case. Not the other ones. @sorooris could you fix the original post please if it is indeed so?

----

@matejkriz I believe yours https://github.com/trezor/trezor-suite/issues/4132 is a duplicate of this one. Could you please discuss with @pingpwned the ideal solution? @Hermez-cz will help with the product design.

**Comment by sorooris** [comment] 2021-08-10 14:57
i'll retest and fix

**Comment by sorooris** [comment] 2021-08-10 15:15
> a device with an old firmware that requires update before it can be used

The issue is present either after Suite's local storage is wiped or when accessed in browser in incognito mode.

Precondition: **Suite local storage wiped**

Steps to reproduce:
1. Connect device Trezor Model One to the computer,
2. Launch Suite in browser's incognito mode,
3. Confirm analytics and select Access Suite.

OR

1. Launch Suite,
2. Delete app's local storage,
3. Connect Trezor Model One,
4. Cancel the update modal.

Suite: 21.7.1, 21.8.1
Browser: N/A, Chromium 92.0.4515.107
OS: NixOS 21.05
Device: model One 1.5.2

```
$ trezorctl get-features 
/nix/store/hs2mvshbmr1wfwxa7q4cz0zggrmpjgmp-python3.7-trezor-0.12.2/lib/python3.7/site-packages/trezorlib/client.py:238: UserWarning: Firmware is out of date
  self.check_firmware_version(warn_only=True)
Features (131 bytes) {
    bootloader_hash: 32 bytes 0x7651b7caba5aae0cc1c65c8304f760396f77606cd3990c991598f0e22a81e007,
    device_id: 'A9A43EFE1876242E165F3474',
    flags: 3,
    imported: False,
    initialized: True,
    label: '1.5.2',
    major_version: 1,
    minor_version: 5,
    needs_backup: False,
    passphrase_protection: True,
    patch_version: 2,
    pin_protection: True,
    revision: 20 bytes 0xe4cc08775fc9c204f295442f930326eb7877f2d4,
    unlocked: False,
    vendor: 'bitcointrezor.com',
}
```


Web 21.8.1
![image](https://user-images.githubusercontent.com/10185314/128892234-196ddb45-0665-4bff-bc10-d8d417e5af96.png)
App 21.7.1
![image](https://user-images.githubusercontent.com/10185314/128892307-a5acb30c-b183-4f2f-a3d2-35fab389dbcf.png)

**Comment by sorooris** [comment] 2021-08-10 15:21
Please before I continue retesting each case - do we understand each other correctly that people are confused about this text: "Device detected in incorrect state"?
![image](https://user-images.githubusercontent.com/10185314/128893142-82ac4998-6dec-4513-bee5-6bcdfe0b011c.png)

**Comment by sorooris** [comment] 2021-08-10 15:31
> a device with no firmware

Previously accessed Suite (preferably with some other device), then connecting a Trezor with no firmware.
 
![image](https://user-images.githubusercontent.com/10185314/128894260-0b4691b6-7107-4214-ac48-05ffe4fbb1d7.png)

**Comment by tsusanka** [comment] 2021-08-10 18:54
Yeah I think this is mostly about copy.

**Comment by Hermez-cz** [comment] 2021-08-11 05:51
> Yeah I think this is mostly about copy.

Yes, but... Product wise we need to have a clear checklist of all technically distinguishable states and their copy/design to make sure we're clear with our users. Working on this with our research team and will provide solution here ASAP.

**Comment by sorooris** [comment] 2021-08-11 06:58
sorry, i had some issues with my account and couldn't post here, should be okay now
![image](https://user-images.githubusercontent.com/10185314/128983578-685c6173-bd9e-49e3-a3b6-853f0e1ae2bc.png)


> a not-initialized device

and I was able to achieve the ConnectDevicePrompt in "Device detected in incorrect state" version after connecting an initialized Model T during firmware update - i'll specify the steps to reproduce later if needed.
![image](https://user-images.githubusercontent.com/10185314/128894439-7a5a031f-4095-4a46-8a76-1e85eb3ee47b.png)

**Comment by matejkriz** [comment] 2021-08-12 13:13
https://github.com/trezor/trezor-suite/issues/4132 is not a duplicate, but related...

@Hermez-cz could we support you and research team in any way? Maybe provide that checklist? What about short personal meeting?

**Comment by hynek-jina** [comment] 2022-05-30 11:21
I wasn't able to replicate the bug in any of described scenarios.
For the scenario with old firmware I have tested 2.3.2 and 2.1.8..

Only where it appear is when you don't have initialized device and go directly to device settings and back. But when you reconnect the device, it's again back in normal state. This seems to be very edge case to me..

https://user-images.githubusercontent.com/26002916/170981973-10ee4442-cf24-4cc1-bfae-dbe49ce97dcd.mov


QA could you please confirm that?

**Comment by sorooris** [comment] 2022-05-30 11:43
> QA could you please confirm that?

@ondracja FYI there's no one from Trezor QA tagged so just in case :wink:

**Comment by STew790** [comment] 2022-06-02 13:33
Closing, can't replicate. 

Creating new issue https://github.com/trezor/trezor-suite/issues/5543

**Closed as completed by STew790** 2022-06-02 13:33 UTC
Labels: bug, onboarding, design needed
