### ISSUE TITLE
[Wallet] Sign & Verify

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#843] opened 2019-11-28 11:29 UTC
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f363b71b411bf68115e

**Comment by ZdenekSL** [comment] 2019-12-12 11:37
How we would communicate success or failure?

**Comment by glacierbits** [comment] 2019-12-18 09:37
All possible notifications (incl. successes and failures) need to be analyzed and designed first.
WIP: https://www.notion.so/satoshilabs/1d622e7079c14f64a03fa17f50bce14f?v=7e094ac0e0524a8983133a3f07b850b2

**Comment by tsusanka** [comment] 2020-11-03 13:21
@matejzak maybe this is a duplicate of #2854?

**Comment by mroz22** [comment] 2020-11-04 10:29
it is

**Closed as completed by mroz22** 2020-11-04 10:29 UTC
