### ISSUE TITLE
Privacy / Discreet Mode doesn't provide any privacy, especially from digit counts.

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8874] opened 2023-07-08 16:33 UTC
I don't think the purpose of that feature is to hide the exact decimals of the amount, The purpose is to hide the size of the sum.

The characters are extremely obvious to count
and relatively easy to figure out the actual digits from the blur.

<img width="181" alt="image" src="https://github.com/trezor/trezor-suite/assets/48504624/151b15af-85b7-49b5-a5b8-bd490e8cb7da">

_.93974087 BTC = ... If we can read "BTC" then there's no doubt that an Ai could read even the smaller character from each individual transactions.

Someone might copy paste screenshots of his wallet thinking his privacy is protected.
The way this feature was implemented is borderline insulting.

**Comment by nostitos** [comment] 2023-07-08 16:49
For a solution that looks the same, I would replace it by the blur of a fixed length string of random the digits.

a balance of 21.38137000 would be replaced by 1.23456789 or any random string of the same length then blurred.

**Comment by komret** [comment] 2024-07-11 14:09
Closing as duplicate of https://github.com/trezor/trezor-suite/issues/10567.

**Closed as completed by komret** 2024-07-11 14:09 UTC
Labels: bug

**Comment by nostitos** [comment] 2024-07-12 17:47
wow, took you more than a year to just ACK an obvious privacy issue?
