### ISSUE TITLE
Address poisoning attack: Label zero value transactions in TX detail

### ISSUE THREAD

**Issue by Hannsek** [trezor/trezor-suite#7278] opened 2023-01-03 07:28 UTC
## Background

One type of scam is that anyone can send a transaction from any address with 0 amount without the private keys. Attackers will send the 0 amount to the address, which is almost the same as the address of e.g. Binance. The user won't realize it as the beginning and the end of these addresses look the same. User will then just copy the address from TX history and send funds to that (wrong) address.

## Proposed changes

Label zero value transactions from the TX list and detail as scammy.

## Concepts

<img width="1152" alt="image (4)" src="https://user-images.githubusercontent.com/216917/210796639-524c241f-20a2-467d-899c-1b67264e579d.png">

Tooltip and red banner to contain link to [KB article](https://trezor.io/support/a/address-poisoning-attacks)

<img width="102" alt="Screenshot 2023-01-13 at 16 51 12" src="https://user-images.githubusercontent.com/216917/212361852-00eaf2ae-3820-4450-a39c-0c62673e6ab6.png">

![image (5)(1)](https://user-images.githubusercontent.com/216917/210797121-253d3a19-672c-4074-ad88-3b8dc56e7d8e.png)

**Comment by sime** [comment] 2023-01-04 12:03
Thorough analysis of the attack: https://www.reddit.com/r/TREZOR/comments/z8msk1/comment/iyd01ha/

Key takeaway how this attack is plausible
> You might think they can not send anything from the wallet address to their scam address because they do not control the private keys of the wallet, but this is not entirely accurate. The TransferFrom method of ERC20/BEP20 tokens allows any address to send funds from any other address as long as the amount doesn’t exceed the allowance given, but in this case since the amount is 0 it doesn’t exceed the allowance which by default is 0.

**Comment by sime** [comment] 2023-01-04 13:29
Good thread on this topic: https://twitter.com/tayvano_/status/1605801004141727745

**Comment by sime** [comment] 2023-01-04 16:50
How to reproduce the attack: https://www.reddit.com/r/CryptoScams/comments/zcnj34/comment/izctwyb/

**Comment by cavigneron** [comment] 2023-01-13 11:04
@sime here are a couple of variations for the warning message bar:

- Proceed with caution. This may be a fraudulent transaction. Read more here.
- Beware! This may be a scam transaction. More here.
- Caution! Potential fraud. Review this info before continuing.

For the tool tip (ideal max length 140 characters), how about:
- Suspicious address alert! Verify before sending. Learn more about potential scam here. (86 characters)
- Address poisoning alert! This address looks suspicious. Check and confirm the address before sending. Read more about this potential scam here. (143 characters)

**Comment by sime** [comment] 2023-01-13 15:55
@cavigneron I like this:
* Proceed with caution. This may be a fraudulent transaction. [Read more here](https://trezor.io/support/a/address-poisoning-attacks).

For the tooltip I suggest:
* Address poisoning alert! This _transaction_ looks suspicious. [Learn more](https://trezor.io/support/a/address-poisoning-attacks).

**Comment by cavigneron** [comment] 2023-01-13 22:32
@sime Top dollar!

**Comment by komret** [comment] 2023-01-17 12:53
I checked the code and have some questions:
The warning is currently shown for both received and sent transactions. However, the typical form of the attack is **sending** zero amount transactions from your address. Shouldn't we limit the warning to sent transactions only? If we include received transactions, this problem is not specific to EVM tokens and seems too broad to handle this way.

We could also make the condition more specific (Ethereum and EVM-compatible blockchains only, possibly also mainnet only), what do you think @sime?

**Comment by sime** [comment] 2023-01-17 13:01
I don't have we examples handy, but the attack could go in both directions.

I agree making the logic specific for EVM chains. Please note, this should be sharable with mobile later.

**Comment by komret** [comment] 2023-01-17 13:17
The logic is sharable via `suite-common`.

My point is that if we include received transactions as well, there is nothing EVM specific, e.g. someone might attack you by sending you 0 ETH or 0 BTC. And even if we warn with every zero-value transaction, this attack can still be performed very cheaply with some dust. So we cannot cover all cases anyway and it could lead to some false positives.

**Comment by dahaca** [comment] 2023-01-18 11:11
Currently the condition for getting marked as phishy is also having _tokens_, so it wouldn't be showing up for BTC, for example. 
Also we have to bear in mind that we are speaking about the token transfer within a transaction, and they could have different types. In the scam transactions the wrapper transaction is not `receive` nor `send` since your address is not a part of it. However, the tokens transferred as a part of that transaction could be both send to and from your address.
Regardless of how this particular scam works, 0 value TXs seem suspicious anyways IMO :D

**Closed as completed** 2023-01-20 15:13 UTC
Labels: transactions, low hanging fruit

**Comment by bosomt** [comment] 2023-01-23 13:07
**QA OK**

<img width="325" alt="image" src="https://user-images.githubusercontent.com/31506317/214046994-a8cffc70-f7c3-498d-b125-5cb9f1fcb0f9.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/31506317/214047151-795ce09d-e3a1-457f-af26-73086ce4c5af.png">

**Info:**
 - Suite version: desktop 23.2.0 (4c8e4dccd95e1ab4c85bc1ad507c114e1b02fd48)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.4 Universal (revision ab65b18b07170c8a9e4f1506620af988d678453b)
 - Transport: bridge 2.0.32

**Comment by Hannsek** [comment] 2023-02-15 11:48
Shoudn't we block copying the address from the tx history? It is blurred but I can copy that… @sime
