### ISSUE TITLE
Incorrect formatting of token amount in the transaction confirmation dialog

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#3561] opened 2021-03-23 19:00 UTC
In the left column, the amount is not displayed correctly.

**Info:**
 - Suite version: web 21.3.2 (6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
 - OS: MacIntel
 - Screen: 2048x1280
 - Device: model T 2.3.5 regular

![image](https://user-images.githubusercontent.com/11609674/112202804-18e6a200-8c12-11eb-8c4d-1d3ec5dd8f97.png)

**Comment by bosomt** [comment] 2021-03-24 07:59
I was able to reproduce issue 

![image](https://user-images.githubusercontent.com/31506317/112274701-179f8e80-8c7f-11eb-9b0e-2b4d4a5701de.png)

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular

**Comment by bosomt** [comment] 2021-04-08 10:07
**QA OK**


<img width="667" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/114008778-db655400-9862-11eb-8bbc-28017bc122c5.png">



**Info:**
 - Suite version: web 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment] 2021-04-09 10:12
**QA NOK**

Looks like ETH send modal is still broken.

![image (1)](https://user-images.githubusercontent.com/31506317/114165505-dc62b800-992c-11eb-8181-4c6fe8ed39d7.png)
![image](https://user-images.githubusercontent.com/31506317/114165508-dc62b800-992c-11eb-96be-cadf35f6247a.png)


**Info:**
 - Suite version: desktop 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Comment by jerechinsky** [comment] 2021-04-09 10:26
@bosomt could you please elaborate how is it still broken? Do you mean the line break in the amount?

**Comment by bosomt** [comment] 2021-04-09 10:55
@alex-jerechinsky exactly , looks more like you are sending 5 ETH and not 1$ :), sorry i wasn't specific.

**Comment by jerechinsky** [comment] 2021-04-09 10:59
@bosomt no worries
thanks for pointing it out! 
This is already covered and tracked in #3323 so let's close this issue for now.

**Closed as completed by jerechinsky** 2021-04-09 10:59 UTC
