### ISSUE TITLE
Suite web doesn't connect with device via WebUSB on Linux

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#9500] opened 2023-09-20 06:59 UTC
**Describe the bug**
Suite web version doesn't connect to Trezor device via WebUSB on Chrome on Linux. The popup to pair the device opens and Chrome sees the device but after selecting it and clicking on "Connect" nothing happens.

**Steps to reproduce:**
1. Kill your bridge if you have standalone running.
2. Go to https://suite.trezor.io/web/
3. Connect your device
4. Click on "Find Trezor"
5. Popup opens 
6. Click on Trezor device
7. Click on "Connect"
8. Suite doesn't see the device at all and shows only the same "Find Trezor"

**Info:**
 - Suite version: web 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: 
 - Transport: WebUsbTransport

**Expected result:**
I can connect my device with Suite via WebUSB on Chrome on Linux

**Actual result:**
I can't connect my device with Suite via WebUSB on Chrome on Linux

**Comment by mroz22** [comment] 2023-09-20 08:29
This happens only on linux? mac/win not affected?

**Comment by STew790** [comment] 2023-09-20 08:42
Yes, Windows and Mac works just fine.

**Comment by mroz22** [comment] 2023-10-02 13:57
is this still issue? didn't restarting everything help?

**Comment by bosomt** [comment] 2024-02-02 11:45
**QA NOK**

Installed latest Ubuntu and latest Chrome
Chrome sees device and pairs it but Trezor Suite does not see device 

 - Suite version: web 24.1.3 (240373658ecb4b9ea1e6b09e06e657722ae6c2f1)

**Comment by mroz22** [comment] 2024-02-02 12:02
assigning this to @karliatto who runs on ubuntu. not the highest priority but when you have time, please check on it and post here your finding 🙏 
- my tip is that on connect event in usbApi is not fired on linux? 
- maybe this is the reason why enumeration used to run in a loop before big transport refactor related to nodeusb?
- but it was all tested after the nodeusb refactor right??

**Comment by karliatto** [comment] 2024-02-02 14:18
> assigning this to @karliatto who runs on ubuntu. not the highest priority but when you have time, please check on it and post here your finding 🙏


Just tested https://suite.trezor.io/web/ with Trezor Model One on Chrome Version 120.0.6099.216 (Official Build) (64-bit) running on PoPOS (builds on top of ubuntu) and it all works as expected.
I did not have latest firmware so I installed latest one and it keeps working as expected.

**Comment by mroz22** [comment] 2024-02-03 09:35
@karliatto did you test pairing after resetting browser usb permissions

**Comment by karliatto** [comment] 2024-02-05 08:29
> @karliatto did you test pairing after resetting browser usb permissions

Sure, I tried to break it in multiple ways, but it was working quite well. 
@bosomt @STew790 maybe I can have a call with one of you to see what is happening. Today?

**Comment by bosomt** [comment] 2024-02-05 10:21
**QA OK**


retested on different computer 

- Chromium have not seen device at all , but webUSB dialogue was present in browser
- Chrome , latest download `Chrome Version 121.0.6167.139 (Official Build) (64-bit)` worked as expected 
- KUbuntu 22.04

**Comment by karliatto** [comment] 2024-02-05 12:32
After conversation with @STew790 I think we have found the intriguing reason, and I can reproduce the issue in Ubuntu with Google Chrome and Chromium.
I think the issue is related to the way WebUSB behaves in Google Chrome depending on the way you install it in your OS.

Basically if Google Chrome is installed System installation (using .deb) or with snap it works smoothly. But if it is installed using Flatpack then there is a reproducible issue in the scenario bellow:

1. Make sure you have Trezor disconnected from computer and bridge is not running.
2. Open Google Chrome installed using Flatpack
3. Go to https://suite.trezor.io/web/
4. Once https://suite.trezor.io/web/ is loaded connect Trezor device to the computer
5. Suite is not able to find the device
6. Close the browser and open it again while having Trezor device connected to the computer
7. Suite can find the device with no problem


In my experimentation this issue is only if Google Chrome was installed using Flatpack otherwise it works seamless.

@mroz22 I am afraid there is nothing we can do about it. But know about it. Maybe write it in some documentation.

**Comment by karliatto** [comment] 2024-02-05 12:44
I propose to add "Method Installation Method" in the GitHub Issue Template as a way to remind us that this can make a difference, and be helpful in debugging.

I created pull request: https://github.com/trezor/trezor-suite/pull/11036

**Comment by mroz22** [comment] 2024-02-05 12:44
hmm at least we need to note it somewhere, maybe even some debugging tooltips in UI ? cc @Hannsek

**Comment by Hannsek** [comment] 2024-02-05 19:38
What exactly do you have in mind?

**Comment by karliatto** [comment] 2024-03-12 08:12
I think this issue could be closed, we have at least this mitigation https://github.com/trezor/trezor-suite/pull/11036

**Closed as completed by karliatto** 2024-03-12 08:12 UTC
Labels: bug, connect, Linux
