### ISSUE TITLE
Token more info not properly rendered when more tokens in token list 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#14605] opened 2024-09-29 06:43 UTC
**Describe the bug**
Token more info not properly rendered when more tokens in token list.
Plus when scrolling is available it wont help

**Steps to reproduce:**
1. Load account with multiple tokens
2. Navigate to token section
3. Try to show more info via ... of token thats in bottom

**Info:**
 - Suite version: desktop 24.10.0 (03347b5e28587e194525d937b7943bc9836db435)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision ab96ce7954c7db384b26bc863d8752150027adbf)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/d6247276-d15c-42c5-9fea-1e8bb2151a70">

https://github.com/user-attachments/assets/f23b02cf-c5f4-4686-a3b1-87da5ddb25ca

**Comment by tomasklim** [comment] 2024-11-24 14:02
Duplicate of https://github.com/trezor/trezor-suite/issues/12939

**Closed as completed by tomasklim** 2024-11-24 14:02 UTC
