### ISSUE TITLE
SENSO token wrong amount in the application

### ISSUE THREAD

**Issue by Ariloum** [trezor/trezor-suite#8030] opened 2023-04-06 21:14 UTC
**Describe the bug**
SENSO token balance amount shows as "0.00000000000001 SENSO" but real etherscan amount is 10000.

**Info:**
-   Remembered Wallet: yes
-   Suite Version: windows app, 23.3.2
-   Browser: -
-   OS: Windows 10 Pro
-   Bridge: -
-   Firmware Version: Trezor model T, 2.5.3

**How to reproduce**

1. Send any amount of ERC20 SENSO token to the Trezor Ethereum wallet
2. Click on ethereum tokens balance
3. Here you can see wrong token amount 

**Expected behavior**
Amount must match to real one shows on the etherscan

**Screenshots**
Screenshot shows how 10000 looks like in the Trezor Suite:
![2023-04-07 00_11_27-Trezor Suite](https://user-images.githubusercontent.com/6816952/230494897-3fb44874-9341-403b-a6ca-0b22f88c50a9.jpg)

**Additional context**

**Comment by tomasklim** [comment] 2023-04-07 20:14
Blockbook issue @martinboehm 

Same tx on etherscan and blockbook
https://etherscan.io/tx/0xa7b635ff1f823fa3a99ac2353a14bfc523ce6b690b9743992757346ad8c9def9
https://eth1.trezor.io/tx/0xa7b635ff1f823fa3a99ac2353a14bfc523ce6b690b9743992757346ad8c9def9

According to blockbook, `decimals` = 18 https://eth1.trezor.io/api/v2/address/0xC19B6A4Ac7C7Cc24459F08984Bbd09664af17bD1
Acording to ethscan `decimals` = 0
<img width="464" alt="Screenshot 2023-04-07 at 22 13 34" src="https://user-images.githubusercontent.com/33235762/230672952-01c95fae-c043-41db-baba-f3d7add3a79c.png">

**Comment by tomasklim** [comment] 2024-01-23 13:44
@martinboehm We think that it's an issue in Blockbook. This token has 0 decimals, so I guess it is a bug caused by using `!` with token decimals and then using default value `18`

**Comment by martinboehm** [comment] 2024-01-24 12:25
@tomasklim yes, it is reported incorrectly by Blockbook because the contract self describes itself incorrectly (probably does not implement the get decimals method and Blockbook then defaults to 18). I will have to implement manual correction of contract metadata.

**Comment by tomasklim** [comment] 2024-01-24 13:16
Closing as issue was moved to Blockbook

**Closed as completed by tomasklim** 2024-01-24 13:16 UTC
Labels: bug, EVM
