### ISSUE TITLE
Suite transaction signing flow is not aligned with new FW for model T

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7948] opened 2023-03-29 11:47 UTC
_Discovered by @marekrjpolak_ 👏 

**Describe the bug**
Address and amount validation was splited into two steps on Trezor device. 
So when you confirm first address Suite moves pointer on second address (or fee) but Trezor is showing Amount of the first output.

**Steps to reproduce:**
1. Use model T and download new (unreleased) firmware (version > 2.5.3) 
2. Prepare transaction and click on `Review & Send`

**Info:**
 - Suite version: desktop 23.4.0 (ba456167fc70626d92a4d36a3bf2725033b955ea)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 924452272164333575b9e744ae7dae0cacc2d906)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**
| Trezor | Suite |
| --- | --- |
| ![Screenshot 2023-03-29 at 12 44 29](https://user-images.githubusercontent.com/26002916/228525503-c182705a-422b-415e-b90f-bcb00f826646.png) | ![Screenshot 2023-03-29 at 12 38 01](https://user-images.githubusercontent.com/26002916/228524632-fe2253f2-b30e-4144-9d72-4b46ad3dd0ff.png) |
| ![Screenshot 2023-03-29 at 12 44 09](https://user-images.githubusercontent.com/26002916/228525798-7b89b255-6721-49c8-b0b5-666d12d612cf.png) | ![Screenshot 2023-03-29 at 12 39 58](https://user-images.githubusercontent.com/26002916/228524675-828998b8-897d-4196-abb1-3e7734af182d.png) |

**For QA from Hannsek:**
Suite transaction signing flow steps should be aligned with the screens that user see on the Trezor. So when user approving address on Trezor, he should see that he is approving address. 
![image](https://user-images.githubusercontent.com/57008159/230362362-b96dff11-ed4f-4a02-88b8-3f16176f1ef2.png)
<img width="241" alt="image" src="https://user-images.githubusercontent.com/57008159/230362424-d0fef1d1-ab07-4a01-80a2-7ae7d395b241.png">

The wording is not exactly the same now, but the meaning is the same. There can be some misalignment in altcoin sending flow as it is a mess in fw right now.

_Examples_: 

ETH flow: 
![image](https://user-images.githubusercontent.com/57008159/230362846-3da4009f-2584-4610-82de-451ad2335e78.png)
BTC flow: 
![image](https://user-images.githubusercontent.com/57008159/230363008-2b52e556-1ae4-4ffd-b84b-8fea04c1d0b9.png)
BTC flow with locktime: 
![image](https://user-images.githubusercontent.com/57008159/230364939-63452f4b-08a9-4818-89ca-23ced9afaec7.png)

**Comment by Hannsek** [comment] 2023-03-29 11:50
Nice catch. @sime 

The screens are as follows: 
<img width="185" alt="image" src="https://user-images.githubusercontent.com/57008159/228528759-7d1970f3-74fa-417c-821d-1bccd7575078.png">
Address -> ammount -> (Address 2 -> ammount 2) -> Total ammount including fee

**Comment by sime** [comment] 2023-03-29 12:11
@matejkriz Can we have unique flows per device _and_ FW version?

**Comment by matejkriz** [comment] 2023-03-29 13:05
> @matejkriz Can we have unique flows per device _and_ FW version?

Sure we can

**Comment by matejkriz** [comment] 2023-03-31 09:14
@Hannsek It's not only about BTC signing flow, right? ETH flow has changed too? Any others?

**Comment by Hannsek** [comment] 2023-03-31 09:19
It is this pr: https://github.com/trezor/trezor-firmware/pull/2925/files#. @mmilata will know better than I but I think there is something off in altcoins flow.

**Comment by marekrjpolak** [comment] 2023-03-31 09:19
I'm especially interested in Cardano signing flow as currently, only `ButtonRequest_Other` is ever fired there so review modal implementation is kinda hacky for that case.

**Comment by mmilata** [comment] 2023-03-31 10:39
Yes, the new design has "confirm output" split into two screens, each of which currently sends a `ButtonRequest.ConfirmOutput`. I can change the FW so that it only sends ButtonRequest when it shows the _recipient_ screen but not when it shows the _amount_ screen if it helps.

However there is no longer separate screen for _fee_, it's all on the _total_ screen, not sure what to do about this one.

**Comment by dahaca** [comment] 2023-03-31 12:29
@mmilata I see that for BTC the flow is oddly that:

* To _(ButtonRequest_ConfirmOutput)_
* Amount _(ButtonRequest_ConfirmOutput)_
* Fee _(ButtonRequest_SignTx)_
* Total  _(ButtonRequest_SignTx)_

The fee being `ButtonRequest_SignTx` does not seem right, only Total should always be `ButtonRequest_SignTx`, no?

On ETH I'm getting:

 * To _(ButtonRequest_SignTx)_
* Amount _(ButtonRequest_SignTx)_
* Gas _(ButtonRequest_SignTx)_
* Max Fee _(ButtonRequest_SignTx)_
* Amount sent _(ButtonRequest_SignTx)_

Which is counter-intuitive 🤔  Also why have different "last step" naming? `Total` vs `Amount sent` 😅 

**However**, that's not relater to this issue, since the steps logic is not based on even types. Just an observation I had.

**Comment by mmilata** [comment] 2023-03-31 13:03
For BTC the Fee and Total screens will be combined into one after trezor/trezor-firmware#2925 is merged.

I don't know what's the reasoning behind the ETH ButtonRequests (perhaps it's not using ConfirmOutput because technically Ethereum doesn't have outputs?), but we can change them as you need, just let us know or open an issue.

**Comment by mmilata** [comment] 2023-03-31 13:08
FWIW there used to be an effort to make ButtonRequests more useful to Suite trezor/trezor-firmware#35, we might want to restart that eventually.

**Comment by dahaca** [comment] 2023-03-31 13:31
@mmilata any changes to other networks which are about to get merged?

**Comment by dahaca** [comment] 2023-03-31 14:45
@Hannsek Should I split up the BTC addresses in groups of 4 in the modal as well? Would be easier to compare with what's on a  device.

**Comment by dahaca** [comment] 2023-03-31 15:07
@mmilata @Hannsek  Is the `Address -> Amount -> Total + Fee` true for all networks except for ETH?

edit: oh, it's not actually implemented in the FW it seems... 😅

**Comment by mmilata** [comment] 2023-03-31 15:54
Combining the _total_ and _fee_ screens in https://github.com/trezor/trezor-firmware/pull/2925 affects Bitcoin, Cardano (uses ButtonRequest.Other for some reason), Ethereum, and Tezos.

I think they are on the same screen in the currently released firmware so there won't have to be changes in that logic?

**Comment by dahaca** [comment] 2023-03-31 15:58
@mmilata Also noticed that Cardano has 1 more screen with  `Choose level of details` which seems to do nothing but puts one more `ButtonRequest_Other`, complicating tracking steps.

**Comment by dahaca** [comment] 2023-03-31 16:03
Ripple needs adjustment as well, Suite mixes up total sent _(w/o fee)_ and amount but yeah, it does not combine fee and total screens. Any reasons why? Seems odd to create a separate case for XRP... @Hannsek

**Comment by Hannsek** [comment] 2023-03-31 18:04
> @Hannsek Should I split up the BTC addresses in groups of 4 in the modal as well? Would be easier to compare with what's on a device.

Not now. The time for this will come.



> Ripple needs adjustment as well, Suite mixes up total sent _(w/o fee)_ and amount but yeah, it does not combine fee and total screens. Any reasons why? Seems odd to create a separate case for XRP... @Hannsek

Don’t know. @mmilata @matejcik any hints?

**Comment by matejcik** [comment] 2023-04-01 09:05
> I'm especially interested in Cardano signing flow as currently, only `ButtonRequest_Other` is ever fired there so review modal implementation is kinda hacky for that case.

that's what the "new buttonrequests" thing is all about basically, so maybe let's push that through? 


> > Ripple needs adjustment as well, Suite mixes up total sent _(w/o fee)_ and amount but yeah, it does not combine fee and total screens. Any reasons why? Seems odd to create a separate case for XRP... @Hannsek
> 
> Don’t know. @mmilata @matejcik any hints?

altcoins are a mess, see https://github.com/trezor/trezor-firmware/issues/2712
we can modify (most) altcoins to show total+fee, or fee -> total, or whichever, just need a tracking issue for it

**Comment by dahaca** [comment] 2023-04-03 14:33
@matejcik @Hannsek  For this issue, unifying the last step for all would be great! And afaik, it's different only for `XRP`. Idk how long it would take to change it but it would be great if we are able to make a smooth transition of the send flow for 2.6.0 without any unnecessary magick :D

**Comment by matejcik** [comment] 2023-04-03 15:06
if it's only XRP (out of Suite supported coins), we can probably do it

**Comment by mmilata** [comment] 2023-04-03 15:51
Like this? First two send ButtonRequest.ConfirmOutput, last one ButtonRequest.SignTx.

![Screenshot 2023-04-03 at 17-48-50 TT-device_tests-ripple-test_sign_tx py test_ripple_sign_simple_tx](https://user-images.githubusercontent.com/85857/229562132-deb84e77-37eb-4b6d-a037-6a1cbb11a44d.png)

**Closed as completed** 2023-04-06 13:57 UTC
Labels: bug

**Comment by bosomt** [comment] 2023-04-09 14:53
See difference in tx signing between new and old UI. Tested on last dev master of Trezor Suite
First screenshot is new UI FW and Suite reports `Confirmed` in top of modal before tx is actually signed.
So you will end up with Suite saying confirmed and gray `Send` button and device asking you to `Hold to confirm`

**2.6.0**
<img width="556" alt="Screenshot 2023-04-08 at 10 39 01" src="https://user-images.githubusercontent.com/31506317/230712280-8d13a743-3235-412e-acf7-2beec3616ef9.png">

**2.4.3**
<img width="542" alt="Screenshot 2023-04-08 at 10 38 14" src="https://user-images.githubusercontent.com/31506317/230712282-f1771ddc-bbb5-4e81-bd46-b82c2fe94bb4.png">



**Info:**
 - Suite version: web 23.5.0 (0f6b428936d1ab6efe14e9e2fb2cb4d402bfdc67)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.6.0 Universal (revision 6e0c2578f8932c94413b2d1564725dc687eceaf7)
 - Transport: BridgeTransport 2.0.32

**Comment by STew790** [comment] 2023-04-14 13:42
**QA OK**
Everything seems fine. Tested together with some other issues on multiple coins. The exception is this https://github.com/trezor/trezor-suite/issues/8099 but this has separate issue and will be fixed in next RC.

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32
