### ISSUE TITLE
Trezor Suite does not apply labelling correctly when switching to standard wallet

### ISSUE THREAD

**Issue by ghost** [trezor/trezor-suite#3207] opened 2020-12-23 08:34 UTC
**Describe the bug**
After switching from a passphrase protected wallet to the standard wallet (empty passphrase) labels are not applied within the standard wallet.

**Info:**
 - Suite Version: 20.12.1
 - OS: Ubuntu 20.10

**Steps to reproduce:**
This only happens if you open with the standard wallet first: 
1. open standard wallet (no passphrase) and confirm "enable labeling"
2. switch to passphrase protected wallet and again confirm "enable labeling"
3. switch back to standard wallet -> labels are gone

**Expected result:**
Labels should still be applied.

**Actual result:**
Default labels are shown instead, e.g. acccount "Bitcoin #1", etc. instead of custom labels.

**Note(s):**
Not sure if suite should ask again to enable labeling when switching back to standard wallet? Suite does not ask a second time to enable labeling when switching back to standard wallet.

**Comment by prusnak** [comment] 2020-12-23 10:01
Labeling of accounts is not implemented in the old wallet and we don't plan to add it.

Can you confirm the labeling of transactions works and this issue is only about the missing account labels in the old wallet?

**Comment by ghost** [comment] 2020-12-23 11:14
Do you mean "wallet" and "beta wallet" when you say old wallet?

Not sure if I understand your question correctly. I am only testing within Trezor Suite in latest version:

- When I open the standard wallet (= wallet with empty passphrase) in Trezor Suite accounts are labelled (Trezor T asks "enable labelling").
- Same when switching to a passphrase protected wallet from the standard wallet. Trezor T asks "enable labelling" and account labels are shown.
- Only when I switch back to standard wallet (empty passphrase) from the previously opened passphrase protected wallet the labels are not shown anymore in standard wallet.

Does this info make sense to you?

**Comment by prusnak** [comment] 2020-12-23 11:29
Ah, sorry. I thought you mean "wallet.trezor.io" by saying standard wallet.

Your bugreport makes sense, thanks!

**Comment by ghost** [comment] 2020-12-23 11:45
Great! And no worries... I am amazed to get such a swift response during Christmas time at all. Awesome work - thank you!

**Comment by bosomt** [comment] 2020-12-30 14:32
I was able to reproduce this issue with 20.12.1 Win10 app public version.

**Info:**

OS: Windows 10 current version
Suite: 20.12.1 be4e3a36f7dbe15b2b203f66de11edc50a6665b8
Device regular-1.9.4-889a3699

**Steps to reproduce:**

1) delete local config data
2) load standard wallet, 
3) enable labeling and choose local storage
4) rename account #1
5) add hidden wallet and rename account #1 
6) go back to standard wallet, label from standard wallet is gone

This only happens first time, when you create label for second time it won't  disappear.

**Comment by mroz22** [comment] 2021-01-04 08:50
@bosomt could you please try it again on this build? https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/941473423
It is from another branch that makes some changes to labeling and I wasn't able to reproduce it there. 
PS. you may also trigger build for another platforms of your choice if you are logged into gitlab

**Comment by bosomt** [comment] 2021-01-04 10:21
@mroz22 i was not able to reproduce it with

- Suite version: desktop 21.1.0 (8a5b32aa0a0f4e74ea7090f2561025be1b68a589)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

I recommend to test it properly during 21.1.1 release test.
Should we close it and move it to merged /so we won't forget to test it with another OS and final suite version ? /

**Comment by mroz22** [comment] 2021-01-05 10:46
thanks! definitely keep an eye on testing metadata related things for regression before the release as there will be some refactoring changes. I am putting this issue into the January 13th project so that it won't slip through.

**Closed as completed** 2021-01-11 11:19 UTC
Labels: bug

**Comment by bosomt** [comment] 2021-01-19 15:56
**QA OK**

**Info:**
 - Suite version: desktop 21.1.0 (9ae82af375cea195a84fec664b387c461b2df1ae)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
