### ISSUE TITLE
Can't close Trezor Suite with Tor On and Solana account active

### ISSUE THREAD

**Issue by evgenysl** [trezor/trezor-suite#12628] opened 2024-05-29 07:39 UTC
**Describe the bug**
If Solana account is activated and Tor is on, I can't close Trezor Suite.

Happens both on 24.5.2.and 24.5.3. and only on Arm Mac
Not reproducible on Linux and Windows yet.

**Steps to reproduce:**
1. Activate Solana account
2. Turn on Tor
3. Close the app
4. Observe app is not closing and in Activity Monitor it's not responding

**Info:**
 - Suite version: desktop 24.5.3 (0ff3e0bd75d90719b7b36a60b3eab1c2bd3d3491)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
App closes

**Screenshots:**
![Screenshot 2024-05-29 at 08 43 41](https://github.com/trezor/trezor-suite/assets/63164324/b01d0501-9bcc-457b-a527-bacc7cba0211)

**Note(s):**
related to https://github.com/trezor/trezor-suite/issues/12626 ?

**Comment by bosomt** [comment] 2024-05-29 08:00
Managed to reproduce it on my machine by quiting app during discovery with tor on

<img width="457" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/efe9bc72-1bb5-4e22-b187-64146e8d961e">

**Info:**
 - Suite version: desktop 24.5.3 (0ff3e0bd75d90719b7b36a60b3eab1c2bd3d3491)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.3 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment] 2024-08-08 09:35
@trezor/qa this still happening?

**Comment by bosomt** [comment] 2024-08-08 12:18
**QA NOK**

still happening :(

**Info:**
 - Suite version: desktop 24.8.1 (b8c7e5e6835b67eeef75fecb037ef79de194c608)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.8.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Comment by enjojoy** [comment] 2024-10-31 11:36
I tried multiple times with solana activated and tor on but it never got to the Not Responding state. Can you please try replicating it again? @evgenysl @bosomt

**Comment by evgenysl** [comment] 2024-10-31 12:10
Suite 24.10.1

- Empty wallet - no issues
- Funded wallet - Suite takes longer time (about 50sec) to close and app is in _Not Responding_ state

Mouse pointer is actually MacOS loading spinner the whole time (not captured on video).


https://github.com/user-attachments/assets/fb744e05-f01f-48e1-bfe7-82c27add42ef

**Comment by enjojoy** [comment] 2024-10-31 15:18
> Suite 24.10.1
> 
> * Empty wallet - no issues
> * Funded wallet - Suite takes longer time (about 50sec) to close and app is in _Not Responding_ state
> 
> Mouse pointer is actually MacOS loading spinner the whole time (not captured on video).
> 
>  Screen.Recording.2024-10-31.at.13.02.28.mov

Not sure what to do because I can't get this behavior on my M3

**Comment by enjojoy** [comment] 2024-11-04 06:20
<img width="554" alt="image" src="https://github.com/user-attachments/assets/086d205c-8ecb-4cd5-9621-3cbe6b641fec">
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/98e51b07-9bb3-47d4-b938-a5b7e28f4ac4">

**Comment by enjojoy** [comment] 2024-11-04 06:28
Related issue 

https://github.com/solana-labs/solana-web3.js/issues/2288

https://solana.stackexchange.com/questions/15171/how-to-handle-connection-failures-with-onlogs

**Comment by marekrjpolak** [comment] 2024-11-04 15:23
@enjojoy the problem is in [this part](https://github.com/solana-labs/solana-web3.js/blob/e3459377d3cef03d6e2570119dd45ce38fc8476b/src/connection.ts#L6306-L6321) of `@solana/web3.js` and [this line](https://github.com/trezor/trezor-suite/blob/develop/packages/blockchain-link/src/workers/solana/index.ts#L584) of Suite:

When Tor process is killed (in a pretty uninteresting manner I'd say) and Suite tries to unsubscribe Solana accs, the library function `isCurrentConnectionStillActive()` incorrectly returns true so the unsubscription is repeated in a neverending loop.

Preferred solution would be to fix the library (e.g. implement [this todo](https://github.com/solana-labs/solana-web3.js/blob/e3459377d3cef03d6e2570119dd45ce38fc8476b/src/connection.ts#L6316) or get the connection status from underlying socket's `readyState`). From our side, the only solution I see is not to unsubscribe the accounts on disconnect. :man_shrugging:

**Comment by enjojoy** [comment] 2024-11-19 07:44
For now, I will create a patch to temporarily fix the issue on our side, until it's fixed in the library

**Comment by martykan** [comment] 2024-11-19 09:16
Also related https://github.com/solana-labs/solana-web3.js/issues/3053

**Comment by steveluscher** [comment] 2024-11-20 07:39
Hello friends! I maintain `@solana/web3.js`. Will you accept a PR to upgrade to version 2.0 of our library? It simply does not have any of these problems, but it is a completely new API that will require a rewrite. I can _probably_ throw it together in less than a day, if you are amenable.

**Closed as completed** 2024-11-29 08:51 UTC
Labels: bug, solana

**Comment by bosomt** [comment] 2024-12-02 10:06
**QA OK**

TOR + SOLANA enabled and discovered
- tried to quit app with remember wallet on ✅ 
- tried to quit app with remember wallet off ✅ 
 

**Info:**
 - Suite version: desktop 24.12.0 (16cbfef4d484a16875027b80e99d07577eb09626)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.12.0 Chrome/130.0.6723.91 Electron/33.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 688bddc887b8bb660640cc6e40a99036f2e87f1f)
 - Transport: BridgeTransport 2.0.33
