### ISSUE TITLE
Cancelled bump fee modal creates send draft

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13325] opened 2024-07-14 18:59 UTC
**Describe the bug**
When I cancel bump fee tx review modal and I navigate to send form, it is partially filled and symbol is missing. I would not expect filled form at all!

If the tx is mined with old fee and user will want to send another tx in send form, it will not work as it adds also rbf params

**Info:**

-   Suite Version: 24.7.1

**How to reproduce**
1. Send tx with low gas price
1. Bump fee
2. Cancel it in review tx modal
3. Navigate to send form

**Screenshots**
![Screenshot 2024-07-14 at 20 55 33](https://github.com/user-attachments/assets/aa4ec2a6-de2a-4ae7-a9e2-30e0c820b8bc)

**Comment by MiroslavProchazka** [comment] 2024-07-15 11:50
cc @peter-sanderson will this be fixed by Full rbf?

**Comment by peter-sanderson** [comment] 2024-07-22 11:44
I was able to somehow reproduce on testnet on current `develop`.

1. create TX with 1sat/byte
2. make sure the Send form is cleared (I clicked `Clear all` and refreshed whole Suite)
3. click `Bump fee` button in transaction list
4. change see to 1sat/byte
5. click `Replace transaction` button in dialog
6. Cancel the confirmation dialog (the one that wants you to sing on Trezor)
7. Click `Send` button on top-right corner
8. **The send form is filled with data** <--- wrong :question: 

![image](https://github.com/user-attachments/assets/32e181e2-9646-409d-9715-d39548c30c43)

**Comment by MiroslavProchazka** [comment] 2024-07-31 09:14
Looks like that this is more of a issue in the send form, closing for now.

**Comment by komret** [comment] 2024-08-09 21:02
This is caused by https://github.com/trezor/trezor-suite/pull/12378/commits/8631fdad6f0ff9b63ec6bb40753b707328e344bf. It turns out `precomposedForm` wasn't entirely redundant. It allowed to store some fields without overriding the draft. Any chance you could put it back, @PeKne?

**Comment by PeKne** [comment] 2024-08-12 10:22
> This is caused by [8631fda](https://github.com/trezor/trezor-suite/commit/8631fdad6f0ff9b63ec6bb40753b707328e344bf). It turns out `precomposedForm` wasn't entirely redundant. It allowed to store some fields without overriding the draft. Any chance you could put it back, @PeKne?

Sure, if it is truly needed, we can put it back. But let's find some better solution. The original was very messy and confusing.

**Comment by bosomt** [comment] 2024-08-30 05:57
**QA OK**

- send draft is still created /expected/
- draft cant be reused if you want send same amount to same account it generates `Transaction signing error: ALREADY_EXISTS: already known`
- bumping of tx works as expected

**Info:**
 - Suite version: web 24.9.0 (c63f73cc9cb1c714b31ed58c29500b0500c87725)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.2 regular (revision 9e18e72a2c7896cbcce1df4c2d908eab0f01564f)
 - Transport: BridgeTransport 2.0.33

**Comment by komret** [comment] 2024-10-29 12:25
@bosomt, I accidentally closed this issue, creating a send form draft by opening RBF form is not expected.

I suspect this bug is somehow related to https://github.com/orgs/trezor/projects/58?pane=issue&itemId=82436895&issue=trezor%7Ctrezor-suite%7C14753

**Closed as completed** 2024-11-18 12:07 UTC
Labels: bug
