### ISSUE TITLE
After closing Suite window on Linux, trezor-suite, trezord and bindmount are not closed

### ISSUE THREAD

**Issue by hiviah** [trezor/trezor-suite#4904] opened 2022-02-07 20:34 UTC
**Describe the bug**
After closing Suite window, `trezor-suite`, `trezord` processes and tmpfs bindmount are not closed.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Trezor-Suite-22.1.1-linux-x86_64.AppImage
 - Browser: used the AppImage version
 - OS: Ubuntu 20.04 LTS with KDE/Plasma desktop environment
 - Bridge: bundled
 - Firmware Version: 2.4.3 TT
 - Used Tor bridge that comes from torproject.org PPA (preinstalled)

**How to reproduce**
1. Open Suite
2. Click on an account, wait them to load
3. Exit Suite by closing window
4. Processes `trezor-suite`, `trezord` processes and tmpfs bindmount are not closed.

**Expected behavior**
Processes and tmpfs bindmount should be closed. I don't see any tray icon or anything, google doesn't think there is tray icon implemented, so I guess processes and mount along with bridge should've been closed.

**Additional context**

These processes remain after closing of suite.

```
 145504 ?        Ssl    0:01  \_ ./Trezor-Suite-22.1.1-linux-x86_64.AppImage
 145508 pts/22   S      0:00  \_ /tmp/.mount_TrezorPCzAze/trezor-suite --type=zygote --no-zygote-sandbox
 145509 pts/22   S      0:00  \_ /tmp/.mount_TrezorPCzAze/trezor-suite --type=zygote
 145512 pts/22   S      0:00  |   \_ /tmp/.mount_TrezorPCzAze/trezor-suite --type=zygote
 145579 pts/22   Sl     0:11  \_ /tmp/.mount_TrezorPCzAze/resources/bin/bridge/trezord

```

**Comment by prusnak** [comment] 2022-02-07 22:23
> 3. Exit Suite by closing window

How are you closing the window? Clicking on X button or using a keyboard shortcut?

------

This particular code (which should quit the app when all windows have been closed on `platforms != darwin`) hasn't been touched for quite a while:

https://github.com/trezor/trezor-suite/blob/ff71cc624ae923bc7c6cc561c22ce9d940f51978/packages/suite-desktop/src-electron/modules/window-controls.ts#L34-L38

**Comment by hiviah** [comment] 2022-02-07 22:29
Clicking 'X' on window.

**Comment by STew790** [comment] 2022-02-10 11:27
We (@trezor/qa ) were all able to reproduce this, unfortunately. 

The steps are the same as @hiviah mentioned. Both on Linux Ubuntu and MacOS.

**Screenshots**

Linux
![image](https://user-images.githubusercontent.com/48477147/153398994-e1cfffca-d0cc-42d4-a863-4e8030f66eb3.png)


**Info**
- Suite version: desktop 22.2.1 (520802b8052d558de9c5f0ee55f9151ea5122eb4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular

**Comment by wendys-cats** [comment] 2022-02-10 15:15
Reproduced this on mac (intel), tried with autoupdates and/or installing over last three (21.12.2, 22.1.1, 22.2.1-beta) versions available [here](https://github.com/trezor/trezor-suite/releases).

Looks like version 22.1.1 is the culprit, trezord.service stays alive after eixiting Suite, and will persist even after autoupdate or installing another version over this one. Quitting the service via activity monitor solves nothing. 

Version 22.1.1 always leaves trezord alive after exiting Suite. Version 21.12.2 does not do this. Neither does 22.2.1-beta.
Happens with autoupdate from 22.1.1 to EA 22.2.1-beta. Also tried installing 21.12.2 over 21.1.1 and it's the same, trezord from 21.1.1 stays alive. Quitting the service via activity monitor or restarting mac kills the persisting service and it does not longer stay alive after exiting Suite.

**Comment by hiviah** [comment] 2022-02-12 00:11
Seems that if you kill just `trezord` process, the rest cleans up (so no dangling processes, on Linux at least).

**Closed as completed** 2022-02-14 11:32 UTC
Labels: bug

**Comment by bosomt** [comment] 2022-02-15 13:59
**QA OK**

**Info:**
 - Suite version: desktop 22.2.2 (b07f353c6f405d70d4f53ef5a1d4345f9d7fc4b9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.2.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular
