### ISSUE TITLE
App crashes when discovery is in progress ETH or token account is entered

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10094] opened 2023-11-28 11:44 UTC
Steps to reproduce:
Open the app
Connect&Unlock the device which has some ETH and ERC20 token
Access the Token account detail or ETH account detail while discovery is still in progress
App turns white and then crashes

Look at the video: https://drive.google.com/file/d/1jgdlEXZbtPRpZRK6fo_bGZkxtszMv752/view?usp=sharing

**Comment by PeKne** [comment] 2023-11-30 13:07
Fixed by changes in #10124

**Comment by STew790** [comment] 2023-12-01 06:53
**QA OK**
App is no longer crashing when going to ETH or ERC20 tokens while discovery is happening.
23.11.1(602)

**Comment by juriczech** [comment] 2023-12-05 08:46
@STew790 @bosomt Can we please ask for retest? This seems to happen from time to time, not sure whether it's related to ETH or not. @PeKne just told me this happened to him few days ago but now cannot be replicated. No need to spend too much time on it, just bear this in mind while testing other issues and if app crashes during discovery, please report it here 🙏

Since we're going to do internal release, we will have a lot of testers as well so I will reopen this issue and if no occurences will be found within a week, we can close this.

**Comment by bosomt** [comment] 2023-12-05 09:10
I was not able to reproduce issue with 7 /5 from device and 2 imported/ accounts, including ERC20 tokens.
But i will continuously try to replicate it during overall testing

**Comment by STew790** [comment] 2023-12-28 13:23
Unfortunately, the app just crashed for me when I was testing this https://github.com/trezor/trezor-suite/issues/10166 
Nonetheless, I was trying to reproduce it but I wasn't successful...It happened just randomly when trying to get the receiving address of ETH account and the discovery was still going (not 100% sure about this though) on but I just couldn't reproduce it after.

Develop 23.12.2 (656) https://github.com/trezor/trezor-suite/commit/19c6638a3225f0c321d88fc6b36b8da18a0bc079

**Comment by bosomt** [comment] 2024-01-12 15:51
**QA OK**

i was not able to reproduce issue for some time

 24.01.1 (682)
be06d91 - [develop] - fix(suite-native): correct error for firmwareless device (#10635)

**Closed as completed by bosomt** 2024-01-12 15:51 UTC
Labels: bug, mobile
