### ISSUE TITLE
Suite-Desktop: Add logging

### ISSUE THREAD

**Issue by keraf** [trezor/trezor-suite#3248] opened 2021-01-08 18:21 UTC
Add extensive logging to Suite-Desktop with various log levels (info, warn, error, etc...). Launch parameter should be able to determine the level of logging required. Disabled by default.

**Comment by sorooris** [comment] 2021-01-20 15:45
**QA NOK**

Adding a runtime flag `--log-write` when launching Suite from command line results in an error, details below.

Suite: app 21.1.0 e31cc2b
OS: Win10 19042.746
Device: model T 2.3.4 50854b921

Details:
```
C:\Users\Seb>
2021-01-20T15:26:06.281Z - ERROR(exception): EISDIR: illegal operation on a directory, open 'C:\Users\Seb\AppData\Roaming\@trezor\suite-desktop\Trezor Suite\logs'
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at WriteStream.Writable.write (_stream_writable.js:318:11)
    at R.write (C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite\resources\app.asar\dist\app.js:1:3199)
    at C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite\resources\app.asar\dist\app.js:1:3011
    at Array.forEach (<anonymous>)
    at R.log (C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite\resources\app.asar\dist\app.js:1:2995)
    at R.error (C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite\resources\app.asar\dist\app.js:2:553)
    at process.<anonymous> (C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite\resources\app.asar\dist\modules\event-logging\process.js:1:230)
    at process.emit (events.js:327:22)
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5)
    [... lines matching original stack trace ...]
    at R.log (C:\Users\Seb\AppData\Local\Programs\@trezorsuite-desktop\Trezor Suite\resources\app.asar\dist\app.js:1:2995) {
  code: 'ERR_STREAM_DESTROYED'
}
```

**Comment by bosomt** [comment] 2021-01-20 15:55
i was able to reproduce it on my computer

Suite: app 21.1.0 e31cc2b
OS: Win10 19042.746

**Comment by bosomt** [comment] 2021-01-21 09:40
I noticed that new directory structure is created when you start Suite app / commit e31cc2b2c0388e1b50f3f8fd529bc47d7e00fbef /

**Linux**
log is written to 
`/home/tbosansk/.config/@trezor/suite-desktop/@trezor/suite-desktop/logs/`
and not to 
`/home/tbosansk/.config/@trezor/suite-desktop/logs/`

**Windows**
`AppData\Roaming\@trezor\suite-desktop\Trezor Suite\logs`
`Trezor Suite` directory is created and only content is log directory , maybe we can create log directory in `suite-desktop` directory

**Comment by sorooris** [comment] 2021-01-28 11:16
Okay - after fiddling around with the runtime flags i think it works as intended, closing and approving!
Edit: confirmed with @keraf.

**Closed as completed by sorooris** 2021-01-28 11:16 UTC
