### ISSUE TITLE
Problem with suite in Tor browser

### ISSUE THREAD

**Issue by Dehumanizer77** [trezor/trezor-suite#3360] opened 2021-02-08 14:43 UTC
**Describe the bug**
Suite doesn't work when accessed via Tor browser.

**Steps to reproduce:**
1. open http://suite.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion/ via tor browser 
2. connect trezor and try to access the wallet (no matter if hidden or not)
3. in case of the hidden wallet, it says the hidden wallet is empty, in case of standard wallet it reports an error with discovery

**Info:** 
  - Suite version: web 20.12.1 (be4e3a36f7dbe15b2b203f66de11edc50a6665b8)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
 - OS: Linux x86_64
 - Screen: 1800x1000
 - Device: model T 2.3.2 regular

**Expected result:**
You get to your wallet

**Actual result:**
Standard wallet reports discovery error, hidden wallet says the wallet is empty.

**Comment by prusnak** [comment] 2021-02-08 15:26
Which version of the Bridge do you use (http://127.0.0.1:21325/status/) ? You need to have bridge at least 2.0.30 for .onion domains to work

Plus make sure you did all the steps described in https://wiki.trezor.io/Tor

**Comment by Dehumanizer77** [comment] 2021-02-09 11:11
I had 2.0.27 but with 2.0.30 it's the same. 
As for the instructions, I have done it before, without it, it couldn't connect at all.

**Comment by tsusanka** [comment] 2021-02-23 09:50
@trezor/qa please retest with 21.2.3

**Comment by bosomt** [comment] 2021-05-19 08:01
I was able to reproduce issue with latest version of Tor browser.
Device connected, Trezor Bridge is runnning.

<img width="1403" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/118776917-cb408b80-b888-11eb-8421-1c4b607666c4.png">


**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)

 - OS: MacIntel
 - Screen: 1584x990
 - Device: model T 2.3.4 regular

**Comment by bosomt** [comment] 2021-05-19 08:23
looks like Tor browser doesn't have access to localy running bridge

<img width="734" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/118780268-26c04880-b88c-11eb-8a82-dcad010618d8.png">

**Comment by keraf** [comment] 2021-05-19 08:29
@bosomt Looks like a different issue from what is originally described. The issue you encounter seems to be related with the Tor browser not letting you communicate with the bridge. There's a setting to change for that: https://wiki.trezor.io/Glossary:Tor

**Comment by bosomt** [comment] 2021-05-19 16:15
@keraf I thought that i need to adjust configuration so i went to google, to bad that not to our Wiki ;)

So i passed Bridge quest, but 5 of 5 tries i got `Init_IframeTimeout: Iframe timeout`
I'm not sure if this is problem on my side or same problem as when we released 21.5.1 and all users got this error


<img width="734" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/118847425-044f1f00-b8ce-11eb-8e5b-ce2f4de9bc4f.png">

**Comment by bosomt** [comment] 2021-05-19 16:38
**QA OK**

I was not able to reproduce problem, it just took some time due to Tor connectivity. 
Standard and passphrase wallet loaded correctly. Loaded even when I enabled all coins

<img width="233" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/118850264-e505c100-b8d0-11eb-8e4c-4f5929666c5d.png">

<img width="1131" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/118850055-a53ed980-b8d0-11eb-977f-a18e24ab96e5.png">

**Info**
Name 	Firefox
Version 	78.10.0esr
Build ID 	20210502170101
Useragent Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

**Comment by tsusanka** [comment] 2021-05-19 17:30
Closing then. Please reopen if this occurs again.

**Closed as completed by tsusanka** 2021-05-19 17:30 UTC
