### ISSUE TITLE
Passphrase redesign: Logic

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#895] opened 2019-12-10 09:10 UTC

**Comment by glacierbits** [comment] 2020-02-07 09:48
Merged via #1120

**Comment by sorooris** [comment] 2020-02-11 10:39
UX issue: Missing back button (or an option to correct a typo in passphrase)

User is not able to navigate back from the passphrase confirmation dialogue to the first passphrase entry to enter the correct passphrase (after typo and opening an empty hidden wallet).

![image](https://user-images.githubusercontent.com/10185314/74229685-2ae1db80-4cc3-11ea-9ae6-603a152d35cc.png)

**Comment by szymonlesisz** [comment] 2020-02-12 09:10
bugfix already merged

**Comment by petrsulc** [comment] 2020-02-14 11:27
@matejzak
Updated:
https://sketch.cloud/s/AK1WY/a/LE04PQ
https://sketch.cloud/s/AK1WY/a/7zy152

**Comment by wendys-cats** [comment] 2020-02-17 10:20
Issue: Confusing warning when creating a wallet with empty passphrase

suite.corp.sldev.cz/suite-web/develop/

Steps
Occurs after clicking on "My device", selecting "Add hidden wallet" and trying to create a hidden wallet with empty passphrase. (While the warning is technically correct, it can be confusing for many users, hence the request in this one particular scenario.)

Expected behaviour
In this particular case, please let the user access the standard wallet without the warning. 

Actual behaviour
When creating a hidden wallet with empty passphrase (technically a standard wallet), there will come up a warning "Passphrase duplicated. The hidden wallet that you are trying to create already exists".

**Comment by wendys-cats** [comment] 2020-02-18 11:02
suite.corp.sldev.cz/suite-web/develop/

**steps:**
1. Click on Create hidden wallet
2. Enter a typo in existing passphrase (make sure the generated wallet will be empty)
3. Enter the correct passphrase when confirming
4. There will be a mismatch notification. Click on the Retry.
5. Try to enter the correct passphrase again

**Expected behavior:**
The Retry option will start the process of creating a hidden wallet again. 

**Actual behavior:**
The Retry option directs you to the Confirm Passphrase step with NO option of going back/starting the process again. Clicking on the Create hidden wallet button will ALSO result in opening the Confirm Passphrase window, making the user stuck in a loop.  

**!!!** Please make sure that after getting a Passphrase Mismatch notification, suite and device will no longer wait for confirmation, so that the user will be able to create a hidden wallet without unplugging the device.

**Comment by sorooris** [comment] 2020-02-18 14:27
QA NOK:
Passphrase confirmation by pressing the Enter button on a keyboard does not confirm the focused Enter passphrase input; instead confirms a Standard wallet.
![image](https://user-images.githubusercontent.com/10185314/74744785-1a9da380-5263-11ea-81d1-8d8d068cf935.png)

**Comment by glacierbits** [comment] 2020-04-09 22:47
I believe we should remove the _< Try again_ button (after the _Retry_ Passphrase mismatch notification).

**Steps to reproduce:** 

Passphrase input: A
Passphrase input: B
Mismatch notification
Click _Retry_
Click _< Try Again_
Click _< Try Again_ (again)
Results in Authorization error

**Comment by wendys-cats** [comment] 2020-04-16 14:30
**Issue: Retry option for passphrase mismatch** 

**steps:**

Click on Create hidden wallet
Enter a typo in existing passphrase (make sure the generated wallet will be empty)
Enter the correct passphrase when confirming
There will be a mismatch notification. Click on the Retry.
Try to enter the correct passphrase again

**Expected behavior:**
The Retry option will start the process of creating a hidden wallet again.

**Actual behavior:**
The Retry option directs you to the Confirm Passphrase. 

video: https://drive.google.com/file/d/1p8nrUEbYyRyjSO8mc_g8w09rM4E-1aPS/view

**Comment by glacierbits** [comment] 2020-05-11 15:59
I believe this is a correct behavior, since the user receives the information they are about to enter "empty wallet" against their expectation to begin with (considering the "correct" hidden wallet is not empty anyway). However what you describe is a valid case, and I like the idea to add "start over" button or at least instruction to reconnect device so the user won't get stuck in the vicious circle.

**Comment by glacierbits** [comment] 2020-08-21 16:54
I came to a conclusion it is a correct behaviour. The case of [ Incorrect passphrase > Correct passphrase > Error notif > Fix 2nd input ] is handled by the second "Confirm empty passphrase" to begin with – in other words the user has been warned after the first input the wallet is empty. The case of the "correct" empty hidden wallet without a transaction history is a corner case not worth pursuing at the moment (unless user feedback proves otherwise).

**Closed as completed by glacierbits** 2020-08-21 16:54 UTC
Labels: feature
