### ISSUE TITLE
Desktop app - application navigation is broken

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2406] opened 2020-09-22 15:27 UTC
**Info:**
 - OS: Nixos
 - Wallet Version: app, commit c67a173aabdb7e5b4ea7a2de478707e96a27ced4
 - Firmware Version: 2.3.3 model T, revision 0d5f00668 
 
**Describe the bug**
and im not able to click on anything in desktop suite except http://blog.trezor.io/ in news
im not able to get to settings or to accounts

**Steps to reproduce:**
1. download Linux app build
2. try to navigate in app, try to go to settings or accounts 
3. observe

**Expected result:**
you can navigate in desktop app

**Actual result:**
you can't navigate in desktop app

**Comment by glacierbits** [comment] 2020-09-25 11:01
I assume this has been tackled already (remember seeing some conversation on Slack). Just to make sure assigning to you @keraf :) Thanks!

**Comment by slowbackspace** [comment] 2020-10-03 10:12
I patched nextjs so the issue is fixed for now, watch https://github.com/vercel/next.js/issues/17212 for proper fix in nextjs and remove the patch once we update to version that will include the fix.

**Closed as completed** 2020-10-05 11:56 UTC
Labels: bug

**Comment by bosomt** [comment] 2020-10-12 08:46
**QA OK**

Microsoft Windows [Version 10.0.18363.1082]
Suite win app commit a26355244abe0850d23e6c353b5e157f44f12694
Device Trezor model T 2.3.4
