### ISSUE TITLE
Option to Delete Tokens from ETH Token List

### ISSUE THREAD

**Issue by DerekMiner** [trezor/trezor-suite#4677] opened 2021-12-19 05:20 UTC
**Problem**
There is currently no way to remove tokens from the ETH portion of the wallet. Add a way to allow a user to remove the token from being tracked. This can cause trauma when seeing tokens in the wallet that the user held when they went to zero and they want to remove the scam coins from the wallet. They may have also put the incorrect contract in to track by accident, or moved the token out of the wallet and no longer wants to track that token in the future.

**Possible Solutions**
**Idea 1:** New X Button next to tokens in list to delete them from the Wallet and no longer be tracked
![deleteToken](https://user-images.githubusercontent.com/9966028/146664705-141e37b7-7c99-4103-b372-06c0a63bd063.jpg)

**Idea 2:** Button when clicked that enables user to select on tokens to delete with a checkbox or highlight, then

-After deleting with idea 1 or 2, have a confirmation panel ask to verify if user wants to remove tracking from wallet for the tokens selected

**Comment by Rav3nPL** [comment] 2022-07-29 15:44
We need that to remove scam tokens from the view... It's like this on my account:
![image](https://user-images.githubusercontent.com/1094027/181795463-d1431295-7559-40e3-80ad-0380fbd140b2.png)

There is also few tokens I owned long ago with zero balance, and I want to remove them also.
At this moment we have only "add" option.
![image](https://user-images.githubusercontent.com/1094027/181795775-3115c916-37e8-4e4b-804f-67680335e0d3.png)

**Comment by tomasklim** [comment] 2023-04-26 09:40
duplicate of #6595

**Closed as completed by tomasklim** 2023-04-26 09:40 UTC
Labels: feature
