### ISSUE TITLE
Suite, Coinjoin account is not aware of it's own transaction. (utxo already spent)

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#11827] opened 2024-03-28 20:00 UTC
I have many many utxo that cause "already spent error"

I sent to myself about 30 small UTXO to consolidate. 

The transaction is visible in the history, It clearly show it spend those UTXO but the list of UTXO still show those as available.

**Comment by MiroslavProchazka** [comment] 2024-04-08 09:53
@trezor/qa can you check this please?

**Comment by MiroslavProchazka** [comment] 2024-04-08 13:56
Hi @nostitos, thanks for reporting this issue. Unfortunately we have not been able to reproduce it yet. 
Can I ask you to check whether the Txs order is correct? (the transaction spending utxo is always after the transaction receiving it). 
Thank you.

**Comment by nostitos** [comment] 2024-04-09 16:03
There is no miss ordering,
The last transaction was there, confirmed and the details from the included
tx viewer shows the UTXO being spend are the same as those who are still
made available in coin selection.

**Comment by MiroslavProchazka** [comment] 2024-04-14 13:01
@trezor/qa any news regarding the reproducibility please? :) 
@marekrjpolak can you take a look at it please as well?

**Comment by MiroslavProchazka** [comment] 2024-04-16 11:27
I'm sorry, but we are not able to reproduce it. We would need your data, which we cannot request due to privacy reasons. Our QA/Devs were not able to find anything suspicious, and we haven't received similar reports from other users. I'm closing it for now until we find clues or new tickets come in.

**Closed as not planned by MiroslavProchazka** 2024-04-16 11:27 UTC
Labels: bug

**Comment by MiroslavProchazka** [comment] 2024-04-16 11:29
One more thing, could you please try to forget the remember wallet and load the Tx data from scratch?
