### ISSUE TITLE
Desktop app titlebar actions do not work when app has no focus

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#4243] opened 2021-09-07 09:59 UTC
**Describe the bug**
If the desktop app does not have focus, it is not possible to close it (minimise it or use fullscreen). However, other macOS apps can be closed without focus. Moreover, if I click on actions, it does not give focus to the window.

https://user-images.githubusercontent.com/33235762/132324912-44b6b648-8e1f-43f7-a5b0-4b7b9b74dc30.mov

**Steps to reproduce:**
1. Open desktop app on macOS
2. Give focus to another app
3. Try to close Suite

**Expected result:**
I am able to close unfocused app.

**Note(s):**
I think that we do something wrong with the whole macOS desktop app window, because I am unable to use Magnet app (https://apps.apple.com/cz/app/magnet/id441258766) to move and resize window using key shortcuts.

**Comment by bosomt** [comment] 2021-09-08 09:06
i was able to reproduce issue

**Info:**
 - Suite version: desktop 21.9.1 (7d9ab031275907086a2a20f4f3118c3632ef4904)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.1 regular

**Comment by alex-jerechinsky** [comment] 2021-09-08 09:07
Try this one please.
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/367051191

**Comment by alex-jerechinsky** [comment] 2021-09-08 09:08
It consistently works for me. 🎉

**Info:**
 - Suite version: desktop 21.10.0 (2debf49411803c570a43c66ea5eac84e61814710)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by bosomt** [comment] 2021-09-08 09:11
**QA NOK**

**Info:**
 - Suite version: desktop 21.10.0 (2debf49411803c570a43c66ea5eac84e61814710)
 - Suite version: desktop 21.9.1 (7d9ab03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.1 regular

https://user-images.githubusercontent.com/31506317/132481521-21a55453-d558-4dee-9818-8153f790c3b0.mov

**Comment by STew790** [comment] 2021-09-15 12:49
**QA NOK**

The same happens on Windows. I need to click on the window once to focus it and then I can close it.

**Info**:
 - Suite version: desktop 21.9.2 (cc85c69e3d6556e673c4d30f39953179f690b663)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.9.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.4.2 regular

**Closed as completed** 2021-11-02 12:12 UTC
Labels: bug

**Comment by bosomt** [comment] 2021-11-02 20:35
**QA OK**

**Info:**
 - Suite version: desktop 21.11.0 (4a56ae794159091a4f2c4de847d237a47657dc1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

@STew790 please retest on Windows if possible
