### ISSUE TITLE
BTC: "Transaction history not available" in one of my accounts

### ISSUE THREAD

**Issue by caglorithm** [trezor/trezor-suite#3650] opened 2021-04-15 08:23 UTC
**Describe the bug**
One of my Bech32 accounts doesn't show me the transaction history. I can click on the block explorer button (see screenshot) and I will see the transaction history. I can also see the account balance. Only the transaction history is gone. Other accounts are fine.

After I've sent a transaction to this account, my history appeared again (not shown). 

**Info:**
 - Suite Version 21.4.1 (21.4.1.11059)
 - OS: MacOS

**Expected behaviour:**
History should be visible in any case

**How to reproduce:**
I have no idea, but I found [a reddit post](https://www.reddit.com/r/TREZOR/comments/m3fbkh/why_isnt_trezor_suite_show_my_bitcoin_transaction/) with a user describing probably the same problem.

**Screenshots:**
![image](https://user-images.githubusercontent.com/7763212/114837631-34d60180-9dd4-11eb-8c9d-90cb069923b9.png)

**Comment by jerechinsky** [comment] 2021-04-21 16:12
Thanks for creating the issue, @caglorithm. I'm glad you were able to get your history to reappear. We'll use this issue to track more occurrences of this bug so we can hopefully replicate it and get to the root of it.

**Comment by slowbackspace** [comment] 2021-04-23 12:23
@alex-jerechinsky just fyi, I think I replicated the issue in https://github.com/trezor/trezor-suite/issues/3671. This one seems like a duplicate of it, but I am not totally sure if it the same cause, result certainly is the same.

**Comment by Daddy-C** [comment] 2021-05-12 15:11
I'm having the same issue with one of my BTC (Bech 32) accounts as well as my ETH ac
![Screenshot 2021-05-12 111046](https://user-images.githubusercontent.com/83146669/117999336-bc9b2700-b312-11eb-94cb-62a85ba13f52.jpg)
count - same error.

**Comment by tsusanka** [comment] 2021-10-19 09:28
@tomasklim we could this one along with the other transactions issues..

**Closed as completed** 2021-11-01 16:17 UTC
Labels: bug, transactions

**Comment by bosomt** [comment] 2021-11-10 11:24
**QA OK**

AFAIK issue will be fixed in 21.11.1 release that will be released today
https://github.com/trezor/trezor-suite/pull/4418
