### ISSUE TITLE
Infinite spinner on Firefox with myetherwallet.com

### ISSUE THREAD

**Issue by refi93** [trezor/trezor-suite#5749] opened 2022-07-06 08:12 UTC
**Describe the bug**
When I try to connect with my Trezor to myetherwallet.com from my Firefox browser (v102.0), connect.trezor.io ends up stuck at the "Connecting" spinner without further progress. On Chrome this doesn't seem to happen. I tried it also in incognito mode to rule out interference from extensions. I'm facing the same issue in https://adalite.io therefore it seems likelier to me that the issue is in connect rather than on the web wallet's side.

May be related to other reported issues: https://github.com/trezor/trezor-suite/issues/5644 and https://github.com/trezor/connect/issues/784

**Info:**

-   Browser: Firefox, 102
-   OS: Linux Mint 20.1 Cinnamon
-   Bridge: version: 2.0.27
-   Firmware Version: Trezor T, 2.5.1

**How to reproduce**

1. Go to 'myetherwallet.com' on Firefox
1. Try connecting with Trezor
1. connect.trezor.io ends up stuck on the "loading..." spinner

**Comment by sime** [comment] 2022-07-07 07:23
Hi @refi93 

Can you try toggling the options mentioned in #5644 ?

**Comment by refi93** [comment] 2022-07-07 17:41
thanks @sime - indeed, toggling the "enhanced tracking protection" off helped :+1: sorry I somehow overlooked that advice. Any chance this could be fixed or at least detected/mentioned by connect.trezor.io for better UX without the need to implement such checks for each web wallet separately?

**Comment by sime** [comment] 2022-07-08 08:28
It's something we are considering/looking into!

Closing as duplicate of #5644

**Closed as not planned by sime** 2022-07-08 08:28 UTC
Labels: bug
