### ISSUE TITLE
Suite passphrase settings does not reflect device settings

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#3567] opened 2021-03-25 10:58 UTC
**Describe the bug**
Your device is locked and you want to enable passphrase. You click on the switch and enter an incorrect pin. You get a notification, that pin was incorrect, but the switch is changed until you go to the settings again.

If you click on the switch again (without refreshing the page). It looks like that you want to disable it (put it into the initial state). Now you enter the correct pin and the device asks if you want to enable the passphrase (but Suite looks like that you want to disable it). You confirm it and the switch changes to "enabled".

**Steps to reproduce:**
1. You have a locked device
2. Settings > Device
3. Click enable passphrase
4. Insert the wrong pin

**Info:**
 - Suite version: web 21.3.2 (6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
 - OS: MacIntel
 - Screen: 1792x1120
 - Device: model One 1.9.4 regular

**Expected result:**
Suite should reflect device settings.

**Actual result:**
Suite does not reflect device settings.

**Screenshots:**
![Screen Recording 2021-03-25 at 11 40 51 (1)](https://user-images.githubusercontent.com/33235762/112462039-e5665d80-8d60-11eb-9522-dd98d1b2cc6a.gif)

**Comment by bosomt** [comment] 2021-03-26 06:10
I think it's same issue as https://github.com/trezor/trezor-suite/issues/2149

**Comment by jerechinsky** [comment] 2021-04-06 11:41
Correct, seems like it is duplicate of #2149. Thanks for raising this, though.

**Closed as completed by jerechinsky** 2021-04-06 11:41 UTC
