### ISSUE TITLE
Transaction signing error: Constructed transaction doesn't match the hash returned by the device.

### ISSUE THREAD

**Issue by shoojilipef** [trezor/trezor-suite#7025] opened 2022-11-25 11:17 UTC
Reproducible error: When attempting to transfer cardano from my trezor wallet to another ada wallet or ada address. It will work some times and other times it produces this error. My Trezor Suite was updated today to the latest version.

Error message received: Transaction signing error: Constructed transaction doesn't match the hash returned by the device.

**Comment by sime** [comment] 2022-11-25 11:22
@shoojilipef First time seeing this issue. Out of interest, do you have a 12 or 24 word seed phrase?

**Comment by sime** [comment] 2022-11-25 11:29
Ignore my question @shoojilipef. This is a duplicate of #6945.

Will be included in the next release.

**Closed as completed** 2022-11-25 11:31 UTC
