### ISSUE TITLE
Close button rendered only during on hover in Switch firmware modal

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10996] opened 2024-02-01 18:51 UTC
**Describe the bug**
Close button rendered only during on hover in Switch firmware modal
EDIT: see last 2 screenshots, there is no margin between `IMPORTANT!` text and modal border

**Steps to reproduce:**
1. Navigate to `Settings/Device` section
2. Try to change device firmware type
3. Observe `Close` button behavior

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
<img width="477" alt="Screenshot 2024-02-01 at 19 43 59" src="https://github.com/trezor/trezor-suite/assets/31506317/f648b435-154b-4f52-b313-9966d8893e40">
<img width="502" alt="Screenshot 2024-02-01 at 19 43 12" src="https://github.com/trezor/trezor-suite/assets/31506317/499bd305-8d58-4a9f-8c21-cb19f8b205a2">
<img width="478" alt="Screenshot 2024-02-01 at 19 43 06" src="https://github.com/trezor/trezor-suite/assets/31506317/69c4254a-d993-4344-8d1f-9a3d357e8530">

<img width="160" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/be3799eb-2098-4d69-b7dc-30e86d406d7b">
<br>
<img width="478" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/ae7a188b-43b6-4b26-836d-ec871ff21aa8">

**Comment by dahaca** [comment] 2024-02-02 15:44
duplicate of https://github.com/trezor/trezor-suite/issues/10960

**Closed as completed by dahaca** 2024-02-02 15:44 UTC
Labels: bug
