### ISSUE TITLE
update react-redux

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#5781] opened 2022-07-13 14:38 UTC
some context: https://github.com/trezor/trezor-suite/pull/4711#issue-1098109503

**Comment by matejkriz** [comment] 2022-08-03 11:08
duplicate of https://github.com/trezor/trezor-suite/issues/4651 but this one has HIGH priority and the other one LOW 🤔

**Closed as not planned** 2023-01-12 13:07 UTC
Labels: code
