### ISSUE TITLE
Trezor Suite (web) doesn't work with WebUSB on latest Chrome

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#3041] opened 2020-11-22 14:02 UTC
**Describe the bug**
Trezor Suite doesn't work with Trezor in the latest Chrome when you connect via WebUSB (don't have Trezor Bridge running). 
It recognizes the Trezor device but it won't connect. The same goes for Trezor Wallet, it just shows an error "Unable to reset the device".
**Info:**
 - Suite Version: web, production
 - Browser: Chrome , version 87.0.4280.66
 - OS: Windows 10 
 - Firmware Version: all

**Steps to reproduce:**
1. Uninstall or kill your bridge
2. Open Chrome.
3. Go to either https://wallet.trezor.io/ or https://suite.trezor.io/web/.
4. Connect your device.
5. Click on "Check for devices" and select your device.
6. In the wallet you will see an error (screenshot 1) and in Trezor Suite you won't be able to connect the device with the web (screenshot 2).

**Expected result:**
You should be able to connect to either Trezor Suite or Trezor Wallet via WebUSB.

**Screenshots:**
Screenshot 1
![image](https://user-images.githubusercontent.com/48477147/99905722-f760c280-2cd2-11eb-9839-f3d90c7d104d.png)
Screenshot 2
![image](https://user-images.githubusercontent.com/48477147/99905734-09426580-2cd3-11eb-91e2-903005743bb2.png)

**Comment by prusnak** [comment] 2020-11-22 14:43
Google changed their USB implementation in Chrome 87 for Windows. I've seen the same error with Ledger, so this is not specific to Trezor. Let's hope Google fixes this soon. Meanwhile we can investigate whether it is possible to workaround this issue somehow.

**Comment by karelbilek** [comment] 2020-11-23 09:37
https://source.chromium.org/chromium/chromium/src/+/master:services/device/usb/usb_device_handle_win.cc;l=351

Here is the new implementation. Seems like this is the culprit

```
void UsbDeviceHandleWin::ResetDevice(ResultCallback callback) {
  DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);

  // Resetting the device is not supported on Windows.
  task_runner_->PostTask(FROM_HERE, base::BindOnce(std::move(callback), false));
}
```

**Comment by prusnak** [comment] 2021-01-15 09:23
This should've been fixed already via this commit in trezor-link: https://github.com/trezor/trezor-link/commit/c69d83bfd62679cebf8f9f10c343d12ecf567c2b

(which got propagated into Suite via Connect 8.1.19)

**Comment by mroz22** [comment] 2021-01-15 09:36
Yes, should have been but seems like it is not. I managed to setup windows debugging environment finally so I am looking into it.

**Comment by mroz22** [comment] 2021-01-24 19:10
Just found that this throws here https://github.com/trezor/trezor-link/blob/c69d83bfd62679cebf8f9f10c343d12ecf567c2b/src/lowlevel/webusb.js#L196
in case device.reset() threw on line 187

**Comment by glacierbits** [comment] 2021-02-04 09:55
@trezor/qa Can you please retest? Not sure this issue persist.

**Comment by bosomt** [comment] 2021-02-05 11:36
**QA OK**

I was not able to reproduce it with Web version of Suite in Chromium

**Info:**
 - Suite version: web 21.2.1 (a63b29d19ff08ece94be28d2997d4265ac1c84fc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.4 regular + 1.9.4

**Comment by tsusanka** [comment] 2021-02-05 11:57
@STew790 could you retry? Seems like you had some more luck :eyes:

**Comment by dsmid** [comment] 2021-02-09 15:04
I have tested the WebUSB access on two devices:

1. Chrome 88.0.4324.146 on Windows 10 without the bridge running
- both wallet.trezor.io and suite.trezor.io/web work
- clicking "+Find Trezor" button brings the WebUSB connection dialog

2. Chrome 88.0.4324.153 (latest) on Chromebook Acer R11
- wallet.trezor.io works fine after giving permission to access Trezor One (fw 1.9.3) over WebUSB
- suite.trezor.io/web doesn't work and clicking "+Find Trezor" button doesn't bring the WebUSB connection dialog

**Comment by sorooris** [comment] 2021-02-09 15:31
**QA OK**

@tsusanka neither @wendys-cats nor I couldn't replicate the issue on our machines but @STew790 had a rogue gnome on his during his retest yesterday, I instructed him to post his findings here.

Suite: web 20f555fc, be4e3a3
Bridge: process stopped, uninstalled
Browser: Chromium 87.0.4280.66, 88.0.4324.150
OS: NixOS 20.09, macOS Big Sur 11.2

**Comment by STew790** [comment] 2021-02-09 17:13
I tried it again on updated Win10 with the latest version of Chrome (88.0.4324.150) and on suite.trezor.io and for some reason, it still doesn't work for me and now it doesn't work at all with FW 2.3.4. What is strange is that I tried it with FW 2.3.5 and it lets me in as you can see on the screenshots but I can't see anything else other than that the Trezor is connected. I will try it again on a different setup. Let me know if I can get any more info, please.
![image](https://user-images.githubusercontent.com/48477147/107400429-187ec580-6b02-11eb-9366-cc2c476f26db.png)

![image](https://user-images.githubusercontent.com/48477147/107400714-61367e80-6b02-11eb-8a38-272aa130f931.png)

**Comment by tsusanka** [comment] 2021-02-09 18:50
Also please discuss together how your system differs to @sorooris's or @wendys-cats'. Maybe you are on Windows?

**Comment by dsmid** [comment] 2021-02-09 19:03
> 1. Chrome 88.0.4324.153 (latest) on Chromebook Acer R11
> 
> * wallet.trezor.io works fine after giving permission to access Trezor One (fw 1.9.3) over WebUSB
> * suite.trezor.io/web doesn't work and clicking "+Find Trezor" button doesn't bring the WebUSB connection dialog

I have found out that the issue described above is unrelated to this.
Most probably due to unexpected font size/zoom settings, the "+Find Trezor" button becomes unresponsive (although it changes color when clicked). It worked when I displayed the page fullscreen.

**Comment by sorooris** [comment] 2021-02-10 10:04
@tsusanka All three of us have the same version of Windows - 10.0.19042.746. We will investigate further and hopefully extract some clear steps to reproduce - after release.

**Comment by tsusanka** [comment] 2021-02-25 09:57
@sorooris what's the verdict on this one?

**Comment by sorooris** [comment] 2021-02-25 11:44
Investigated and @STew790 will post details - couldn't replicate, let's close this issue :smirk:

**Comment by STew790** [comment] 2021-02-25 11:48
Tested this on 2 Win10 PCs today (thoroughly). Latest wallet and latest Trezor Suite works with WebUSB properly. After asking for a connected device, just selected the device and got into wallet/suite. **QA OK**

Suite: Web 9cf47b5b526bbb5cda585e717fbbf0f5b93b8cc0
Bridge: uninstalled
OS: Windows 10 [10.0.19042.804]
Browser: Chrome 88.0.4324.182

**Comment by tsusanka** [comment] 2021-02-25 12:01
Ok :pray:. Closing then.

**Closed as completed by tsusanka** 2021-02-25 12:01 UTC
Labels: bug
