### ISSUE TITLE
btc explorer vs suite differences

### ISSUE THREAD

**Issue by soucek87** [trezor/trezor-suite#3695] opened 2021-05-03 08:58 UTC
**Describe the bug**
There is a difference in what says the btc explorer and Suite. The current balance, the nr. of TXs, and outgoing amount are different.

**Firmware version and revision**
Suite log available at request.

**Desktop/smartphone setup:**
 - Wallet software: Trezor Suite web
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
 - Version commitHash: "1baa8ced16f2f6a5d60e9f4d7911669f856123d8"

**Expected behavior**
Btc explorer should show the same details as Suite.

**Comment by jerechinsky** [comment] 2021-05-04 11:31
Hi @soucek87, could you please provide the suite log? alexandr.jerechinsky@satoshilabs.com
Thank you.

**Comment by bosomt** [comment] 2021-07-20 14:24
**QA OK**

closing, only difference could be caused by different mempools of unconfirmed transactions.
In last months there were 250.000 tx in mempool. Now empty. Closing

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.2 regular

**Closed as completed by bosomt** 2021-07-20 14:24 UTC
