### ISSUE TITLE
Check backup modal on T1 doesn't allow you to type into text field

### ISSUE THREAD

**Issue by STew790** [trezor/trezor-suite#11411] opened 2024-03-02 14:52 UTC
**Describe the bug**
When I try to check my backup on T1, in the modal I can't write any word, I can only select it from the drop-down menu. Also, for some reason the drop-down menu with words first appears in the top left corner until I click into the text field.

**Steps to reproduce:**
1. Connect T1 device
2. Go to Settings/Device
3. Select "Check backup"
4. Try to write anything into the text field

**Info:**
 - Suite version: desktop 24.2.4 (748176286ae231aae44c83981a62b174b7605e1a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.4 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T1B1 1.12.1 regular (revision 1eb0eb9d91b092e571aac63db4ebff2a07fd8a1f)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
I am able to write my seed words into the text field

**Actual result:**
I can't write anything into the text field

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/48477147/db864ffb-8e77-4311-b236-0ce553a2f6b6)

https://github.com/trezor/trezor-suite/assets/48477147/b6bce085-04b1-470d-92f7-5f01d6527365

**Comment by STew790** [comment] 2024-03-02 14:53
Just to add, when I select one word with my mouse, the word isn't really selected but then I can actually write.

**Comment by MiroslavProchazka** [comment] 2024-03-04 09:21
Duplicate of [#10720](https://github.com/trezor/trezor-suite/issues/10720)

**Closed as completed by MiroslavProchazka** 2024-03-04 09:21 UTC
Labels: bug
