### ISSUE TITLE
Custom homescreen upload

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1157] opened 2020-02-07 13:09 UTC
- [ ] Validation (?)
- [ ] Cropping (?)

Include Model One in the process.

**Comment by prusnak** [comment] 2020-07-26 19:01
Duplicate of https://github.com/trezor/trezor-suite/issues/945

**Comment by jimbojw** [comment] 2021-04-05 18:25
Is this still on the roadmap?

**Comment by tsusanka** [comment] 2022-02-11 17:32
I think this has been done by https://github.com/trezor/trezor-suite/pull/4725?

**Closed as completed** 2022-02-13 08:33 UTC
Labels: feature
