### ISSUE TITLE
 Missing padding or alignment in fraudulent transaction warning

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10999] opened 2024-02-01 20:46 UTC
**Describe the bug**
Missing padding or proper alignment in fraudulent transaction warning

**Steps to reproduce:**
1. Compare fraudulent transaction warning on production and develop version

**Info:**
 - Suite version: web 24.2.0 (d3a7b23a070f251e1ef5cfd9064a2b1d3d779026)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: WebUsbTransport

**Screenshots:**
<img width="696" alt="Screenshot 2024-02-01 at 21 41 41" src="https://github.com/trezor/trezor-suite/assets/31506317/872e16bc-be3c-426a-b8d0-e769d849d430">
<img width="588" alt="Screenshot 2024-02-01 at 21 41 02" src="https://github.com/trezor/trezor-suite/assets/31506317/0059d2b0-af32-4b39-8f06-7befbf100756">

**Comment by AdamSchinzel** [comment] 2024-02-02 06:57
Duplicate of https://github.com/trezor/trezor-suite/issues/10956

**Closed as completed by AdamSchinzel** 2024-02-02 06:57 UTC
