### ISSUE TITLE
Suite asks for access to microphone

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7337] opened 2023-01-06 12:45 UTC
**Describe the bug**
When I try to change input field 

**Steps to reproduce:**
1. Access CoinJoin account
2. Go to `Account` tab (next to `Overview`)
3. Change desired anonymity in input field

It happens only once during first launch of newly installed Suite (and then again with newly updated)...

**Info:**
 - Suite version: desktop 23.2.0 (f9ffa4407c135dafc0b330b2f42be419ac181199)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
Nothing happens

**Actual result:**
Suite asks for microphone permission

**Screenshots:**
![Snímek obrazovky 2023-01-06 v 13 36 39](https://user-images.githubusercontent.com/26002916/211014059-865174d4-d90d-4d4c-81f6-383bd4ed2766.png)

**Comment by hynek-jina** [comment] 2023-01-16 14:40
@trezor/qa 
Were anyone able to reproduce it anyhow...?

**Comment by bosomt** [comment] 2023-01-16 15:00
@hynek-jina i was not able to reproduce this issue

**Comment by STew790** [comment] 2023-01-16 15:36
@hynek-jina same here, unfortunately, I will close it. Let's reopen if this ever happens again.

**Closed as completed by STew790** 2023-01-16 15:36 UTC
Labels: bug, account, coinjoin
