### ISSUE TITLE
Acquire error initalise failed: unexpected error when empty device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#12562] opened 2024-05-24 14:03 UTC
**Describe the bug**

- i am getting `Acquire error initalise failed: unexpected error` error lots of times when trying to acquire wiped device mostly
- Including 400 bad request errors/responses from node bridge
- only quit and start of whole app/bridge helps /reconnect of device or reload of app does not help/
- its same behavior if you run new app as source of bridge and you use production web wallet
- i will try reproduce it with new bridge that will save log file
- it happens on **mac** and on **win** machine

**Steps to reproduce:**
1 Wipe device and reconnect it
1 Update device that includes wiping of device
1 ???

**Info:**
Suite version: desktop 24.6.0 (https://github.com/trezor/trezor-suite/commit/b6ccc949b30d2c22cfc9a3e59bfe0459a32dc693)
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
    OS: Win32
    Screen: 1920x1080
    Device: Trezor T2B1 2.7.0 regular (revision null)
    Transport: BridgeTransport 3.0.0

**Screenshots:**
![telegram-cloud-photo-size-4-5947173913089916915-x](https://github.com/trezor/trezor-suite/assets/31506317/c1d3bd55-102b-4c5a-8350-dbca78cd311d)
![telegram-cloud-photo-size-4-5947173913089916916-y](https://github.com/trezor/trezor-suite/assets/31506317/c0f8155b-84aa-4a51-befa-41cdd7941b6f)

**Comment by mroz22** [comment] 2024-05-29 17:27
just tested now and was unable to reproduce. it is possible that if there really was a problem related to wipe device, it might have gone away after this was merged https://github.com/trezor/trezor-suite/pull/12550

logs should be already in working state now. maybe they are not very information rich but this is something I can fine-tune later. 

I can imagine that this error can still occur when you are doing some crazy things with multiple instances of suite/connect

**Comment by bosomt** [comment] 2024-05-30 09:03
Managed to replicate it by connecting device in BL mode but suite still thinks that its connected in standard mode.
Attached log from node bridge status page



[trezor-bridge(6).txt](https://github.com/trezor/trezor-suite/files/15496431/trezor-bridge.6.txt)


Info:

    Suite version: desktop 24.6.0 (https://github.com/trezor/trezor-suite/commit/337fabb4cc48a3ef0c3dbc3b970468b3127a162e)
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
    OS: Win32
    Screen: 1920x1080

**Closed as completed** 2024-06-26 15:22 UTC
Labels: bug

**Comment by bosomt** [comment] 2024-07-09 11:54
**QA OK**

i was not able to replicate issue for some time

**Info:**
 - Suite version: desktop 24.7.1 (88dbe0410ac5b6245f392ce13e8c30f0f8f549f2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 bitcoin-only (revision null)
 - Transport: BridgeTransport 3.0.0
