### ISSUE TITLE
Cant send Dogecoins from Trezor - Failed to send transaction Error details: Requested unknown tx

### ISSUE THREAD

**Issue by SvenBudak** [trezor/trezor-suite#3311] opened 2021-01-30 00:31 UTC
Hi. I just tryed to send my dogecoins. i created a deposit adress and try to send to this adress. when i submit i get an error:

```
Failed to send transaction
Error details: Requested unknown tx:
```

Is this a bug inside the firmware of trezor? because the loading indicator is also stuck on display on my trezor model T at about 22%

**Comment by prusnak** [comment] 2021-01-30 08:06
This is the issue affecting the whole Dogecoin network. There are not enough public nodes to sync with. If you run any Dogecoin wallet, you'll face the same issues. The network is not well interconnected and it's not handling the influx of new transactions very well.

Please keep trying.

**Comment by SvenBudak** [comment] 2021-01-31 20:24
@prusnak Thank for the answere! One question... Can i use somehow any node that makes my transaction work? its ok if it costs money.

**Comment by prusnak** [comment] 2021-01-31 21:59
Yes, you can try to resubmit the transaction via any other node.

**Comment by SvenBudak** [comment] 2021-01-31 22:04
can you recommend anyone?

**Comment by Head** [comment] 2021-01-31 22:07
This seem to be a different problem here. Sven cut off the TX id here. He's sent it to me and it's the incoming TX from Kraken to his wallet. Seems like the trezor backend can't find this OLD tx to generate the raw TX, while it is visible and confirmed on their own block explorer.
(also Trezor nodes are up to date right now https://doge1.trezor.io/ Last Block | 3588834 -- | -- Last Block Update | Sun, 31 Jan 2021 22:04:51 UTC)

**Comment by prusnak** [comment] 2021-01-31 22:17
@Head can you send me the TXID? Ideally with link to some dogecoin explorer which clearly shows the TX has been mined already. It's impossible to debug the issue without it.

**Comment by SvenBudak** [comment] 2021-01-31 22:24
@prusnak Thank you for taking the time to do this. I have sent you the TX by email.

**Comment by prusnak** [comment] 2021-01-31 22:30
@SvenBudak which firmware version are you on?

**Comment by SvenBudak** [comment] 2021-01-31 22:33
Firmware: 2.3.4

I just bought the Trezor 1 or 2 weeks ago and set it up. I was wondering if a Google Chrome installer should be running during the installation. I have canceled this. I think that has but rather nothing to do with it ;)

**Comment by prusnak** [comment] 2021-01-31 22:34
Can you please try our new Trezor Suite - https://suite.trezor.io - if it has the same problem?

**Comment by SvenBudak** [comment] 2021-01-31 22:39
Thanks, I had already tried that. only the error message there is worded slightly differently:

Instead of:
Failed to send transaction
Error details: Requested unknown tx:

it says:
Sign transaction error: requestTxInfo: Requested unknown tx:

Ah and I forgot to mention that the loading indicator on the Trezor T display stops at 25%. Then I have to disconnect the device from the USB to get it running again.

**Comment by Ivanov345** [comment] 2021-01-31 22:59
Hi,
I have the same problem with Tresor One FW 1.9.3. My Doge is since 25.08.20 in the wallet. I have tried to send it many times and I have always the same error like SvenBudak. I bought new Dogecoin but sent it to the same address. Sometimes the display goes to 10%, sometimes 0%. I suggest because  one of the  tx-es is ok and the other one not. I can't choose from which tx I want to make the transaction, so I can't tell if the second part could go trough. 

I hope you can find a solution, because you will be helping both of us. If you want some Information about my device you can get it from the Support. Jirka was my contact there. He gave me this post for more information.  May be you can check for similarities and cause of the problem.

**Comment by Ivanov345** [comment] 2021-02-01 23:01
I found a way to send and sell my Doge in 15 minutes. 

I am writing an Email to @SvenBudak so he can do it too. If you want some information I will tell you as well.

**Comment by SvenBudak** [comment] 2021-02-02 01:50
i still hope for a serious solution...

**Comment by szymonlesisz** [comment] 2021-02-02 09:31
fix is on the way

**Comment by prusnak** [comment] 2021-02-02 13:02
@SvenBudak @Ivanov345 we've released the fix to wallet.trezor.io that should help with the issue - please try now

**Comment by SvenBudak** [comment] 2021-02-02 13:24
@prusnak AWESOME! It is working! :) Thanks alot for the fix!

**Comment by Ivanov345** [comment] 2021-02-02 13:33
Nice a little to late for me, I couldn't try it, only took the damage because of the ignorance by the support, which told me just to keep trying. Because there was no problem with the app or the device

**Comment by SvenBudak** [comment] 2021-02-02 13:39
@Ivanov345 I think it was a misunderstanding in communication in the beginning. If my friend had not made clear what the problem was, no one would have understood what my problem was, because my knowledge about crypto transactions is too poor to describe the problem correctly. I am thankful that they have loaded a fix live within only 2 days.

**Comment by prusnak** [comment] 2021-02-02 13:42
Thanks @SvenBudak for confirmation. Closing

**Closed as completed by prusnak** 2021-02-02 13:42 UTC
Labels: bug
