### ISSUE TITLE
Desktop app external links

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2395] opened 2020-09-21 18:40 UTC
External links from desktop app open an electron web window as opposed to default browser.

**Comment by keraf** [comment] 2020-09-21 19:30
This was fixed in PR #2275 and should be fixed for the next release.

**Comment by glacierbits** [comment] 2020-09-21 19:32
Thanks!

**Comment by bosomt** [comment] 2020-09-22 06:50
downloaded latest build from https://suite.corp.sldev.cz/suite-desktop/develop/
commit **c67a173aabdb7e5b4ea7a2de478707e96a27ced4**
linux version

and im not able to click on anything in suite except http://blog.trezor.io/ in news
im not able to get to settings or to accounts

**Comment by keraf** [comment] 2020-09-22 12:35
Huh, seems like the navigation got broken. Could you open a new (high priority) issue for this please? 

In the meantime, do the news link open in the default browser or within the app? If it's the former, this issue can be closed as resolved. Previously, it would open it as a new app window.

**Comment by bosomt** [comment] 2020-09-22 15:28
@keraf 

1) created https://github.com/trezor/trezor-suite/issues/2406
2) news links are open in default system browser and not in electron, i can close this issue ?

**Comment by keraf** [comment] 2020-09-22 15:30
@bosomt Yep, working as intended :slightly_smiling_face:

**Comment by bosomt** [comment] 2020-09-23 10:21
**QA OK**

Nixos + Chromium 85
Suite web dev master commit c67a173aabdb7e5b4ea7a2de478707e96a27ced4
FW 1.9.1 commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Closed as completed by bosomt** 2020-09-23 10:21 UTC
Labels: bug
